### ISSUE TITLE
Add option to only change cursor etc instead of full theme

### ISSUE THREAD

**Issue by xtprion** [AutoDarkMode/Windows-Auto-Night-Mode#103]
Auto dark mode have a feature to change theme, but sometimes it can mess with other tools. For instance, i use dynamic wallpaper, and when ADM kicks off, theme change and the wallpaper change to the one that i set when making the theme. (make an option to select or ignore some theme aspect like wallpaper, color, cursor etc, just like on my screenshot below)
![image](https://user-images.githubusercontent.com/46372297/83827765-5290ff80-a709-11ea-8d5d-eed2a4e2d71b.png)

**Comment by Armin2208** [comment]
Is the screenshot from real software? Can you send me a link?

**Comment by xtprion** [comment]
Sorry for a late reply. I got it from SecureUxTheme

Here the link: https://github.com/namazso/SecureUxTheme

**Comment by Spiritreader** [comment]
done.

![image](https://user-images.githubusercontent.com/18438899/196757337-f7124618-6587-4ab3-882d-cecef73b5f14.png)
