### ISSUE TITLE
Feature Request: Switch to Dark Mode on Battery Power

### ISSUE THREAD

**Issue by AndrewGaspar** [AutoDarkMode/Windows-Auto-Night-Mode#114]
I have an OLED panel on my laptop, and so there are battery life benefits to being on dark mode. However, when I'm plugged in _during the day_, I'd prefer light mode. It would be a useful feature, for me, if Auto Dark Mode had a way to turn on Dark Mode when switching to battery power, even outside my normal dark mode start/stop times.

**Comment by Spiritreader** [comment]
added in 800860d

**Comment by AndrewGaspar** [comment]
@Spiritreader Awesome, thank you!

**Comment by Spiritreader** [comment]
Sorry for the delay on this making it to the release.
This is now included in the new version X release we released to the public today.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26

Thank you for your idea! I've been told by a lot of people they really like this!
