### ISSUE TITLE
Office theme change without reopening

### ISSUE THREAD

**Issue by emberaholdon** [AutoDarkMode/Windows-Auto-Night-Mode#120]
Is it possible to change Office theme without reopening all Office apps? The mechanism should exist because when you change the theme in the Office settings, it changes instantly and across all Office apps.

Thanks and keep up the great work.

**Comment by Armin2208** [comment]
there are no information about this right now, so it's seems like it's not possible

**Comment by Eisermann** [comment]
I am interested on this as well, I forked project and will try to investigate

**Comment by emberaholdon** [comment]
While you guys at it, would it be possible to select dark gray instead of black for Office?

**Comment by Armin2208** [comment]
wouldn't make much sense, because dark gray doesn't make the pages in outlook and OneNote dark :) and it's pretty light tbh

**Comment by jonferreira** [comment]
any joy?

was scratching my head trying to understand why my outlook wasn't changing theme even though it was supposed to and finally found this thread

**Comment by emberaholdon** [comment]
> any joy?
> 
> was scratching my head trying to understand why my outlook wasn't changing theme even though it was supposed to and finally found this thread

Seems like only insider channel has this option, the current channel (even though the build number is higher) does not yet.

**Comment by jonferreira** [comment]
hmm OK...

I do have the Black office theme and can change it manually but Auto Dark Mode can't change it automatically without restarting

**Comment by KingfisherAU** [comment]
Has there been any progress on having the Office 365 programs also automatically switch themes without having to close and reopen them?

**Comment by Armin2208** [comment]
fixed by Microsoft in Office 365 and 2021
