### ISSUE TITLE
Align Dropdown menu to center

### ISSUE THREAD

**Issue by pc-v2** [AutoDarkMode/Windows-Auto-Night-Mode#127]
**Describe the bug**
the dropdown menu is not centered

**To Reproduce**
1. Go to Apps section
2. Click on any dropdown menu
3. See error

**Expected behavior**
the dropdown menu become centered
![Illustration2](https://user-images.githubusercontent.com/58063311/86629956-58bf1800-bff6-11ea-86c4-27c8afa84439.jpg)

**Screenshots**
![image](https://user-images.githubusercontent.com/58063311/86629663-f1a16380-bff5-11ea-9d6e-aca65c6bb2c4.png)

**Environment:**
 - OS Version: [e.g. Windows 10 2004 Dev]
 - Auto Dark Mode version number [e.g. 3.0]
 - Do you use Windows .theme switcher? no
 - Has user admin rights? no
 - which antivirus software you use? Windows Defender
 - what language is your Windows set to?

**Comment by Spiritreader** [comment]
The UI has been completely revamped in Version X. This issue is solved.

https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26
