### ISSUE TITLE
Feature suggestion - TeamViewer dark mode

### ISSUE THREAD

**Issue by emberaholdon** [AutoDarkMode/Windows-Auto-Night-Mode#129]
TeamViewer also has a dark mode but unfortunately it does not respect system settings, so Auto Dark Mode could flip its registry key:

HKEY_CURRENT_USER\SOFTWARE\TeamViewer
ColorScheme (DWORD) = 1 (light theme) / 2 (dark theme)

I suspect there are several other apps that are using their own registry keys for their respective color schemes, so the "Apps" section of this tool could be extended greatly. :)

**Comment by EndPositive** [comment]
I would like to help with this. How do we want the apps page to be shaped? I can imagine there will be more apps like this and with the current setup that might become a long page.

**Comment by emberaholdon** [comment]
What first comes to mind is the Nvidia control panel, where there is a dropdown list of the supported apps and then below it are the options for the selected app.

I think something like this would fit into the current UI nicely without needing much layout change:

![app_selector](https://user-images.githubusercontent.com/67831954/87185431-0cbbee00-c2ea-11ea-8758-8976b9be32e3.png)

**Comment by Armin2208** [comment]
I've planned something that allows users to add their own registry keys for apps that support theme switching. We need a more flexible UI that incorporates this and I'm already working on conceptualizing it. 
Still, thank you for your contribution. I can potentially use parts of it to make the overall experience better

**Comment by emberaholdon** [comment]
> I've planned something that allows users to add their own registry keys for apps that support theme switching.

That's a very neat idea.

**Comment by Armin2208** [comment]
For this you can now run your own scripts in Auto Dark Mode Beta.

Check out our wiki page: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts

Thanks for your issue and being patient.

**Comment by Spiritreader** [comment]
Custom scripts have been in stable for a while now.
Support for individual programs will probably not make it into ADM and we will refer to our custom scripts instead, unless it's a more complicated endeavor that requires maintenance from our part (if we have the resources).
