### ISSUE TITLE
Taskbar not adapt to theme sometimes.

### ISSUE THREAD

**Issue by iseeghosts** [AutoDarkMode/Windows-Auto-Night-Mode#133]
First of all, thanks for making this great program.
While all the programs and icons adapt to the current theme - the taskbar remained in the previous theme.

1. Set to automatic scheduling
2. Shut down the device when in Dark Mode
3. Turn on the device outisde of dark theme schedule
4. Everything is in light mode except the taskbar

**Expected behavior**
Everything should be in light mode

**Environment:**
 - Windows 2004
 - Auto Dark Mode v3.0
 - Admin rights - yes
 - Antivirus software - Windows Defender
 - Windows language - English (U.S)

**Comment by Spiritreader** [comment]
We have released Version X with many new improvements and fixes. Please try again, and reopen the issue if it still doesn't work.

You can find the release version here!
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26
