### ISSUE TITLE
[Suggestion] Add an option to have multiple wallpapers for day/night cycle

### ISSUE THREAD

**Issue by scotrod** [AutoDarkMode/Windows-Auto-Night-Mode#141]
Auto Night Mode is great, what I would like to see in the program is the feature to add multiple wallpapers and the ability to switch them at every x minutes past.

I'm leaving a poorly edited screenshot of what I mean.

![Annotation 2020-07-21 213604](https://user-images.githubusercontent.com/45900128/88093548-d4929600-cb9a-11ea-86fe-f3539eeefbdc.png)

**Comment by Armin2208** [comment]
Hi! Thanks for your request. Please use the the Windows Theme mode and select a windows theme with a slideshow :)

**Comment by scotrod** [comment]
I did not managed to make it work because Windows won't let me name my theme... I'll try to update to 2004 and hope that this will be fixed.
Once again, I'm disappointed by Windows and amazed by your program.
Well done, sir!

**Comment by chonty** [comment]
I recommend WinDynamicDesktop: https://github.com/t1m0thyj/WinDynamicDesktop/releases // https://www.microsoft.com/en-us/p/windynamicdesktop/9nm8n7dq3z5f?activetab=pivot:overviewtab

**Comment by emberaholdon** [comment]
[Scene Flow](http://sceneflow.zogolo.tn/) is another excellent dynamic wallpaper app, I use it without any issue.

**Comment by Armin2208** [comment]
If I'm honest: I plan to make the Auto Dark Mode wallpaper switcher more enhanced anyways

**Comment by Spiritreader** [comment]
The way this will eventually make it into ADM will be slideshow support. That issue is tracked in #247. For all other methods, we kindly refer to apps such as WinDynamicDesktop. 

Closing this in favor of the other tracked issue.
