### ISSUE TITLE
[Feature Request] Ability to enter zip code or custom lat/lon instead of GPS

### ISSUE THREAD

**Issue by Rex501st** [AutoDarkMode/Windows-Auto-Night-Mode#145]
Hi, I recently moved from one state to another, and sadly, ADM thinks I'm still in the old state so I have to configure it to use time instead of GPS. I would prefer using zip code in the future to prevent this rare but annoying issue. 

Maintainer comment on progress
- [x] backend support (bb8d11d)
- [x] frontend support

**Comment by emberaholdon** [comment]
Isn't it Windows that thinks you're in another place? Make sure the location services are enabled and time and date is set to automatic in Windows settings.

**Comment by MercuryXIII** [comment]
> Isn't it Windows that thinks you're in another place? Make sure the location services are enabled and time and date is set to automatic in Windows settings.

I have. Even set the default location to my new location. Sadly, this is an issue with the service provider Microsoft uses for location. When they get something based off your IP Address, they base your location off of the IP Address. (at least that's what I was told by eero)

I have been able to fix this since moving with all my browser stuff, but sadly, ADM is one app that still thinks I'm in my old state.

**Comment by AndrewGaspar** [comment]
Yeah, I have the same issue - For some reason Windows doesn't recognize correlate my IP Address to location very accurately, either. It's actually kind of obnoxious because it breaks things like YouTube TV if you aren't careful to not allow it to use Windows location data.

**Comment by mikesafari** [comment]
Would like this as well but for a different reason: my business machine has location services disabled completely, so I cannot truly automate this based on time of day.

An implementation like what of f.lux would be great.

**Comment by ArestouMars** [comment]
@Armin2208 Sorry to bug you, is there any work being done on this? Or anyway to have users use their own API via OpenWeatherMap?

**Comment by Armin2208** [comment]
project is currently on hold and priorities are different. But I noted it and will see what I can.

**Comment by Spiritreader** [comment]
This issue now serves as collection for all zipcode or lat/lon requests

**Comment by Spiritreader** [comment]
## What changes with #145:
The Auto Dark Mode backend now supports setting **custom latitude and longitude values.**
You will have to retrieve these values manually and enter them.
This decision was made based on the highly requested feature of not having to rely on geolocator services.

As such, ADM version X will support the following modes
- Using the Windows Geolocator Service
- Using the Windows Default Location
- Using custom latitude/longitude values

## What will not change
We will **not** add any kind of support for
- postal/zip codes
- city names 
- map selectors.
There will be **no auto-conversion to a city name** in the frontend either.

From a privacy standpoint, this would expose exactly the same issue as using the Windows default location.
As such, future requests in this regard will be closed and referrred to the lat/lon feature for the forseeable future.

**Comment by Armin2208** [comment]
![image](https://user-images.githubusercontent.com/32982430/135347154-3aa78f5e-ad14-46b3-9d89-76c1c1830310.png)

release: 5th october

**Comment by Rex501st** [comment]
@Armin2208 Thank you so much for all your hard work! I look forward to the release, and donating to the project once available!
