### ISSUE TITLE
The app doesn't work on Windows 2004

### ISSUE THREAD

**Issue by matthew635** [AutoDarkMode/Windows-Auto-Night-Mode#147]
Hi, 
I'm using the app since few months and when I update my laptop to Windows 10 2004 the app start to doesn't work. I mean then when I turn on the automatic change, the button turn off just after.

I have another pc on Windows 2004 and same problem

I don't know exactly what it is because the 2.2 version work fine on 2004, and the 3.0 worked fine on 1909 ...*
I can still use the 2.2 so I don't understand why 3.0 and Windows 2004 don't match.

**Comment by emberaholdon** [comment]
Working fine for me (work and home pc).

**Comment by Spiritreader** [comment]
We have released Version X with many new improvements and features.
This should take care of any lingering issues that V3 still had with theme switching.

Please download and install. if you still experience this issue, feel free to reopen.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26
