### ISSUE TITLE
[Feature Request] Let the user change the color properties for the current wallpaper for dark mode

### ISSUE THREAD

**Issue by evertonstz** [AutoDarkMode/Windows-Auto-Night-Mode#148]
The current way a user can have a wallpaper change during dark mode is by selecting two different wallpapers for each there: one for white theme, one for dark theme.

Some users, like myself, just want to dim and desature the current wallapaper when the dark mode is activated, and have the original wallpaper come back when the dark mode is deactivated. One app that do something similar and have the necessary slide controls for "dim" and "saturation" is [Muzei for Android](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei&hl=pt_BR).

Here are some mockups:

Default wallpaper with white theme: [here](https://imgur.com/lnWsWwK)

Default wallpaper with dark theme, some desaturation and some brightness reduction:  [here](https://imgur.com/8D1uCdS)

Here's how the app Muzei presents these sliders: [here](https://zdnet2.cbsistatic.com/hub/i/r/2015/05/28/a55ce4d2-e8b9-41a4-8db9-5c37c6207221/resize/1200x900/a880cb8b623f5590f29c0f2c4ff49f1e/screen-shot-2015-05-28-at-14-37-24.png)

**Comment by Spiritreader** [comment]
Wallpaper modification will not make it into Auto Dark Mode as the feature creep would be too much.
My recommendation is to prepare these images beforehand with a free image editor.

Thank you for suggesting this tho, it's a super cool idea, but sadly doesn't quite fit the scope of the project anymore.
