### ISSUE TITLE
希望增加只修改应用的模式切换而不是系统主题切换功能

### ISSUE THREAD

**Issue by Top-Chen0** [AutoDarkMode/Windows-Auto-Night-Mode#155]
希望增加只修改应用的模式切换而不是系统主题切换功能

**Comment by pc-v2** [comment]
> rough translate for topic

`I hope to increase the mode switch that only modifies the application instead of the system theme switch function`

**Comment by Spiritreader** [comment]
if i understand this correctly, we already have this. Please reopen if still relevant.
