### ISSUE TITLE
Auto Dark Mode isn't automatic

### ISSUE THREAD

**Issue by Praetorian1981** [AutoDarkMode/Windows-Auto-Night-Mode#159]
Hello,

Ever since the update to version 3.0.0 the automatic portion of the programme has ceased to function. Everything works as intended but only if the programme is loaded manually.

Removing the new version, reinstalling the new version, reverting to an older version... nothing has worked & I'm all out of ideas. Even tackling the listings in the Task Scheduler hasn't helped at all. It simply will not do the switch automatically.

Please help!

Many thanks.

**Comment by vvitch3d** [comment]
Same here. I've tried unchecking the Use Logon Task instead of Autostart option like it says in Troubleshooting but to no avail.

**Comment by leifalbor** [comment]
+1 also occurring for me

**Comment by duttyend** [comment]
I also thought it was a bug in the beginning, but after waiting around 5 minutes after computer wake from sleep, it ends up changing theme automatically when required.
Did you try waiting a few minutes?

**Comment by Praetorian1981** [comment]
> I also thought it was a bug in the beginning, but after waiting around 5 minutes after computer wake from sleep, it ends up changing theme automatically when required.
> Did you try waiting a few minutes?

Waited after reboot, waited while using the PC, waited after reinstall, no change. The only time a mode change occurs is when I run the program myself.

**Comment by duttyend** [comment]
@Praetorian1981 Okay, well I don't know why it's not working for you, maybe you can give details about your config (in my case, it's working fine on Windows 10 Version 1909 (Build 18363.1316)

**Comment by Praetorian1981** [comment]
I'm also running Windows 10 Version 1909 (Build 18363.1316).
Have you disabled some Services or Tasks? - Yes, many. Mostly to do with Windows telemetry. Location services remain in place & ANM uses them just fine. Given that other scheduled task launch just fine, I don't think this is the problem.
Did you give internet access to the app? - Yes

**Comment by duttyend** [comment]
Okay, then I have no more ideas. You say that even reinstalling an older version doesn't solve the issue so it leads to thinking the problem is on your side. You should try a full backup of your OS and a Reset to see if it works again.

**Comment by Praetorian1981** [comment]
I came to the same conclusion. Resetting the OS is too much disturbance for me so I'll stick to running it manually for now.
Thanks for your time.

**Comment by duttyend** [comment]
One last thing you could check is if the following service is Running and on Automatic start : Connected Devices Platform User Service.

**Comment by duttyend** [comment]
I am now facing an issue with automatic switch. It happened today and I'll try to describe it the best I can : shortly after logging in, I changed the time zone to a country where it is night time, and the Dark Theme was set by the app (normal behavior).

The problem is that after changing again the time zone to a country where it is daytime, the app doesn't set the Light Theme.

@Armin2208 Maybe you could have the app check periodically (say every 5 mn) is the right Theme is set according to the system clock...?

**Comment by Armin2208** [comment]
sure

**Comment by Spiritreader** [comment]
We have released Version X. It comes with many fixes and improvements.
Please download, try again and check if you still experience this. If so, feel free to reopen the issue!

https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26
