### ISSUE TITLE
Dropdowns and checkboxes in Settings - Apps don't respond when clicking

### ISSUE THREAD

**Issue by foami** [AutoDarkMode/Windows-Auto-Night-Mode#163]
Ver 3.0.1
 Suddenly I cannot select the mode of color changing in this menu
![image](https://user-images.githubusercontent.com/39795953/93019214-335b1580-f608-11ea-8a58-1f142ca63760.png)

And
What does this mean: **Alternative light theme** under the Office theme?

**Comment by Armin2208** [comment]
Not a single dropdown is working? Does the app still change the theme?

**Comment by vaporwav** [comment]
Seems it still changes the theme, just cannot select the dropdown or check the box.

**Comment by Spiritreader** [comment]
Please update to Auto Dark Mode Version X and let us know if this fixes your issue and let us know.
If it does, please close this issue.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26

**Comment by foami** [comment]
Already updated. This issue should be fixed now
