### ISSUE TITLE
Feature Suggestion - Manually choose location

### ISSUE THREAD

**Issue by JimmyRespawn** [AutoDarkMode/Windows-Auto-Night-Mode#165]
Please add an option to manually choose the location which adjusts theme by sunset and sunrise.

**Comment by Armin2208** [comment]
your profile picture really convinces me to implement this. But it's kinda useless, because you could also set a default location in windows settings.

**Comment by schaafjs** [comment]
> But it's kinda useless, because you could also set a default location in windows settings.

This is not entirely true because in order for this to work and Windows Auto Dark Mode maintaining access to the location, location services have to remain active at all times. This would not be the case if the location is chosen directly in Windows Auto Dark Mode if I understand correctly.

**Comment by JimmyRespawn** [comment]
> > But it's kinda useless, because you could also set a default location in windows settings.
> 
> This is not entirely true because in order for this to work and Windows Auto Dark Mode maintaining access to the user's location, location services have to remain active at all times. This would not be the case if the location is chosen directly in Windows Auto Dark Mode if I understand correctly.

Yes, exactly. If I do not enable location service on my device, the WANM will open the setting's app to re-enable location anyway. Or this feature won't be active. There is a way to change the default location in settings menu, but I have to enable the LOCATION.

**Comment by mikesafari** [comment]
Would like this as well but for a different reason: my business machine has location services disabled completely, so I cannot truly automate this based on time of day.

An implementation like that of f.lux would be great.

**Comment by edel79** [comment]
I agree with @mikesafari : my business machine has also location settings locked so I can't allow Auto Night Mode to use it.
The idea would be to do as the Dark Reader browser extension : allow the user to enter the coordinates of the location.

**Comment by jvacek** [comment]
Yup, same. This is brought up whenever I try to choose "by location", but there is no way for me to turn the location services on.

![image](https://user-images.githubusercontent.com/1302278/108371438-07b70980-71fe-11eb-9cc3-124c156a6970.png)

**Comment by mikesafari** [comment]
This is (thankfully) no longer a requirement for me since f.lux now supports automatic dark mode at sunset/sunrise.
