### ISSUE TITLE
Remove transparency effects, can cause issues with certain graphics devices / Win 11

### ISSUE THREAD

**Issue by tiziodcaio** [AutoDarkMode/Windows-Auto-Night-Mode#169]
It is too much complicated remove trasparents effects due to too many performance used **only** in old pcs????
It's a suggestion...

**Comment by emberaholdon** [comment]
If your computer is too old to handle the transparency effects, you shouldn’t even run Windows 10 on it.

**Comment by tiziodcaio** [comment]
🤣🤣🤣

**Comment by tiziodcaio** [comment]
i agree, but it's trashing performance

**Comment by TheMayhem6328** [comment]
Not a deal breaker, but I think that Settings > Colors > Transparency Effect toggle should change that (but it doesn't)

**Comment by Armin2208** [comment]
> Not a deal breaker, but I think that Settings > Colors > Transparency Effect toggle should change that (but it doesn't)

great idea!

**Comment by Armin2208** [comment]
lol

**Comment by tiziodcaio** [comment]
Oh sorry

**Comment by tiziodcaio** [comment]
I thought my idea was trashed 🥺

**Comment by Tom4tot** [comment]
Just to confirm I'm having big issues on W11. Huge delay while moving the window, and everytime I open the program for the first time, I need to alt tab twice to show content, otherwise it's just a transparent window that shows elements only when I hover them with my mouse.
I have a 3700x and a RTX 2070 so I don't think it only affects old PCs. :D 

Please let me know if you need logs, screenshots, videos, etc.

**Comment by Spiritreader** [comment]
Transparency effects are disabled for the forseeable future for the MainWindows only in Windoes 11 until FluentWPF introduces an option to globally disable transparency, or it gets fixed.

**Comment by Spiritreader** [comment]
I have addressed this in the latest beta with a workaround, by spawning the main window without fluentwpf if the host operating system is Win11.

The message boxes are still fluentwpf for now, so it's not a full fix, but it should restore operability for most users until the framework updates.

**Comment by Spiritreader** [comment]
The behavior of ADM has been revamped and it should now no longer exhibit the laggy behavior originally observed in this issue.
We also use Mica on Windows versions that support it.
