### ISSUE TITLE
Incompatible with WinDynamicDesktop

### ISSUE THREAD

**Issue by shadeMe** [AutoDarkMode/Windows-Auto-Night-Mode#171]
The [WinDynamicDesktop](https://github.com/t1m0thyj/WinDynamicDesktop) app can be used to simulate day/night cycles using Windows wallpapers. Currently, AutoNightMode's automatic theme switching prevents the former from working correctly.

What happens: It automatically resets the wallpaper to the active (day/night) theme's base wallpaper every few minutes.

What should happen: It lets WinDynamicDesktop override the wallpaper setting.

Version: 3.0.19.0 (Dev build supplied by Spiritreader).

**Comment by Armin2208** [comment]
do you use theme file theme switching?

**Comment by shadeMe** [comment]
Yes.

**Comment by Armin2208** [comment]
yes

**Comment by shadeMe** [comment]
Is this something that will be looked into by you guys? Just something as simple as a toggle in the config to prevent the polling behaviour would do.

**Comment by emberaholdon** [comment]
I use them together and have no issues whatsoever. I don’t use Auto Night Mode to switch wallpapers or themes, I might add.

**Comment by shadeMe** [comment]
> 
> I use them together and have no issues whatsoever. I don’t use Auto Night Mode to switch wallpapers or themes, I might add.
As I mention in my original post, this is an issue specific to the automatic theme switching functionality.

**Comment by Spiritreader** [comment]
If you switch to the Auto Dark Mode Beta channel (you can find this under settings) and download the update, you will now find a checkbox that disables automatic theme overrides when they have been changed by an external program.

Please note that theme states will no longer be tracked at all, even when updating the auto dark mode config,
This behavior is subject to change though.

![image](https://user-images.githubusercontent.com/18438899/136118744-153dc080-6705-4ab9-ab1d-795a0fffaf3b.png)
