### ISSUE TITLE
Windows 10 LTSC "Start, Taskbar and action center" color following problem

### ISSUE THREAD

**Issue by cmhrky** [AutoDarkMode/Windows-Auto-Night-Mode#172]
Windows 10 Enterprise LTSC 1809 OS build 17763.1518
Auto Dark Mode v3.0.1

I choose this option in Windows Settings, but when the computer is rebooted or sign out and sign in it is disabled.

![image](https://user-images.githubusercontent.com/17867666/95983315-180f4000-0e2a-11eb-8147-bd5adf18153a.png)

![image](https://user-images.githubusercontent.com/17867666/95982821-4b050400-0e29-11eb-9736-39f37d53e21b.png)

**Comment by cmhrky** [comment]
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"ColorPrevalence"=dword:00000001
```
This way I am fixing the problem by applying it manually.

**Comment by Armin2208** [comment]
Interesting bug, thnk you!

**Comment by cmhrky** [comment]
The problem still continues. (Auto Dark Mode v10.0.0.26)

**Comment by cmhrky** [comment]
It seems like the problem is solved. I tried with Force Ligtht/Dark Mode from the tray icon and restarting the computer.

**Comment by Spiritreader** [comment]
Awesome, if it reappears, feel free to reopen this issue!
