### ISSUE TITLE
Keeping preferences when updating Auto Dark Mode

### ISSUE THREAD

**Issue by udobehm** [AutoDarkMode/Windows-Auto-Night-Mode#173]
Please when installing a newer version of Auto Dark Mode keep the original settings and wallpapers. It's very annoying if you have to re-apply all settings and wallpapers after an update has taken place. Hope you may implement this...

**Comment by Spiritreader** [comment]
ADM is currently undergoing a major rewrite under the hood.
I am afraid a configuration file reset will be mandatory for the next major release.
Sorry :(
