### ISSUE TITLE
Grayscale filter enables itself when launching app

### ISSUE THREAD

**Issue by Grekkq** [AutoDarkMode/Windows-Auto-Night-Mode#178]
Steps to reproduce:
- Check "Use grayscale colour filter" checkbox 
- Close app
- Disable filter using shortcut (can be also disabled while app is launched, it doesn't unmarks checkbox)
- Launch app

Also when checkbox is checked filter is enabled when theme switches automatically from light to dark.

**Comment by Armin2208** [comment]
This is because the app makes a theme switch at app start. Let's see what I can  do against that.

**Comment by Spiritreader** [comment]
this should be fixed in the latest beta.
The update mechanism for the color filter changed to accomodate for this
