### ISSUE TITLE
Offset digits limit

### ISSUE THREAD

**Issue by mburkasov** [AutoDarkMode/Windows-Auto-Night-Mode#180]
When customizing offset for location-based switching cannot input more than two digits, with a maximum of roughly 1.5 hours.

**Comment by Armin2208** [comment]
Can you explain me your usecase why you need more?

**Comment by mburkasov** [comment]
Basicallyt I can't input a number more than 99
![image](https://user-images.githubusercontent.com/20526265/99156166-d6dfa980-26cf-11eb-94cc-2a27dc4c9c76.png)

**Comment by mburkasov** [comment]
> Can you explain me your usecase why you need more?

Well, I wanted an offset the sunset by 3 hours, because the sun sets really early, and I can't do that.

**Comment by CXwudi** [comment]
Same here, I want the dark mode come 4 hours earlier but with this digit limit I can't it

**Comment by jwfxpr** [comment]
Having had a look at this area of the code recently for a related change, and checking again now, I can't see a particular technical reason why the input fields for the offsets must be limited to 2 characters. That said, of course, increasing the fields from 2 to 3 characters would increase the range for the offsets from 1.65 hours each way to 16.65 hours each way, which would allow a silly user to set completely impractical offset values, which I think is the reasoning behind the 2 character limit. 

I think perhaps there could be a middle ground, with an upper limit of, say, 6 or 8 hours on the offset? (For users at extreme latitudes, 6 or 8 hour offsets don't seem that unreasonable to me.)

@Armin2208 Any objection to a change which increases the field length to 3 characters, and adds a validation step on focus loss that would coerce the value to a maximum limit? I can make those changes in the next few days, probably, and open a PR for more specific discussion about implementation or UI changes required for it.

**Comment by Armin2208** [comment]
after we geared so much feedback about this, we want to enable this in future. just didn't had time to implement this. I don't know if there is any conflict with the check numbers for validation code.
feel free to add this change, if you want to.

**Comment by jwfxpr** [comment]
I have an idea of how this could be sensibly done without adding any new regionalised strings. I'll have some time in the next week to play with it a bit 👍

**Comment by jwfxpr** [comment]
Additional discussion of this feature and its implementation can be found in the #243 PR conversation thread.

**Comment by Spiritreader** [comment]
Feature implemented, for more details see f5bffd0 or #243
