### ISSUE TITLE
[Feature Request] Change Lock Screen and Wallpaper

### ISSUE THREAD

**Issue by perrinpagess** [AutoDarkMode/Windows-Auto-Night-Mode#184]
Basically what the title says. The ability to automatically change the wallpaper at the time change is a feature that I love, but to also change the lock screen would be awesome. 

Thanks

**Comment by Spiritreader** [comment]
At this point in time, we have no plans to implement this feature.
However, we are open to accepting pull requests.

[We also provide documentation on how to contribute to make this process easier.](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Adding-a-new-component)
