### ISSUE TITLE
[Feature Request] Add option for custom post scripts

### ISSUE THREAD

**Issue by UiharuKazari2008** [AutoDarkMode/Windows-Auto-Night-Mode#185]
Can you add the ability to have custom scripts run after light or dark mode. I want to run a script to set me iCUE lighting to a specified mode for day and night.

I used to just edit the schedule task but apparently the way you have it implemented it recreates the task instead of just updating it and my actions are lost.

**Comment by emberaholdon** [comment]
> I used to just edit the schedule task but apparently the way you have it implemented it recreates the task instead of just updating it and my actions are lost.

Changing this behavior could open up a lot of possibilities, eg. using custom scripts which set other programs themes via registry. I know the expandable application list is coming in future versions but until then it would be great if the program did not recreate, only modifyed the existing scheduled tasks.

**Comment by Armin2208** [comment]
how and in which environment would you write a script for iCUE?

**Comment by UiharuKazari2008** [comment]
Just have a dummy exes run that are linked to a i cue profile

**Comment by Spiritreader** [comment]
merge issue with #186
