### ISSUE TITLE
[Feature request] Add support to run script upon theme change

### ISSUE THREAD

**Issue by TheMayhem6328** [AutoDarkMode/Windows-Auto-Night-Mode#186]
Hello! So I've been using this beautiful piece of software for quite some time (thanks a lot for coming up with this), and I am loving it. The recent addition of full theme change instead of just wallpaper was awesome! Sadly, I still have to modify some apps' themes manually. For example, for Spotify, I use spicetify to theme it - since spicetify is a cli utility, I have to run some commands to change my theme. I made a batch script to quickly change the config file and apply changes - it would be convenient if I could do it via this app; apps like WinDynamicDesktop can do it, so why not this?

![image](https://user-images.githubusercontent.com/56154436/101565717-d77e0e00-39f7-11eb-90ae-399f63c4e798.png)

Something like this would help a lot! Thanks for taking your time to read this!

**Comment by Armin2208** [comment]
will try to implement this.
Can WinDynamicDesktop only run PowerShell Scripts or also Batch Scripts? Or can you run Batch Scripts with PowerShell (Scripts)?

**Comment by TheMayhem6328** [comment]
WinDynamicDesktop can only run powershell scripts, but one can call batch scripts with powershell scripts through line like ".\Test.bat"

**Comment by Armin2208** [comment]
Thanks!

**Comment by Spiritreader** [comment]
There were some issues with the script file not updating correctly when the args lists were not populated.
Also an issue was corrected where changing the working directory would not trigger a script re-run.

Build 10.0.2.17 should have addressed all of these issues.

**Comment by WindowsTablet** [comment]
Would it be possible to add an argument that indicates whether the light/dark mode was forced?

Thanks in advance.

**Comment by Spiritreader** [comment]
> Would it be possible to add an argument that indicates whether the light/dark mode was manually forced?
> 
> Thanks in advance.

The scripting engine is implemented using the standardized adm component. These components are unaware of the external switch state. If such a feature is provided, the components should be able to handle switch events as a whole, which requires modification to the component interface and switching logic, which is quite a lot of work. 

In addition, it would need to be defined if adm passes parameters (and if, how) or whether script entries have a configuration option that allows to speficy event triggers. 

Moreso, the automatic vs manual switching indicator in the log file is not really production ready for such purposes and is just meant as a quick debugging tool to spot rudimentary switching sources.

Unless there is **a lot** of demand from many users for this feature, I would tend to say no, it's not possible for now.

**Comment by WindowsTablet** [comment]
The reason I'm asking for this is that I want to kill the touch keyboard process when I manually force a mode, but I don't want that to happen during a automated scheduled switch.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/347

**Comment by Spiritreader** [comment]
The idea to propagate events within ADM has been discussed before, but I don't believe that your specific problem (which stems from a Windows bug in the first place) warrants a complete rewrite of the ThemeManager.

Without providing any ETAs, this revamp will likely happen eventually.

**Comment by WindowsTablet** [comment]
Understood.

**Comment by Spiritreader** [comment]
@WindowsTablet I've invested the time and rewrote the thing anyway, because it probably needed to be done at some point anyway.
You can find infos on how to specify the source in the wiki.
The feature is availalbe starting with Beta 10.0.2.21

**Comment by Spiritreader** [comment]
Marking this as complete as the scripting engine is working, albeit with no UI.
Will open a separate issue for that for logical separation
