### ISSUE TITLE
Dark Window Mode but Light App Mode

### ISSUE THREAD

**Issue by ghpics** [AutoDarkMode/Windows-Auto-Night-Mode#203]
I hope I'm not being stupid but from what I've tried there doesn't seem to be a way under Windows Theme mode in Auto Dark Mode to set my Windows mode to dark but the app mode to light and then set that as my light theme on Auto Dark Mode. Then having my dark theme as both dark.

**Comment by Armin2208** [comment]
Should work without problems

**Comment by ghpics** [comment]
I've found it crashes when trying to save that configuration. 
![Screenshot 2021-01-17 112904](https://user-images.githubusercontent.com/77551653/104839146-3ec09500-58b7-11eb-8a6d-a82baf3207b3.png)

**Comment by Spiritreader** [comment]
It doesn't look like you picked a theme.
Light Theme and Dark Theme are empty.

However, it shouldn't crash if none is selected.
In fact, it shouldn't even be possible to save two "empty" themes.

We've revamped this in the upcoming version, so it should work as soon as it gets pushed.

**Comment by Spiritreader** [comment]
Please try again with Auto Dark Mode Version X and let us know if you still have issues:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26
