### ISSUE TITLE
No jump lists

### ISSUE THREAD

**Issue by 303951546** [AutoDarkMode/Windows-Auto-Night-Mode#205]
I don't see the jump lists for manually switching between light and dark.

I recall seeing them once back in v2.0(?), but not anymore in the subsequent versions.

I have multiple windows devices and all have the same issue.

**Comment by Armin2208** [comment]
did you let the updater uninstall the previous version before installing the new one? 🤔

**Comment by 303951546** [comment]
I did (and some were fresh installs on new devices).

By the way great app Armin. Been using this for a long time and this is the only hiccup.

**Comment by Armin2208** [comment]
even on fresh installs no jump list?

**Comment by Spiritreader** [comment]
Please download and install the new version X and check if it is working now.

https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26
