### ISSUE TITLE
[Feature request] Add  changing the "show color on start menu, taskbar, and notification center" setting when changing theme

### ISSUE THREAD

**Issue by NIK2703** [AutoDarkMode/Windows-Auto-Night-Mode#206]
I want to achieve this effect when changing themes:
![light](https://user-images.githubusercontent.com/44705381/106576529-4dad7580-654e-11eb-99b3-aae443e5cfc9.PNG)
![dark](https://user-images.githubusercontent.com/44705381/106576520-4a19ee80-654e-11eb-8b56-5d4bfe618d5b.PNG)

**Comment by Armin2208** [comment]
we have this under Apps and use Accent Color but it doesn't seem to work with LTSB/LTSC right now

**Comment by Spiritreader** [comment]
This feature is now available.

![image](https://user-images.githubusercontent.com/18438899/139785131-1a58df8f-b686-4eb8-9e47-d709440f252e.png)

**Comment by pc-v2** [comment]
How do I make Always Dark without accent color?

**Comment by Spiritreader** [comment]
> How do I make Always Dark without accent color?

If you do not want Auto Dark Mode to modify the setting, You disable the feature entirely and set it once in Windows.
