### ISSUE TITLE
[Feature suggestion] Allow any offset number

### ISSUE THREAD

**Issue by avi12** [AutoDarkMode/Windows-Auto-Night-Mode#207]
I suggested in #139 to take into account weather data
Today turned out to be a [rainy day](https://weather.com/weather/tenday/l/73ac32c92ac8a001c2456904df0ddd2a26e304ad9832ace7811984fea5d62991) all of a sudden, and it turns out that I need a large 3-digit offset, whereas the application will only accept a 2-digit offset

**Comment by Spiritreader** [comment]
already tracked in #180
