### ISSUE TITLE
Muti-user and std-install-path

### ISSUE THREAD

**Issue by RenZi-at** [AutoDarkMode/Windows-Auto-Night-Mode#209]
hi
could you pls make it installable for "all users" of the PC?
and make the predfined install path to "Program Files"?

k.r.

**Comment by Armin2208** [comment]
planned :)

**Comment by mateuszdrab** [comment]
I think what's needed is a multi-user install and a way to pre-deploy the configuration - such as by using a Group Policy template.
The app would have to be registered to auto start with the system to configure itself for the user under the hood.

**Comment by Spiritreader** [comment]
Auto Dark Mode Version X supports multi user mode out of the box, and also features an all-users based installation.
However we do not recommend installing in all-users mode, as this is mutually exclusive with our update system.

You can find the release here:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26
