### ISSUE TITLE
ARM version?

### ISSUE THREAD

**Issue by rohitsant** [AutoDarkMode/Windows-Auto-Night-Mode#212]
Hello! Any chance you could compile this for ARM, or provide instructions on how to build from source? I tried to install using `winget` on my Surface Pro X and it errors out saying "No installers are applicable to the current system."

**Comment by Armin2208** [comment]
App is provided as X86, so it should emulate on ARM. Or?
I can't compile C# Apps for ARM sadly :/ This is a Microsoft restriction

**Comment by Bartastic** [comment]
Should be possible now with .NET core - they've made ARM SDKs available and there are some cross-compile options

**Comment by Spiritreader** [comment]
Some components that we use and are mandatory for ADM (ManagementEventWatchers) throw an incompatibility error when the compilation target isn't x86.

So we can't offer ARM support unless .NET starts adding support for the missing archs.

**Comment by Spiritreader** [comment]
see https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/690
