### ISSUE TITLE
Auto-switching to dark theme opens Cortana

### ISSUE THREAD

**Issue by watermarkhu** [AutoDarkMode/Windows-Auto-Night-Mode#217]
Whenever the theme automatically switches to dark theme with WANM, the Cortana window is automatically opened. This occurs to me currently on Windows Insider Build 21337 and the latest WANM 3.0.1. 

![cortana](https://i.imgur.com/IKGaTIF.png)

**Comment by Spiritreader** [comment]
stale as ADM has received multiple updates in the meantime.
Feel free to reopen if still an issue
