### ISSUE TITLE
Feature Request: Allow us to also change the accent colour for light / dark modes

### ISSUE THREAD

**Issue by fredddd1** [AutoDarkMode/Windows-Auto-Night-Mode#218]
It would be great if the accent colours could be decided for both modes. The one I use on light mode does not accent that well on dark mode and I would like something softer to the eyes.

**Comment by Armin2208** [comment]
You can make this possible with windows theme switching, althought this takes a little bit more time to set up :)

**Comment by Spiritreader** [comment]
Thanks for your suggestion!
Issue tracked in #246 now, as there is concrete information on how to do this.
