### ISSUE TITLE
Feature Request: "Title bars and window borders" toggle like we have one for taskbar too

### ISSUE THREAD

**Issue by ghost** [AutoDarkMode/Windows-Auto-Night-Mode#219]
Would be great if we could also have a "Title bars and window borders" toggle like we do have one right now for the taskbar.

**Comment by Armin2208** [comment]
great idea!

**Comment by ARTiL1S** [comment]
Yes please! I was about to suggest this and found this thread. Please make this an option to choose to activate accent color based on the theme activated on Day/Night schedule... eg: use accent color (window borders and title bar) for selected day theme only but not for the night theme.
:)

**Comment by Spiritreader** [comment]
What are the registry keys required to enabled/disable this?

**Comment by Spiritreader** [comment]
More info about this in #246

**Comment by Spiritreader** [comment]
The required key is
```
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM\ColorPrevalence DWORD
```
