### ISSUE TITLE
Suggestion: add a way to get sunset time by latitude and longitude，rather than relying solely on locating.

### ISSUE THREAD

**Issue by stanlywill** [AutoDarkMode/Windows-Auto-Night-Mode#222]
Add a way to get sunset time by latitude and longitude，rather than relying solely on locating.
Better batteries, and makes it easier for desktops to use.

**Comment by maqorbani** [comment]
I would say I highly support @stanlywill 's idea. As the app's method of finding my location is causing issues since I mostly use VPNs on my machine, and it falsely identifies my VPN's location as my current location.
Setting the city based on the windows' time zone also does not seem a bad idea.

**Comment by Armin2208** [comment]
oh didn't know this vpn situation. thanks for your feedback!

**Comment by maqorbani** [comment]
Thank YOU for devising such a useful application!

**Comment by patrikbadanjak** [comment]
What about entering your city's name and getting the lat and long data with google's API (https://developers.google.com/maps/documentation/geocoding/overview) and passing that data to another API that retrieves sunrise and sunset (https://api.met.no/weatherapi/sunrise/2.0/documentation)?

**Comment by Spiritreader** [comment]
Please confer #145 for an update on this.
