### ISSUE TITLE
Crash after start (not responding)

### ISSUE THREAD

**Issue by simonferndriger** [AutoDarkMode/Windows-Auto-Night-Mode#223]
This happens only since today, even after I reinstalled the newest version

**Comment by koshyviv** [comment]
Same issue here, did a fresh install of v3.0.1 - crashes on app open

**Comment by Armin2208** [comment]
I think it has something to do with Ms edge being removed. Although Auto Dark Mode is. optimized to even launch without edge installed.

could you post the crash report of the event log?

**Comment by simonferndriger** [comment]
Thanks for asking - however, the problem solved itself in the meantime.

Best
Simon

Am Do., 29. Apr. 2021 um 19:12 Uhr schrieb Armin Osaj <
***@***.***>:

**Comment by koshyviv** [comment]
So it is working for me too. I installed v2.3.0 and then upgraded to v3.0.1 which somehow made it work.
