### ISSUE TITLE
Portable version of the tool

### ISSUE THREAD

**Issue by tooomm** [AutoDarkMode/Windows-Auto-Night-Mode#224]
Please consider releasing a version that does not require a setup file and works without installation.

These simple yet powerful tools are even better when they can simply be executed by opening the file. They are so much more flexible when you can use them on PC's without admin rights, carry them around on a thumb drive or access them centrally on a cloud storage and many other use cases...
Installation should not be a fixed requirement in order to use it.

**Comment by Armin2208** [comment]
Auto Dark Mode Installation doesn't require Admin rights anyways. And don't forget you need Auto Dark Mode to be installed on the PC in order to get a theme switch. Just setting up Auto Dark Mode from a USB Stick will not work, after you eject the USB.

**Comment by tooomm** [comment]
Is that a windows limitation requiring the installation? Or the way your tool implements the tasks?

I'm only interested in the basic feature of enabling/disabling dark mode at certain times, without the burden to install yet another tool. My setup shares a common local storage for several systems for example. Even my browser, mail app etc. run from there and always have the same up-to-date version, bookmarks, addons and setting for example. I have to maintain it only once. Also reinstalling a system is a breeze with the basics running in seconds with no setup.

**Comment by Armin2208** [comment]
Auto Dark Mode works like this:
It creates a scheduled task in task scheduler. This task starts AutoDarkMode.exe either with the argument /dark or /light. The app runs the needed code to change everything. Sometimes it also runs an updater task (for suntimes updates).

It's not possible to implement this auto switch feature to this extend without having a .exe resting on your pc which will be callled by task scheduler. Your only alternative is to create your own .bat-script which the task scheduler runs. But you need to live with all the negative aspects which this solution brings.

ADM3 is already a really simple solution with nearly no footprint. 

Going further: with ADMX we change our behaviour to a real background task which always runs. WIth this update Auto Dark Mode will have more impact on your system, but it will also provide many new features (like switching to dark on (low) battery, switching theme with keyboard shortcut, going to light mode in bright environments (using bright sensor) etc.

**Comment by tooomm** [comment]
Thanks for the explanation and details @Armin2208 👍 

>It's not possible to implement this auto switch feature to this extend without having a .exe resting on your pc which will be callled by task scheduler.

Imagine a simple multi boot setup with a shared HDD for common access for example. The exe file would be accessible from every system without duplicating it and reconfiguring it for every OS instance.

But I better understand now, that this kind of tool is probably not well suited for portable usage or specific environment due to limitations in how it works and interacts with the system. Too bad windows requires external tools to offer such basic features in the first place. :)


>(ADMX will provide many new features) like switching to dark on (low) battery

Why would one like to do that? I see no connection between power source or battery status and light/dark mode. 🤔  

But yeah, the bright environment use case sounds pretty interesting.

**Comment by Armin2208** [comment]
If you rest Auto Dark Mode on a Network Drive, so every pc has always access to the adm.exe, it should go well. You only need to have the app files accessible, they don't need to be installed for every user.
