### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by corgile** [AutoDarkMode/Windows-Auto-Night-Mode#225]
# the text doesn't display perfectly

![image](https://user-images.githubusercontent.com/48396880/117564835-9b52f480-b0e0-11eb-9ecd-2ea177f323aa.png)

**Comment by Armin2208** [comment]
this is a weird font, but I will take a look

**Comment by corgile** [comment]
> this is a weird font, but I will take a look

## Yes, I changed it to "PingFang SC" with [this](https://github.com/Tatsu-syo/noMeiryoUI) tool, and also its size(slightly)，
### It's not a big problem for me, but it would be better if you could please fix this little problem
### 😏

**Comment by Spiritreader** [comment]
Auto Dark Mode Version X has a newly desinged user interface.
Any limitations with theoretically unsupported fonts are sadly unsupported, as we would need to change the UI framework.

However we made the font larger and work properly with windows scaling, so you may not have the visibility issues anymore.

https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26

**Comment by Armin2208** [comment]
should be better now, because we don't use fixed heights anymore
