### ISSUE TITLE
All of the options in 'Apps' are disabled when automatic theme switching is off

### ISSUE THREAD

**Issue by Susko3** [AutoDarkMode/Windows-Auto-Night-Mode#231]
I switch themes exclusively trough the jumplist, so I have automatic theme switching off.

For some reason, when theme switching is off, I cannot change any of the options under 'Apps'. It's as if the options are disabled. I don't understand why the options are disabled, as they still apply when switching the theme from the jumplist.

This makes it cumbersome to change those options, as I have to enable automatic theme switching, change the options, and then disable automatic theme switching.

**Comment by Spiritreader** [comment]
The reason for this is people configuring AutoDarkMode without having the automatic theme switch enabled.
It acts as a failsafe so people don't think the app is "not working" when they have configured everything.

But what you say is a fair point!
I'll see what I can do about that.
