### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by ncodee** [AutoDarkMode/Windows-Auto-Night-Mode#234]
Probably an early ask, but would be great if you could add support for Windows 11. I've noticed that jumplists are not showing for manually switch themes, and the icon is showing completly blank on the taskbar.

Thanks

**Comment by Armin2208** [comment]
thnks for reporting, will 100% do

**Comment by QuestYouCraft** [comment]
@Armin2208, will you have time to implement this feature before October 5 (the release of the final version of Windows 11)? If not, can you tell us at least an approximate date?

**Comment by Armin2208** [comment]
the next major release of auto dark mode will be released on the 5th October alongside with windows 11.
Currently we are working every day on this project.

**Comment by Spiritreader** [comment]
> the next major release of auto dark mode will be released on the 5th October alongside with windows 11. Currently we are working ~~every day~~24/7 on this project.

**Comment by QuestYouCraft** [comment]
Cool! I, as well as many other users, are looking forward to the new version and your results of painstaking work. Good luck!

**Comment by Spiritreader** [comment]
ADM Version X is compatible with Win11

Please note that due to API limitations, switching wallpapers on each virtual desktop is not supported yet.
