### ISSUE TITLE
Windows File Explorer Sometimes Doesn't Change Theme After Reboot

### ISSUE THREAD

**Issue by KyleNie** [AutoDarkMode/Windows-Auto-Night-Mode#235]
I always turn my computer off before bed (File Explorer in dark mode set by Auto Dark Mode), but sometimes when I wake up next day and boot up my PC the interface change to light but File Explorer sometimes wouldn't change to light. 

It happens on my new MSI GS66 11UH, didn't notice this issue on my other 2 computers. Please contact me if you need more information for debugging.  

Edit: Also happens on my One-Netbook 4.

**Comment by izedamo** [comment]
happens with me as well.

**Comment by Spiritreader** [comment]
Yes, this sometimes happens when switching themes in Windows in general.
It can happen when using the windows control panel to apply a new theme as well.
It should go away after navigating to a different folder in the explorer.
