### ISSUE TITLE
Feature Request: Toggle the Windows Bluelight Filter

### ISSUE THREAD

**Issue by crashmit** [AutoDarkMode/Windows-Auto-Night-Mode#239]
I use Auto Dark Mode with a time offset. It would be great if I could also enable the blue light filter together, as the windows control for that doesn't offer offsets. It's just a convenience thing, that I'd appreaciate a lot! Especially as the windows day/night change doesn't work 100% reliably.

**Comment by Armin2208** [comment]
We will NOT implement this.
