### ISSUE TITLE
Suggestion/Request: Change AccentColor on theme switching

### ISSUE THREAD

**Issue by BjornTjockPals** [AutoDarkMode/Windows-Auto-Night-Mode#246]
Hi! It would be a great addition to add posibility to change AccentColor (as it is named in registry) on theme switching.

It can be done by anchoring simple powershell script like this:

`reg add "HKCU\SOFTWARE\Microsoft\Windows\DWM" /v AccentColor /t REG_DWORD /d 0xd0d0d0d /f`
_- In dark mode accent color would change to chosen - #d0d0d0d_

`reg add "HKCU\SOFTWARE\Microsoft\Windows\DWM" /v AccentColor /t REG_DWORD /d 0xcececece /f`
_- In white mode accent color would change to chosen - #ececece_

With this we could get rid of default white title bars in dark mode, and customise their color in both dark and white mode, independently from windows Color setting.

_I hope I have made it clear what I mean, english is not my native language, so sorry for any ambiguities_

**Comment by Armin2208** [comment]
Thanks for the registry keys!

**Comment by BjornTjockPals** [comment]
No problem! That's what I was able to reach on my own, however running script everytime manually is a little bit annoying so 
I'll be glad if you manage to add this feature!

**Comment by BjornTjockPals** [comment]
Oh, I forgot to mention. There's also another registry key (in the same location) that corresponds to the **title bar** colour of apps which are **inactive**:  `AccentColorInactive`

It may not be created by default, so It may be needed to create it at first; it's also **REG_DWORD** type key.

**Comment by Spiritreader** [comment]
Unfortunately, changing accent color fully without having access to the theme api component that is responsible introduces strange issues where not all components are correctly updated.

We sadly have to indefinitely postpone this for now. However, the toggle of AccentcolorInactive will make its way into the next version.

**Comment by Spiritreader** [comment]
Accent color can now only be changed by applying a theme file with a different colorization color. This is unlikely to change.
You can realize this today with ADM (and in fact, it always worked in unmanaged theme mode) by just using Windows theme mode and setting up a colorization color with the windows ui. 
It has way better previews as well.

However, in the future, we may include a way to set the color for our managed theme.

**Comment by Spiritreader** [comment]
> However, in the future,

The future is now.
This functionality has been added to the latest beta.
