### ISSUE TITLE
Some icons are Light and some are Dark themed on the taskbar

### ISSUE THREAD

**Issue by juninholiveira** [AutoDarkMode/Windows-Auto-Night-Mode#250]
After installing and configuring the app, I noticed some strange behaviour on the taskbar. As you can see on the screenshot, some itens are from the Light Theme and other from the Dark theme, all mixed. Is this some bug or some predicted behaviour that I don't know how to control?

![Screenshot_taskbar](https://user-images.githubusercontent.com/10757100/131229839-167955fe-4443-4dcf-b158-3cdb1c749d56.jpg)

**Comment by Spiritreader** [comment]
This is an issue with the way theme switching works with windows.
The latest version that is currently under development features a customizable offset that will mitigate this issue.
From our testing and experience, that will fix the issue most of the time.
