### ISSUE TITLE
Is this app not fully compatible with Windows 11?

### ISSUE THREAD

**Issue by alok-debnath** [AutoDarkMode/Windows-Auto-Night-Mode#253]
The latest version and the version provided by the dev "https://www.mediafire.com/file/9xu8wfb3zu2h8v5/AutoDarkModeX_Setup_20212307_1741.exe/file" doesn't seem to work in Windows 11. It doesn't even completely load up in my Laptop. I remember it working perfectly in Windows 10

**Comment by Armin2208** [comment]
Windows 11 doesn't provide any changes that would affect Auto Dark Modes behaviour.
So your App doesn't load? That's strange!

**Comment by emberaholdon** [comment]
It’s not Windows 11. Working fine for me.
