### ISSUE TITLE
Use existing Windows 11 themes in "Windows Theme" mode?

### ISSUE THREAD

**Issue by mtrewartha** [AutoDarkMode/Windows-Auto-Night-Mode#258]
I suppose this is a question and maybe a feature request... I can't seem to figure out how to use any existing, built-in Windows 11 themes in the "Pick your themes" drop downs when using the "Windows Theme (more features)" mode. Is there a way to do this without essentially duplicating each theme and saving them as custom themes?

P.S. Thanks for the great free app! I especially love that I can add +/- offsets from the sunrise/sunset timing. So nice!

**Comment by Spiritreader** [comment]
Hey there!

Currently, the Themes are taken from `%LocalAppData%\Microsoft\Windows\Themes`, not including sub-directories.
Adding more theme files to the drop-down list pretty much comes down to having to know where the theme files reside.

Do you know where the built-in and downloadable Microsoft-provided theme files are stored? 
If so, adding them is pretty simple to accomplish!

We're working hard on the next version, thank you for using Auto Dark Mode!

**Comment by mtrewartha** [comment]
A quick Google search turned up `Windows\Resources\Themes` and that looks to be right. I see a few `.theme` files in there and if I double click them, themes are applied. They also match up to the 6 default themes that are available in Windows' Themes settings. For now, I've just copied the ones I want to be able to choose in Auto Dark Mode over to the directory you mentioned. That's a solid workaround. If you folks get a chance, I think it'd be nice feature to expose those to users by default.

Anywho, thanks again for the great free app and I appreciate the quick response!
