### ISSUE TITLE
Both files, exe and zip, are being flagged by my Bitdefender Total Security

### ISSUE THREAD

**Issue by pushkaryadav** [AutoDarkMode/Windows-Auto-Night-Mode#267]
**Describe the bug**
Bitdefender Total Security 25.0.26.89 (threat information update #10580147) is flagging the installation and zip file as "Gen:Variant.Bulz.786769".

**Description**
The .exe file is shown as clean when scanned manually or even on the virustotal.com but the antivirus flags it during installation. I have already tried changing default installation location and running the exe as Admin.

The .zip file is flagged before the download has even completed.

**Expected behavior**
Expected behaviour is a smooth installation.

**Comment by Spiritreader** [comment]
This is pretty much unavoidable.
The exectuables are new and not trusted yet.

It is not something we can fix.

**Comment by Armin2208** [comment]
I've sended a report to Bitdefender about the current Auto Dark Mode exe and zip getting a false positive.
You can also fill out this form to get a higher level of attention.
