### ISSUE TITLE
Wallpaper doesn't switch on Windows 11

### ISSUE THREAD

**Issue by leodoi3** [AutoDarkMode/Windows-Auto-Night-Mode#269]
On Windows 11 the wallpaper wont switch between dark/light themes. 
I played around with it and I think the issue is if you have virtual desktops open . Even if i set the option to multiple monitors it only changes the one you're on, if I switch back between virtual desktops then it shows  the previous theme again.

OS: Windows 11 21H2 (22000.194)

**Comment by Spiritreader** [comment]
This is a known kssue, for more details follow the link.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/228
