### ISSUE TITLE
Auto Dark Mode X is not stable yet

### ISSUE THREAD

**Issue by matsuda0707** [AutoDarkMode/Windows-Auto-Night-Mode#271]
I installed Auto Dark Mode X today, and it seems to work as the previous version.
But it is not stable, for example, when I activate Auto Dark Mode X to see the Auto Dark Mode X settings, the previously opened other windows become no-response!
In this case, i can not click Start menu button, settings, and MS store icons on the task bar for a few minutes. Sometimes I have to restart PC manually (no -respose from system).
As far as I do not acess Auto Dark Mode X during operation, Auto Dark Mode X works normally (autochange,etc).

**Comment by Sevastienn** [comment]
I think I experience the same problem. Whenever Auto Dark Mode settings or any transparent windows are open when one tries to drag any window (not necessarily the settings window) it has an enormous delay often coming to a complete halt. But it is not only with Auto Dark Mode X but also Auto Dark Mode. I have not experienced this issue on Windows 10, only on Windows 11 N. Maybe there is a problem with transparency in Windows 11 or in the N edition?

**Comment by Spiritreader** [comment]
Thanks for your report!

Yes, you're correct @Sevastienn, the window acting up while dragging is an issue with transparency effects.
We use the fluentwpf framework and it has no option to disable transparency (yet).

This behavior is tracked in https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/169.
For further updates, please folow that thread!
