### ISSUE TITLE
Difficult to see Light color

### ISSUE THREAD

**Issue by maboroshin** [AutoDarkMode/Windows-Auto-Night-Mode#274]
The settings window has focus, And, If the background is black, the selected heading will not be visible. In this case, "Personalization" is not visible. The color seems a little light.

Using AutoDarkModeX_10.0.0.26.exe, on Windows 10.

![image](https://user-images.githubusercontent.com/41102508/136173561-c138c589-a58a-4a9e-8bb4-d76274f9d758.png)

**Comment by Spiritreader** [comment]
Hi, thanks for reporting! 
Were are aware of this issue.
I've removed the text colorization of the selection for now, until we find a better solution to highlight selected entries.
