### ISSUE TITLE
More ways to force using a theme

### ISSUE THREAD

**Issue by JingBh** [AutoDarkMode/Windows-Auto-Night-Mode#277]
**Describe the enhancement or feature you'd like**

Sometimes I would like to use the dark theme during the day (maybe because of dark environment), but when I change the theme in Windows settings, the app automatically changes it back.

I found that I can force it using the tray icon, but since I'm hiding the icon, I see no way to do that now.

**Describe alternatives you've considered**

Maybe we can add an option in the app's main window to force a theme, or an option to fallback to the old version's behavior, which is to only switch theme on scheduled time, instead of observing all the time.

**Comment by JingBh** [comment]
Oh sorry, I didn't notice that.

But still, is it possible to make the app use the older version's behavior instead? (Not observing all the time)

**Comment by Spiritreader** [comment]
If I understand you correctly, you're talking about when using Windows Theme mode, right? 
![image](https://user-images.githubusercontent.com/18438899/136181239-f4773321-a198-4c29-a45b-791419b88621.png)

This is available in the latest beta build, for more details see here: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/171

**Comment by JingBh** [comment]
@Spiritreader Yes, That's exactly what I want! thx😄

But... when I updated to the latest beta build, the localization disappeared. Although I'm selecting Chinese, the whole UI is still English. If the translation is still incomplete, maybe I can help translating.

**Comment by Spiritreader** [comment]
The translation is indeed still incomplete, however the language selection not working anymore is indeed a new bug.

However, we are still missing a lot of translation strings overall, and are always happy to have people help out! 
If you want, you are very welcome to open a pull request for newly translated strings!

I will open a new issue for the localization bug.
Closing this for now as the original question has been answered.
