### ISSUE TITLE
Tray icon strings for translation

### ISSUE THREAD

**Issue by maboroshin** [AutoDarkMode/Windows-Auto-Night-Mode#287]
Right-click string on tray icon. It requires preparation for localizations. https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/284#issuecomment-937608165

**Comment by Spiritreader** [comment]
The tray is now localized.

There are three new translation strings, the string for "Close" has been re-used (msgClose) and does not need to be updated.

New strings:

- ForceLightTheme
- ForceDarkTheme
- TrayMenuItemOpenConfigDir
