### ISSUE TITLE
Provide better info section about autostart state

### ISSUE THREAD

**Issue by Spiritreader** [AutoDarkMode/Windows-Auto-Night-Mode#293]
**Describe the enhancement or feature you'd like**
Enhancement derived from https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/259#issuecomment-938806652 by @tooomm

Idea is to create a settings section with the title "Autostart" that
- informs the user which mode is active (logon task, normal autostart)
- provides a checkbox to disable/enable it

**How to implement**
Pretty simple:
- create a service api method that checks which (or if any) autostart mode is active
- add a small section to the settings UI

@Armin2208, please let me know what you think. Close the issue if you don't want sth like this.

**Comment by Spiritreader** [comment]
Progress Update
![image](https://user-images.githubusercontent.com/18438899/136672927-85355750-1e78-4eb2-8635-298f564f00f2.png)

**Comment by mangoepic** [comment]
![image](https://user-images.githubusercontent.com/71931749/136691972-2f051082-bfba-40d5-b2b2-75d58db39531.png)
It just updated and the "Autostart central" looks like this for me ... even though I didn't disable it anywhere

**Comment by Spiritreader** [comment]
> ![image](https://user-images.githubusercontent.com/71931749/136691972-2f051082-bfba-40d5-b2b2-75d58db39531.png) It just updated and the "Autostart central" looks like this for me ... even though I didn't disable it anywhere

please take a screenshot of the entries in this regkey section:
```
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run
```

**Comment by tooomm** [comment]
With this change, will disabling autostart also remove any registry or scheduler entries?

You did mention that @Armin2208 intentionally did not allow this for some reason in https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/259#issuecomment-938840502.
I wonder why this behavior is needed or wanted.

<br>

Maybe the `Refresh Autostart` button can be considered redundant and disabling & re-enabling the setting has the same effect?

**Comment by Armin2208** [comment]
A disable button for Autostart isn't necessary, because User can just deactivate it in Windows Settings or Task-Manager.
@Spiritreader integration is great, with a refresh button. I like it this is why we will and want to keep it :)
Just the Login Task instead of Autostart entry checkbox should move below the Toggle Switch.

**Comment by mangoepic** [comment]
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7318115/service.log)
![image](https://user-images.githubusercontent.com/71931749/136710721-00886b47-02b7-4b97-a30d-fec1fdf065c9.png)
@Spiritreader Alright I will keep it in mind!

**Comment by Spiritreader** [comment]
> [service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7318115/service.log) ![image](https://user-images.githubusercontent.com/71931749/136710721-00886b47-02b7-4b97-a30d-fec1fdf065c9.png) @Spiritreader Alright I will keep it in mind!

that does look like it is disabled tho. What does it say when you open task manager and go to the startup tab?

**Comment by mangoepic** [comment]
![image](https://user-images.githubusercontent.com/71931749/136713864-e96096be-3adb-4647-89d5-62c291a30bba.png)
@Spiritreader yes It seemed it was disabled - I didn't notice I had that many Autostart entries left. I forgot I put it in shell's Autostart which probably opened it. 
![image](https://user-images.githubusercontent.com/71931749/136713910-01a3d078-0019-47de-a912-708c6ddb2362.png)
It works now 👍
