### ISSUE TITLE
Close the app, reopen it, and close it again, can't repoen it anymore

### ISSUE THREAD

**Issue by CXwudi** [AutoDarkMode/Windows-Auto-Night-Mode#294]
**Description**
See a short video [here](https://imgur.com/a/dCNELjQ)

**Expected behavior**
App should close and reopen properly, without spanning lots of background processes.

**Log Data**
Log and my configuration are in the zip
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7313284/config.zip)

**Commit Hash and Version**
Auto Dark Mode X

**Screenshots**
See in description

**Comment by Spiritreader** [comment]
already fixed in latest build

**Comment by CXwudi** [comment]
@Spiritreader alright, thanks
