### ISSUE TITLE
Can't install through Microsoft Store on Windows 11

### ISSUE THREAD

**Issue by Samq64** [AutoDarkMode/Windows-Auto-Night-Mode#306]
**Description**
Clicking the download button on the Microsoft Store causes it to display "Downloading..." and then throws a `0x80190194` error after about 10 seconds. 

I tried restarting my PC and running both Microsoft Store troubleshooters from the settings app. (Apps & Features > Microsoft Store > Repair and System > Troubleshoot > Other Troubleshooters > Windows Store Apps)

I was able to successfully install another Microsoft Store app just now without problems.

**Expected behavior**
The app should successfully download and install through the Microsoft store on Windows 11.

**Log Data**
I can't provide any log data from the app because it's not installed yet.

**Commit Hash and Version**
`10.0.0 (0.5.10.2021)` (From the Microsoft store details page.)

**Screenshots**

https://user-images.githubusercontent.com/81489795/137025852-f37828d6-94e3-4706-880c-e80613298215.mp4

**Comment by Armin2208** [comment]
reuploaded exe, fixed
