### ISSUE TITLE
win11 when switch to different mode if the explorer was opened , some icons on ribbon will missing

### ISSUE THREAD

**Issue by RobertChou** [AutoDarkMode/Windows-Auto-Night-Mode#308]
**Description**
Details about the bug and how to reproduce it

auto dark mode X 。 win11 when switch to different mode if the explorer was opened , some icons on ribbon will missing

**Expected behavior**

**Log Data**

**Commit Hash and Version**

**Screenshots**

**Comment by RobertChou** [comment]
> 
> 
> Hello! Unfortunately we require more information to process this issue. Please complete filling out the bug report template and include a small gif or video that describes your issue.

attach the pic

**Comment by ZMYaro** [comment]
Is it possible this is related to #424?  There are some Explorer and Taskbar surfaces where I thought text and icons had disappeared, but they were stuck with the light mode text color on the dark mode background (or vice versa) due to that bug.

**Comment by Armin2208** [comment]
Probably
