### ISSUE TITLE
Scrolling not working on touchscreen devices

### ISSUE THREAD

**Issue by Spiritreader** [AutoDarkMode/Windows-Auto-Night-Mode#309]
**Description**
The ScrollViewer does not register touch screen events

**Expected behavior**

The ScrollViewer registers touch screen events

**Version Info**

Since 10.0.0.26

**Comment by Zhanyuanium** [comment]
Not Scrollable again 😥
```
version 10.3.0.90
HP Spectre 13-convertible aw, Windows 11 Pro build 23481 (dev insider preview)
```
On the version 10.1.0.10 it was solved, however this new interface seems to break it.

**Comment by Spiritreader** [comment]
Touch screen and panning support for touch has been enabled on our side.

This is an issue with modern-wpf that has existed for quite some time.
A fix for it would require a pull request there: https://github.com/Kinnara/ModernWpf

Here's a link to the already existing issue:
https://github.com/Kinnara/ModernWpf/issues/433
