### ISSUE TITLE
Windows 11 built-in theme selection

### ISSUE THREAD

**Issue by DeepChirp** [AutoDarkMode/Windows-Auto-Night-Mode#312]
In Windows 11, if I use the theme that is built-in, can I add an option in "Wallpaper/Themes" to automatically switch between the dark theme and the light theme provided by the system?
Although I can use the "Desktop Wallpaper" to switch, there is a drawback that in the "Settings" of the system, it will show that I am using a custom theme instead of the one provided by the system. And, this is not very friendly for people who are not familiar with Windows.
And it looks like the themes built into Windows 11 don't have a save option.
Thanks!

**Comment by shenzhiming88** [comment]
But this is strange ...... On my computer, there seems to be only two files in that directory, do I need to select a new theme before the system automatically generates these files?

**Comment by Armin2208** [comment]
> But this is strange ...... On my computer, there seems to be only two files in that directory, do I need to select a new theme before the system automatically generates these files? I think I would be better to test it later.

Strange! Please test this.

**Comment by shenzhiming88** [comment]
Oh, sorry, I made a mistake.
Perhaps instead of displaying the filename of the built-in theme, we could replace it with the corresponding name
![image](https://user-images.githubusercontent.com/66902050/137339039-1762d4cd-f926-4af4-bc18-bebc082b0b43.png)
