### ISSUE TITLE
Why is hiding tray icon option *not* recommended? (re: Auto Dark Mode X)

### ISSUE THREAD

**Issue by loyukfai** [AutoDarkMode/Windows-Auto-Night-Mode#320]
As title.

Cheers.

**Comment by Spiritreader** [comment]
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/26#issuecomment-926978588
^

**Comment by Spiritreader** [comment]
done `->` https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Why-is-it-discouraged-to-disable-the-tray-icon%3F
