### ISSUE TITLE
Philips Hue integration

### ISSUE THREAD

**Issue by laurentkempe** [AutoDarkMode/Windows-Auto-Night-Mode#327]
Integrate the control of [Philips Hue lighting](https://www.philips-hue.com/en-us) to adapt the lightning of a room.

An alternative would be to be able to run an external tool when events are raised.

**Comment by Spiritreader** [comment]
Custom scripting is now available in the latest beta builds.
For references, see: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts

**Comment by Eymay** [comment]
Open to test scripts on Hue's!

In terms of scenarios it should be possible to check wifi for location and bluetooth for proximity to the Hue bulb. Or a connection to Home Assistant could be amazing.
