### ISSUE TITLE
Desktop OneNote's Office Theme doesn't adapt properly to use system settings

### ISSUE THREAD

**Issue by WindowsTablet** [AutoDarkMode/Windows-Auto-Night-Mode#333]
**Description**

Set Microsoft Office to adapt to system, within Auto Dark Mode in the Apps section.

**Expected behavior**

It should switch OneNote's Office Theme to "Use system settings", but instead it leaves it blank making it unable to automatically switch to between  light and dark mode, unless you restart OneNote.

**Comment by Armin2208** [comment]
Open OneNote > File > Account > Office theme > Use system design
