### ISSUE TITLE
Improvements to Settings page

### ISSUE THREAD

**Issue by tooomm** [AutoDarkMode/Windows-Auto-Night-Mode#335]
**Describe what issue or improvement you have with the usability design**
![beta,log](https://user-images.githubusercontent.com/9874850/138594910-ea43f656-da65-4435-9b16-f2b0b8fda35a.png)

- Once one enables the `Beta` channel, the setting to automatically check for updates on start is enabled as well. No matter if you opted to only check based on time intervals.
  IMO there is no reason to enforce check on start just because somebody wants to run more recent, but potentially less stable and experimental beta versions with the latest features and changes.

- The log file link (`Logdatei öffnen` below `Konfig`) should be moved in the `About` menu, next to the version info to have all important debug information in one place. Even experienced users probably do not look for log files in the settings menu... (See #334)

<br>

**Comment by Spiritreader** [comment]
upcoming rework tracked in #603

**Comment by Spiritreader** [comment]
settings page rework is done
