### ISSUE TITLE
Improvements to Personalization page

### ISSUE THREAD

**Issue by tooomm** [AutoDarkMode/Windows-Auto-Night-Mode#336]
**Describe what issue or improvement you have with the usability design**
![custom](https://user-images.githubusercontent.com/9874850/138595301-55a3b0f3-305d-4b2e-bc8f-3a2bb928aba6.png)

In order to change the settings here and get to the submenu with all options, one has to click on one of the link styled texts.
I would prefer a button style or even better: make all paragraph clickable like a widget or box, instead just the small phrase which just doubles the section headline anyway...

**Comment by Spiritreader** [comment]
Personalization page has been overhauled in Beta 10.3.
![image](https://user-images.githubusercontent.com/18438899/194188037-7e2f8245-a109-470a-84c9-01a4eed95e4f.png)
