### ISSUE TITLE
Scrolling with a trackpad is way too sensitive

### ISSUE THREAD

**Issue by l0drex** [AutoDarkMode/Windows-Auto-Night-Mode#341]
**Description**

Scrolling with a trackpad is way too fast.

**Expected behavior**

It should be the same speed as anywhere else in the system.

**Log Data**

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7426069/service.log)
[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7426080/config.yaml.txt) (had to rename to *.txt for upload)

**Commit Hash and Version**

- Commit: `d134b56`
- App: `10.0.1.0`
- Service: `10.0.2.2`
- Updater: `2.4.0`
- Shell: `1.3.1.0`
- .Net: `5.0.10`

**Screenshots**

Note: I am using Windows 11.

**Comment by l0drex** [comment]
Unfortunatly I mainly use Linux and therefore can't help much.

**Comment by albertopasqualetto** [comment]
This seems not resolved in commit hash and version:

- Commit: `6575ecd`
- Service: `10.3.0.34`
- Updater: `2.5.1`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.7`

**Comment by Spiritreader** [comment]
I applied every mitigation I can. 
It seems to be a bug with WPF, nothing we can do.
