### ISSUE TITLE
Auto invert font color for TClock/TClock Redux

### ISSUE THREAD

**Issue by hyuuki** [AutoDarkMode/Windows-Auto-Night-Mode#342]
TClock/TClock Redux is a program to change/customize the date/time label in the taskbar. I'm using Windows 11, and still don't like that we cannot customize how the date and time is shown in the taskbar (that's why I'm using StartAllback for this and other functionalities). Currently, when Auto Dark Mode switch the light/dark mode, the color of TClock/TClock Redux cannot invert automatically. If possible, please add an option to check if we use TClock/TClock Redux and check the process name if running ("T-Clock" or "T-Clock Redux") and change the color in the registry as follows. 

Light Mode (Black Color)
`REG_DWORD, HKEY_CURRENT_USER\SOFTWARE\Stoic Joker's\T-Clock 2010\Clock, ForeColor, 16777215`

Dark Mode (White Color)
`REG_DWORD, HKEY_CURRENT_USER\SOFTWARE\Stoic Joker's\T-Clock 2010\Clock, ForeColor, 4210884306`

Currently, I'm using Python and Task Scheduler to do this similar task, but it would be better if Auto Dark Mode can add this functionality to  Auto Dark Mode.
Alternatively, add an option to start a program when switching to dark mode and light mode.

**Comment by Spiritreader** [comment]
We do not plan to support this for now, however you can use the new scripting engine to hook your existing python script into auto dark mode. It will then get triggered at the same time as Auto Dark Mode switches.
(https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts) for now.
