### ISSUE TITLE
Buggy UI

### ISSUE THREAD

**Issue by eileenthg** [AutoDarkMode/Windows-Auto-Night-Mode#343]
**Description**
Button elements may disappear or get replaced with the wrong images on hover.
Entire UI may disappear when screen is moved around or resized.
UI may also be buggy on first start. (Inconsistent.)
Display resets itself when opening and closing the start menu.
All these happen right after installation, regardless of reinstalls.
Computer was post clean install / reset.

**Expected behavior**
The UI to stay in place and not bug all over the place.

**Log Data**
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7433417/service.log)
[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7433421/config.yaml.txt)

**Commit Hash and Version**
![image](https://user-images.githubusercontent.com/40307498/139240277-9f3e2a4d-e82b-45db-b381-ed74b5c008ea.png)

**Screenshots**
https://youtu.be/FimhA45n6qk
Felt like video demonstration is a bit better.

**Comment by Spiritreader** [comment]
Do you still experience this with the latest Beta 10.3.0.82 or newer?

**Comment by eileenthg** [comment]
Not at all! Huh, I don't know when the problem went away.....
I did have a laptop monitor change a while back when it finally broke. Could a physical defect cause the issue above anyway?

**Comment by Spiritreader** [comment]
> Not at all! Huh, I don't know when the problem went away.....
I did have a laptop monitor change a while back when it finally broke. Could a physical defect cause the issue above anyway?

Very unlikely, this was some sort of issue between the ADM UI framework and graphics drivers I think.
We've made some changes to which framework renders the main window, so either that or automatic graphics driver updates fixed it.

Glad to hear it's working now!

Closing, feel free to reopen or file another report if you experience any more issues!
