### ISSUE TITLE
Can you add this feature directly in powertoys

### ISSUE THREAD

**Issue by sheikalthaf** [AutoDarkMode/Windows-Auto-Night-Mode#344]
I know this is really great feature but if you add this feature directly to powertoys it will be easily adopted by all powertoys users. I hope you can do this to make windows community more stronger

**Comment by sheikalthaf** [comment]
Any update on this?

**Comment by Spiritreader** [comment]
With the way APIs are right now, it's not gonna happen unfortunately. If this ever becomes a possibility again we will update.
