### ISSUE TITLE
VSCode theme doesn't change when manual switching using AutoDarkMode despite the settings. Probably an AutoDarkMode bug.

### ISSUE THREAD

**Issue by aderchox** [AutoDarkMode/Windows-Auto-Night-Mode#345]
Steps to reproduce:
1. Set an auto switching schedule from 7 am to 10 pm.
2. Set  `"window.autoDetectColorScheme": true,` in VSCode and choose a default dark theme (e.g.: `"workbench.preferredDarkColorTheme": "Default Dark+",`).
3. At 4pm right click on the auto dark mode app icon and click "Dark Theme".
4. The Windows goes to Dark, but the VSCode doesn't become dark. It remains in light mode.

WHY I think it's an AutoDarkMode manual switching bug:
I've tried switching to dark mode using Windows settings and this issue doesn't occur again (VSCode works correctly). So it must be an issue with how AutoDarkMode does it.

**Expected behavior**
VSCode preferred dark theme must be activated when the above settings are set in VSCode and when Dark Mode is chosen from the AutoDarkMode icon's right click menu.

**Commit Hash and Version**
Auto Dark Mode 3.0.1

**Comment by Spiritreader** [comment]
Unfortunately, we are no longer providing support for Auto Dark Mode v3.
It is available for people to use if they desire, but it is no longer being actively maintained.

Please try with the latest version.

**Comment by aderchox** [comment]
> Unfortunately, we are no longer providing support for Auto Dark Mode v3. It is available for people to use if they desire, but it is no longer being actively maintained.
> 
> Please try with the latest version.

The newer version doesn't have this issue. Thanks.
