### ISSUE TITLE
After toggling Force Dark Mode, the Windows touch keyboard sometimes initially shows black, until I restart explorer.exe

### ISSUE THREAD

**Issue by WindowsTablet** [AutoDarkMode/Windows-Auto-Night-Mode#347]
**Description**

After toggling Force Dark Mode on and the off, the Windows touch keyboard sometimes initially shows black, until I restart explorer.exe

I'd suggest adding an option in the settings of ADM to restart explorer.exe after each mode switch to prevent issues like these.

This is on Windows 11, but the issue might be present on Windows 10 too.

**Comment by Spiritreader** [comment]
I am always a bit wary and sceptical to implement workarounds for Windows bugs, especially if they're as intrusive as killing the explorer, when the root cause is Windows' own poor handling of theme switching.

**Comment by WindowsTablet** [comment]
I understand, that's why I'm asking it as an option, that's disabled by default.
It's much more elegant to have ADM restart explorer for me, than to me having to manually restart it, after each theme switch.

**Comment by Spiritreader** [comment]
Are you positive that re-launching the on-screen keyboard isn't sufficient to refresh the UI elements that have not switched?

**Comment by WindowsTablet** [comment]
> Are you positive that re-launching the on-screen keyboard isn't sufficient to refresh the UI elements that have not switched?

Relaunching, as in tapping the icon on the taskbar doesn't fix it. But I haven't tried restarting the TexInputHost.exe process yet. I will try that next.

FYI, the issue also happens the other way around. When toggling Force Light Mode on and off, the touch keyboard initially shows white.

**Comment by WindowsTablet** [comment]
So I triggered the issue again, and restarting the TexInputHost.exe process also seems to solve this issue.

**Comment by WindowsTablet** [comment]
Maybe a better suggestion would be, to allow executing a custom command, after each mode switch.

**Comment by Spiritreader** [comment]
custom scripting is available in the latest betas (10.0.2.6 and up).
Please see this guide on how to use the feature
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts.

This will allow you to call any script / functionality you like.
For more info see here: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/186

**Comment by WindowsTablet** [comment]
Thank you.
