### ISSUE TITLE
Unexpected random switching between light and dark modes

### ISSUE THREAD

**Issue by ChriiMoral** [AutoDarkMode/Windows-Auto-Night-Mode#348]
**DESCRIPTION**
Keeps switching alternating between light and dark. No noticeable pattern (such as how long between switches, etc.).

Time settings are set to _custom hours_ (start time for light mode being 8 AM and for dark being 6 PM).

App settings are set as follows: _Apps_: Adapt to system; _System_: Adapt to system (with taskbar option UNchecked); _Office_: Adapt to system (with alternative light mode checked).

No theme or wallpaper was chosen under the _Personalization_ area.

Finally, in Settings, _12 hour clock_ is checked; _Language_ is set to English; _Automatic update check_ is checked (7 days);  _Automatically download and install new versions_ is checked; _Stable_ is selected; _Autostart with Windows_ is toggled ON.

Also, the scrolling speed is much too speedy, but that was already reported.

**Expected behavior**
Mode switching should only occur at the times selected. The scrolling should have the same speed as the rest of the OS.

**Log Data** (in .txt 'cause of formatting issues)
[config - Copy.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7455330/config.-.Copy.txt)
[service - Copy.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7455331/service.-.Copy.txt)

**Screenshots for the commit and version info.**
![Screenshot 2021-11-01 140925](https://user-images.githubusercontent.com/63615949/139721452-174f1835-f05c-4493-bf6a-f97dd8081661.jpg)

**Comment by Spiritreader** [comment]
The only thing that is could be is you having dark theme on battery enabled.

Please see https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/286.

Faulty chargers or software that incorrectly uses the Windows discharge state will send a battery disconnect event to the entirety of Windows, even when you are plugged in.

**Comment by ChriiMoral** [comment]
Thank you so much!

I appreciate the prompt response! I've disabled the feature. I did not know
that this issue with the charging states was a thing.

Thanks again,
Chrii
