### ISSUE TITLE
ADM is closing when using Logon Task

### ISSUE THREAD

**Issue by QuestYouCraft** [AutoDarkMode/Windows-Auto-Night-Mode#357]
I have autorun installed using the task scheduler. It runs well, but I noticed that the theme does not change. Looking in the tray, I noticed that the program was not running. After turning on the log, I noticed that the program starts, but after a while it closes with result "The process was terminated unexpectedly (0X8007042B)":
![Screenshot](https://i2.paste.pics/fb278b7cec5296bc8fc95938803c6785.png)
![Screenshot](https://i2.paste.pics/3489be6a6a982aa719dfee70b3ca6ea7.png)
 It turned out that the problem was that there was a tick in the task scheduler, which, in theory, should not work at all. But for some reason it works. The solution to the problem turned out to be disabling these checkboxes. But these checkboxes should be disabled initially when ADM creating a task. Why should I turn them off myself?
![Screenshot](https://i2.paste.pics/1c6933ed627212993cd0c864b73265d9.png)
I want to draw your attention to the fact that setting "Energy saver mitigation for theme switch" and other battery settings in ADM are (and were) disabled.

**Comment by Spiritreader** [comment]
Oh interesting. thanks for bringing this to our attention. We will look into it.

**Comment by Spiritreader** [comment]
This is now available in the latest beta.
In order for it to take effect, you will have to re-toggle the Logon task so that it updates the entry.
