### ISSUE TITLE
Chrome top bar is not switching to dark mode!

### ISSUE THREAD

**Issue by yazan1107** [AutoDarkMode/Windows-Auto-Night-Mode#358]
**Description**
Chrome top bar(where X MAXIMIZE MINIMIZE) is not switching modes! it keeps the same color, - it does not turn black mode-
file explorer and rest of the apps works fine!

**Expected behavior**
Expected: switching to dark when dark mode is on
What happens: does not switch

**Log Data**

**Commit Hash and Version**

10.0.1.76

**Screenshots**
![image](https://user-images.githubusercontent.com/78726445/140613896-d2d98dd1-7032-49cf-bf62-b4de86d759a9.png)

**Comment by yazan1107** [comment]
why @Spiritreader

**Comment by Spiritreader** [comment]
This is not an issue with Auto Dark Mode. Chrome does not change the title bar color when enabling dark mode.
You can download themes at the chrome webstore that may accomplish this, but, it's not a bug.

**Comment by yazan1107** [comment]
other memebers reporting that auto dark mode switches chrome to black title bar, only my pc it doesnot!
actually i think the bug comes from that i installed a theme on chrome and than uninstalled it!
