### ISSUE TITLE
Specific color for incognito tabs(to differ them from dark mode)

### ISSUE THREAD

**Issue by yazan1107** [AutoDarkMode/Windows-Auto-Night-Mode#359]
**Describe the enhancement or feature you'd like**
Specific color for incognito tabs(to differ them from dark mode)
for example purple for incognito tab
dark for dark mode regular
light for light mode regular
**Describe alternatives you've considered**
easy purple incognito mode theme, but it only works for dark mode!
**Additional context**

**Comment by Spiritreader** [comment]
I think you're confusing Auto Dark Mode with your web-browser.
Such a feature has to be supported within your web-browser.
This has nothing to do with Auto Dark Mode.
Please direct your feedback at the developers of your browser.
