### ISSUE TITLE
ADM does NOT turn on on NonDST!

### ISSUE THREAD

**Issue by brmonaghan** [AutoDarkMode/Windows-Auto-Night-Mode#361]
**Description**

Details about the bug and how to reproduce it
Autodark mode does NOT turn off at Sunrise by 1 hour if NON DST!

**Expected behavior**

Change to light mode at 6:41am instead of 7:41am (as of 211107T1228Z)
**Log Data**

**Commit Hash and Version**

![image](https://user-images.githubusercontent.com/71337477/140644937-154180f3-3b55-47cc-8fbf-a5b76cfde249.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/71337477/140644959-3636e477-5745-425c-aae8-197e8ebdf876.png)

**Comment by Spiritreader** [comment]
ADM uses your local system time zone for determining whether DST should be applied or not.
You can see that here:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/blob/eafcbf8b04e995330439ca72e730d47dfa20b263/AutoDarkModeSvc/Handlers/LocationHandler.cs#L35

 What time zone did you configure on Windows? Does it match your geographic location?

**Comment by brmonaghan** [comment]
EST. Yes it matches Erwin NC. Also our clocks changed by 1 hour so we changed from EDT to EST.

**Comment by Spiritreader** [comment]
Hmm, I would assume that there is an issue with C#'s implementation of retrieving the local time zone.
According to the documentation DST information should be baked into the local timezone
https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.isdaylightsavingtime?view=net-5.0

**Comment by brmonaghan** [comment]
Yep. So we need this fixed right?

**Comment by Spiritreader** [comment]
I am not sure yet what exactly is happening, if and what needs to be fixed. This warrants further investigation.
Until we have come to a conclusion, you apply a 1 hour offse to your sunrise times.

**Comment by brmonaghan** [comment]
Ok thank you

**Comment by Spiritreader** [comment]
Hold on a minute.
When was your DST switch?
If it was less than 24 hours ago, you will have to wait for up to 24 hours for it to propagate.

**Comment by brmonaghan** [comment]
Just at 2AM this morning!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by Spiritreader** [comment]
We've added an info text that informs users when the next update is due
![image](https://user-images.githubusercontent.com/18438899/140661597-89da2b94-dacb-4d85-8f31-94fd60fc29ae.png)

**Comment by brmonaghan** [comment]
Ok thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by brmonaghan** [comment]
FIXED FINALLY! closing!

**Comment by Spiritreader** [comment]
> FIXED FINALLY! closing!

Well, since everything worked as intended and no actual code was modified, I wouldn't call it fixed, but I'm glad it is working now.
