### ISSUE TITLE
Lat/Lon Boxes removing commas

### ISSUE THREAD

**Issue by crashmit** [AutoDarkMode/Windows-Auto-Night-Mode#364]
**Description**
I use the Lat/Long Coordinate System to toggle the dark mode. The times are offset for me by a few hours. I verified the validity of my Lat Long Coordinates and checked for "correct" sunset and sunrise times. 

ADM shows this: 
![image](https://user-images.githubusercontent.com/58466626/140745588-d41a08e9-a2e0-46de-887d-f283925a60a2.png)

A website I found shows this: 
![image](https://user-images.githubusercontent.com/58466626/140745552-458e0f73-4b3b-4ac9-85a7-e098a499d5a3.png)

**Log Data**

**Commit Hash and Version**
![image](https://user-images.githubusercontent.com/58466626/140745677-71536b38-188b-4bed-a9f4-d122b2a51eec.png)
(A button to copy the information would be nice, as I can't select the text and don't want to type it out)

**Screenshots**
See above

**Comment by Spiritreader** [comment]
The entered position data is wrong.
Please enter correct Lat/Lon values.

You were most likely looking for 48.13514 and 11.58191 instead of 48135124 and 11581981

**Comment by crashmit** [comment]
You're right but the issue isn't solved sadly. When I paste the coordinates into ADM with the "." included, it changes them automatically once I leave the field, see the screenshot below. 

![image](https://user-images.githubusercontent.com/58466626/140746677-c14a4d43-bee4-4b87-899c-6a594e11c7c2.png)

**Comment by Spiritreader** [comment]
That is probably because the entered data is out of range.
Click save with 90/180, you should be able to edit them afterwards.

**Comment by crashmit** [comment]
Found it! The issue is that "." isn't accepted by the program. It requires a comma. I manually edited the config file and after switching back to the page it now displays the values with "," instead of "."

**Comment by crashmit** [comment]
I just updated to 
- Commit: `c142563`
- Service: `10.1.0.2`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `5.0.10`
and it still appears there, sadly. Same behaviour as in my last comment.

**Comment by cmhrky** [comment]
- Commit: `c142563`
- Service: `10.1.0.2`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `5.0.10`

https://user-images.githubusercontent.com/17867666/140797392-f927e7d6-0c76-4851-8aca-1203ae3a518a.mp4

**Comment by Spiritreader** [comment]
I've found some intermitent issues with the parsers. The numberboxes were indeed not the cause of this issue, but translation between the config file and the numbox string inputs.

Should work now in Beta 10.0.1.3

**Comment by crashmit** [comment]
Great it works now! One small quirk I noticed was that after putting in my Lat and Long I had to press "Enter" once, as the "Apply Coordinates" Button was still greyed out despite both fields being filled. After I pressed enter in Long, the button became active.

**Comment by Spiritreader** [comment]
> Great it works now! One small quirk I noticed was that after putting in my Lat and Long I had to press "Enter" once, as the "Apply Coordinates" Button was still greyed out despite both fields being filled. After I pressed enter in Long, the button became active.
> 
> ![image](https://user-images.githubusercontent.com/58466626/140892172-0ac75602-7589-43ef-8998-4070efffe3e8.png)

I faintly remember a conversation with Armin where he stated that this was intentional, which is why I left it like this. But I believe this no longer applies to the newer validation rules so I'll fix this.

Also for issues like these, feel free to create a new github issue with the UX tag, as this is logically separated from the last problem.
