### ISSUE TITLE
auto dark mode with multipie wallpapers(like dynamic wallpaper on apple mac)

### ISSUE THREAD

**Issue by yazan1107** [AutoDarkMode/Windows-Auto-Night-Mode#368]
auto dark mode with multipie wallpapers(like apple one on mac), having for example dessert and it changes wallpaper every hour the lighting in the photo changes while changing a lil bit of shades of taskbar

**Comment by Armin2208** [comment]
this is something we will not implement, because this doesn't fit into the philosophy of auto dark mode. In addition, [WinDynamicDesktop](https://www.microsoft.com/de-de/p/windynamicdesktop/9nm8n7dq3z5f?activetab=pivot:overviewtab) does that.
