### ISSUE TITLE
The app doesn't update

### ISSUE THREAD

**Issue by Rex501st** [AutoDarkMode/Windows-Auto-Night-Mode#37]
Continuing my OG Thread: https://github.com/Armin2208/Windows-Auto-Night-Mode/issues/22

The app doesn't update reliably. I have to check github myself every so often.  

Perhaps get more detail before closing tickets?

**Comment by Armin2208** [comment]
Do you have a firewall that blocks the in going connection of auto dark mode?

**Comment by MercuryXIII** [comment]
Sorry for the late reply. Work has me all tied up.

I have AdGuard which blocks ads but I doubt that is causing the issue.

**Comment by Spiritreader** [comment]
Version X uses a new update system if you install without admin elevation.
Please update manually, and re-open this issue if still relevant in the future.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26
