### ISSUE TITLE
Latitude/Longitude bug

### ISSUE THREAD

**Issue by iamrusskikh** [AutoDarkMode/Windows-Auto-Night-Mode#374]
After restarting PC or re-opening app, coord feilds change point to comma and after it feilds lost decimal separator therefore the coordinates are not determined correctly and the time of sunrise and sunset becomes different. If don't re-open app, sunrise and sunset will not updates for the real 

**Log Data**
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7574465/service.log)
[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7574466/config.yaml.txt)
Config and servise log after getting the bug again
**Commit Hash and Version**
![image](https://user-images.githubusercontent.com/49066756/142724580-d4b600ae-b14f-4d32-bff1-a21d8341412e.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/49066756/142724720-6e2dba21-2e40-4141-b097-91488602c044.png)
close and open app from tray, point changed to comma
![image](https://user-images.githubusercontent.com/49066756/142724754-cd995f27-2f2f-46e9-af55-3e4815ca2e4e.png)
click "Apply Coordinates" and time was changed becouse of changing applied coordinates
![image](https://user-images.githubusercontent.com/49066756/142724802-ed8f4eea-e4a9-4d76-861b-4d06acafa76b.png)
If close and open app from tray again, deciminal seperator will lose at all
![image](https://user-images.githubusercontent.com/49066756/142725077-c4c0a5e0-1f50-47c1-b0a5-5ad51528c453.png)

**Comment by Armin2208** [comment]
Please Update your App, the bug was fixed in the newest version
