### ISSUE TITLE
Can you add a theme that only automatically switches the app?

### ISSUE THREAD

**Issue by tikko-now** [AutoDarkMode/Windows-Auto-Night-Mode#379]
**Describe the enhancement or feature you'd like**
Can you add a theme that only automatically switches the app? I don’t want the system theme to be switched at the same time, I want to switch only the theme of the application。
**Describe alternatives you've considered**

**Additional context**

**Comment by Spiritreader** [comment]
That is precisely what this tab is for
![image](https://user-images.githubusercontent.com/18438899/142875672-92cda3c3-9d10-464e-b760-9867bb6141e4.png)

If you don't want to switch system, set it to off.

**Comment by tikko-now** [comment]
> 这正是此选项卡的用途 ![image](https://user-images.githubusercontent.com/18438899/142875672-92cda3c3-9d10-464e-b760-9867bb6141e4.png)
> 
> 如果不想切换系统，请将其设置为禁用。

thank you，I did not understand the meaning of some options in the past, now I understand
