### ISSUE TITLE
Failed to switch language to Traditional Chinese

### ISSUE THREAD

**Issue by SiderealArt** [AutoDarkMode/Windows-Auto-Night-Mode#381]
**Description**

Change the language to Traditional Chinese.

**Expected behavior**

Instead of Traditional Chinese, the app switches the language to Simplified Chinese.

**Log Data**

**Commit Hash and Version**

![image](https://user-images.githubusercontent.com/30827929/143295992-a4719cb2-64bc-4fd8-a84b-62401dceb846.png)
The app crashes when I clicked copy, I'll submit a new issue about this.

**Screenshots**

![image](https://user-images.githubusercontent.com/30827929/143295600-5ad862c2-0d57-4387-ba0a-e5d7dc6b95bb.png)

**Comment by Armin2208** [comment]
you're right! thanks.
