### ISSUE TITLE
Apply Button Missing

### ISSUE THREAD

**Issue by Arihant25** [AutoDarkMode/Windows-Auto-Night-Mode#384]
On the home screen of the app it says:

![image](https://user-images.githubusercontent.com/22986534/143666786-298b7b8f-918d-4dcc-9d6d-f5071da2378c.png)

But where's the Apply button?

**Comment by pc-v2** [comment]
It seems like this is from old version (3.0)
the changes applied automatically when you edit the time, if you use "From sunset to sunrise, there's 'set' button next to the offset.

![image](https://user-images.githubusercontent.com/58063311/143678965-52d5dc94-8a7f-4330-8738-8e66b7b0cc3d.png)

Apply button appears right to coordinate mode

![image](https://user-images.githubusercontent.com/58063311/143678912-f12ecb1a-b835-4f38-9d99-3c0173581ebd.png)

**Comment by Arihant25** [comment]
No, I'm on the latest version.
![image](https://user-images.githubusercontent.com/22986534/143680021-186098c4-0e63-477d-a46b-34a895786f72.png)

I think we should rephrase the sentence 'Click Apply' because changes are automatically applied.

**Comment by pc-v2** [comment]
![image](https://user-images.githubusercontent.com/58063311/143686440-5ac99f7b-e9ff-4b37-90a5-1a7000edd863.png)
I mean this, old string value from 3.0
![image](https://user-images.githubusercontent.com/58063311/143686446-bd6b1eac-0f25-4ceb-909b-038f9f1efccd.png)

**Comment by pc-v2** [comment]
My proposal

for "Custom start time"
> Set the time and hit check mark

**Comment by Arihant25** [comment]
Or maybe just: "Set the time and your changes are automatically saved"?
