### ISSUE TITLE
Please add the function that can control the mode of Visual Studio2022.

### ISSUE THREAD

**Issue by samuhoshi** [AutoDarkMode/Windows-Auto-Night-Mode#389]
**Describe what issue or improvement you have with the usability design**
Now the Visual Studio has dark mode. I
**Describe how you would like to see it improved**

**Additional context**

**Comment by pc-v2** [comment]
it can be follow based on system state
![image](https://user-images.githubusercontent.com/58063311/144050690-fb7af79f-1c22-4758-9b30-925d21d50b70.png)

**Comment by Spiritreader** [comment]
Please use pc-v2's instructions to set theme switching up for VS2022. Should you need more functionality, please use our scripting module.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts
