### ISSUE TITLE
diashow - translation mistake?

### ISSUE THREAD

**Issue by azumukupoe** [AutoDarkMode/Windows-Auto-Night-Mode#394]
### Question

I believe diashow is German for slideshow, no?
here, it's being used in English sentences and I got confused...

**Comment by Armin2208** [comment]
yes, you are right. thanks.

**Comment by Armin2208** [comment]
we need to also change this in app translation

**Comment by Spiritreader** [comment]
already changed in app.

**Comment by Armin2208** [comment]
Sam, [31.12.2021 01:04]
dev who is not on beta build *disappoint*

Sam, [31.12.2021 01:05]
:P
