### ISSUE TITLE
The theme changes to dark for few seconds and again switches to light in the time when it is supposed to be only light.

### ISSUE THREAD

**Issue by natharahul** [AutoDarkMode/Windows-Auto-Night-Mode#397]
I used dark theme based on location coordinates. Windows 11.

**Comment by Spiritreader** [comment]
You have not provided any information that is useful to help you with your issue.
Also, the UX template is not meant for bug reports.

Please ensure you have read this if you get intermittent switching https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/386.

If you require further help, please open another issue, following the bug report template.
