### ISSUE TITLE
Add Visual Studio Code to supported Apps

### ISSUE THREAD

**Issue by crstmkt** [AutoDarkMode/Windows-Auto-Night-Mode#398]
**Describe the enhancement or feature you'd like**
I would like the app to change my Visual Studio Code Color Scheme. Is this, somehow, possible?

**Comment by Armin2208** [comment]
Visual Studio Code has built in suppot for Auto Dark Mode, [please check our Wiki](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Apps-with-Auto-Dark-Mode-support).

**Comment by crstmkt** [comment]
My Bad. Thank you!
