### ISSUE TITLE
Windows ARM64 Service 

### ISSUE THREAD

**Issue by booruce** [AutoDarkMode/Windows-Auto-Night-Mode#401]
Hello,

Thanks for making this app. I understand its already quite a lightweight app and service but are there any plans to compile a ARM64 build of this for Windows. My surface pro x will thank you :)

**Comment by Spiritreader** [comment]
Microsoft's own Windows App SDK won't support ARM64 targets. 
Sadly going forward, it will be required to use for some functionality as well as the UI. As such, there are no plans to provide ARM support unless Microsoft's tooling and buildability changes such that it isn't either impossible or frustrating at its core.
