### ISSUE TITLE
Custom Theme Delete Prompt

### ISSUE THREAD

**Issue by gpallas16** [AutoDarkMode/Windows-Auto-Night-Mode#404]
Installing a deskthemepack in windows with a wallpaper embedded adds the theme in C:\Users\User\AppData\Local\Microsoft\Windows\Themes as a folder (e.g. C:\Users\User\AppData\Local\Microsoft\Windows\Themes\MyTheme). In order for the app to "catch" the theme I have to go inside the MyTheme folder copy the mytheme.theme file and paste it outside of the folder (from C:\Users\User\AppData\Local\Microsoft\Windows\Themes\MyTheme to C:\Users\User\AppData\Local\Microsoft\Windows\Themes\). Even though this works when the theme changes, the app deletes the folder C:\Users\User\AppData\Local\Microsoft\Windows\Themes\MyTheme as a result the theme can no longer have the embedded wallpaper. A current workaround I m using is to take the permission to delete the folder but it would be nice if this could be fixed.

**Comment by Spiritreader** [comment]
It also looks like you are trying to describe multiple issues in one issue report, which is very hard to discern.

Themes in the user theme directory are also picked up recursively, so I'm not entirely sure what you're referring to.
In addition, Auto Dark Mode is unable to delete folders outside of its own installation directory and %AppData%\Roaming

Please re-open the issue by using the formatted bug report templates, they're there for a reason.
