### ISSUE TITLE
[Feature Request] Ability to pause Auto Dark Mode When Certain Apps Running

### ISSUE THREAD

**Issue by pc-v2** [AutoDarkMode/Windows-Auto-Night-Mode#405]
**Describe the enhancement or feature you'd like**
As the title says.
while I draw with drawing app, the stylus get lag input when switch happens

**Comment by Armin2208** [comment]
thanks for your feature request. 
would you think #371 is a great solution for this problem?

**Comment by pc-v2** [comment]
> thanks for your feature request. would you think #371 is a great solution for this problem?

could be :) I like the idea! 💡

**Comment by Spiritreader** [comment]
I think the proposed solution in #371 is the way to go forward for now.
Reason being that it is very likely (comparatively) resource intensive to monitor for open processes.

Using the Windows idle timer should have a non-noticeable performance impact.
Still, implementing this requires a major restructure in terms of how to properly postpone theme switches.
ATM we're in maintenance mode, meaning critical bugfixes only.
So this could take a while to implement and hit beta.
