### ISSUE TITLE
Integration with Bing Wallpapers

### ISSUE THREAD

**Issue by Eymay** [AutoDarkMode/Windows-Auto-Night-Mode#406]
I was using Bing wallpapers that changed wallpapers daily but Auto Dark Mode interferes with Bing's daily refresh process somehow. When dark mode is activated, Bing wallpaper creates a notification saying 'We noticed you changed your wallpaper, daily refresh disabled'. The interesting part is I'm not using anything about wallpaper on Auto Dark Mode, wallpaper or theme switching is disabled. 

I would like to use Bing wallpaper for the day and something darker for the night. They are easily downloadable.

**Comment by Spiritreader** [comment]
Have you attempted to use the Windows theme mode?
It is possible that changing the registry keys responsible for App/System theme disables the bing theme switch.

From what I can see and what APIs are available, this is not really something we can fix, but rather a limitation by MS.

**Comment by Spiritreader** [comment]
We support windows spotlight now. That shall count as bing wallpaper support.
