### ISSUE TITLE
Discord Auto Dark Mode

### ISSUE THREAD

**Issue by yamyam263** [AutoDarkMode/Windows-Auto-Night-Mode#407]
I think it would be a great idea to toggle Auto Dark Mode for Discord, it has the ability to switch themes between dark and light, but none based on system setting. 

Seeing as this repo has support for custom scripts, a question is raised about the possibility of writing a script to achieve this functionality.

**Comment by pc-v2** [comment]
> I think it would be a great idea to toggle Auto Dark Mode for Discord, it has the ability to switch themes between dark and light, but none based on system setting.
> 
> Seeing as this repo has support for custom scripts, a question is raised about the possibility of writing a script to achieve this functionality.

you sure?
![image](https://user-images.githubusercontent.com/58063311/147514962-a9d92e50-6477-4fa1-afd4-f7dbea24354a.png)
****

**Comment by Spiritreader** [comment]
Thanks for your submission.
As pc-v2 mentioned, Discord already has this functionality,

Also, for custom scripts discussions, please use the Discussion tab!

**Comment by Armin2208** [comment]
I'm impressed discord has this
