### ISSUE TITLE
Switches to light mode, but not to dark mode

### ISSUE THREAD

**Issue by jorgetrueba85** [AutoDarkMode/Windows-Auto-Night-Mode#410]
Hi, my problem is that the program **works correctly when switching to light mode** in the morning with 1 or 2 minutes of delay, but **it never switches to dark mode**, i have to force it with the _system wide hotkeys_.
Thanks.

**Comment by Spiritreader** [comment]
Hello, unfortunately your bug report did not follow the template.
We can't help you if you don't give us any debug information.

Please re-open the issue by using the formatted bug report templates, they're there for a reason.
