### ISSUE TITLE
Switches to light mode, but not to dark mode

### ISSUE THREAD

**Issue by jorgetrueba85** [AutoDarkMode/Windows-Auto-Night-Mode#411]
Hi, from the beggining the only settings i changed where the time, which i set to detect location _(from sunset to sunrise),_ also added some shift to the light mode time, set what will adapt to the system and set it to the beta channel.

**Expected behavior**
I Expected the program to change correctly both themes in the indicated time, but that is not what happens, the light mode works correctly with 1 or 2 minutes of delay but it never switches to dark mode. I have to force dark mode with the _system-wide hotkeys_.

**Log Data**
Attach the service.log file
Attach the config.yaml file
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7815245/service.log)
[config.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7815259/config.txt)
They can be found in %AppData%\AutoDarkMode
**config.yaml was converted to txt**

**Commit Hash and Version**
- Commit: `22e2298`
- Service: `10.1.1.4`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

**Screenshots**

None

**Comment by jorgetrueba85** [comment]
It seems like it has to do with something about forcing the dark/light theme, i´m going to keep checking it and if that was the problem i´ll close the issue. 👍

**Comment by Spiritreader** [comment]
I've gone through the logs and I can find nothing wrong with the theme switching mechanic.

As the name suggests "force light theme" or "force dark theme" respectively, will force ADM to switch to the specified theme and **never** switch back again unless you configure and use the "no force" hotkey.

In your case, you only use the force light and force dark hotkeys.
Forcing a theme will disable automatic theme switching until you clear the flag.

**Comment by jorgetrueba85** [comment]
Ok, thanks for responding, i´m going to check that i dont leave the _force light mode_ enabled, and in any case i'll comment here again and/or close the issue. Have a good day 😀.

**Comment by jorgetrueba85** [comment]
It seems like the _force light mode_ was the cause of the problem, it is working correctly so i'm closing this issue. Thanks for the support 👍.
