### ISSUE TITLE
Restart Office Apps on theme change

### ISSUE THREAD

**Issue by euinor** [AutoDarkMode/Windows-Auto-Night-Mode#414]
More of a question that an issue: Is there a way to restart office apps once a theme changes, while keeping open windows?

For example, if I put my computer to sleep at night, when I wake it in the morning the theme is day, but my office apps (open from the previous night) are dark. I have to close them all and re-open manually - a pain if I have a lot of documents open. A 'close office "session" and reopen' button would be useful. But I expect this has been thought of already...

**Comment by Armin2208** [comment]
not possible with Auto Dark Mode AND not planned.
But if you use Office 2021 or subscribe to Office 365, you can use the new System theme setting in Office. So it doesn't need a restart after theme update.

**Comment by Armin2208** [comment]
![image](https://user-images.githubusercontent.com/32982430/149015850-65dda5e7-35c4-44ca-9e3b-6248b6eed7c8.png)
sorry I have Office on german

**Comment by euinor** [comment]
I'll work it out, thanks, I didn't know about that setting.
