### ISSUE TITLE
Windows 11 taskbar bug when switching theme

### ISSUE THREAD

**Issue by 2O48** [AutoDarkMode/Windows-Auto-Night-Mode#428]
**Description**

Details about the bug and how to reproduce it
Windows under normal theme as light/dark(switched by personalise settings), when the system theme switched by this app, the icons on taskbar still keep as the theme before switched.
This is the taskbar switched by the app from dark mode
![image](https://user-images.githubusercontent.com/21039418/155444304-05dc278b-9647-4887-9ee3-92efa0fb28d2.png)

**Expected behavior**

**Log Data**

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8129115/service.log)
[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8129123/config.yaml.txt)

**Commit Hash and Version**

- Commit: `b5ae91f`
- Service: `10.1.1.8`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.1`

**Screenshots**

**Comment by Spiritreader** [comment]
related to this?
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/424

**Comment by 2O48** [comment]
> related to this? #424
> 
> Do you use a Windows Preview build?



> related to this? #424
> 
> Do you use a Windows Preview build?

Seems the same, I’m using the latest Windows preview build

**Comment by JolyonJostar** [comment]
same, I'm on dev channel

**Comment by hoangqy** [comment]
same problem, i'm on beta channel, version 22H2 22581.1

**Comment by peppersean** [comment]
same on 22H2 22581.1

**Comment by wfsg00098** [comment]
theme switching still works

**Comment by wfsg00098** [comment]
theme mode still works

**Comment by lonewulfeu** [comment]
Same issue 22581.200

**Comment by Backnumber-Liu** [comment]
Same issue 22598.1

**Comment by SteveZhu0241** [comment]
Same on 22598.1

**Comment by dkostarnov** [comment]
same on 22598 (beta version AutoDarkMode)

**Comment by JustDesoroxxx** [comment]
Same on dev channel with a clean install

**Comment by JustDesoroxxx** [comment]
And definitely related to #424

**Comment by CuteCatXiao** [comment]
Same on 22610.1
Have to forced the explorer restart to temporary solve this issue

**Comment by QkeleQ10** [comment]
A lot of apps including Auto Dark Mode itself seem to break upon theme switch. This also occurs when switching manually through ADM: 
![image](https://user-images.githubusercontent.com/55982900/167926670-00b53070-9330-43ed-9bd2-12a7530371c5.png)
...but everything is fine when switching in Windows Settings.

**Comment by Spiritreader** [comment]
Microsoft broke registry based theme switch.
Please see here

https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/424

Auto dark Mode has a windows theme switch mode instead.

Registry based functionality is not coming back.
When w11 22h2 comes out the old mode will be replaced.

I'm closing this issue in favor of the other one as there are help and instructions available on how to circumvent it for now.
