### ISSUE TITLE
Great software，there is an unkind request

### ISSUE THREAD

**Issue by 3166265725** [AutoDarkMode/Windows-Auto-Night-Mode#429]
Can you develop a similar software for automatic theme switching that can be used in manjaro KDE plasma system? 
Or whether there is a similar software now. Can anyone tell me.

**Comment by Armin2208** [comment]
just use windows 😂

**Comment by Spiritreader** [comment]
A more serious answer:
AutoDarkMode is a Windows only software. We are not planning or intending to bring this to any other OS.
