### ISSUE TITLE
Win11: Using theme mode, Office always switches to strange "light" color

### ISSUE THREAD

**Issue by Zaelnorth** [AutoDarkMode/Windows-Auto-Night-Mode#430]
Greetings, I am using theme mode and have light/dark themes and everything works perfectly (thanks for that).

However when the system switches to light mode, my Office365 install goes into some strange "light" theme, then I always have to go manually change it back to "colorful" theme as nothing is selected in Office/Properties/Theme. Is there anything that can be done?

As for the Apps/Office theme, I have "Adapt to system"

Thank you

**Comment by Spiritreader** [comment]
Please see here
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/412

Also for newer Office Versions than 2019, the office switch should not be configured via auto dark mode, but rather by setting Office to "follow system theme"
