### ISSUE TITLE
sometimes fail to change wallpapers when automatically switching mode during lockscreen

### ISSUE THREAD

**Issue by hkcoding** [AutoDarkMode/Windows-Auto-Night-Mode#438]
**Description**

fails to change wallpapers when automatically switching mode, and maybe happened when screen was locked
switching time is often or so 17~18 [pm]([url]([url](url)))

**Expected behavior**

**Log Data**

**Commit Hash and Version**

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

**Screenshots**

[data.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8329469/data.zip)

**Comment by Spiritreader** [comment]
Hmm, you have the Windows built-in theme switcher enabled.
We're using a hidden API which has been discovered by the community.

I have personally experienced this once, but didn't occur anymore.
If it happens very frequently, please update us.

**Comment by cableghost** [comment]
I'm experiencing this, sort of. For me, it's only when the change was initially set for sunrise/sunset and my PC Windows session was locked.

Eg, if sunrise occurs prior to me unlocking my Windows session for the morning, although dark mode is turned off and most of my 'Theme' is switched to 'Light' upon me entering Windows, my dark mode wallpaper remains. It's not until I manually change the Theme, that the wallpaper changes.

**Comment by Spiritreader** [comment]
> I'm experiencing this, sort of. For me, it's only when the change was initially set for sunrise/sunset and my PC Windows session was locked.
> 
> Eg, if sunrise occurs prior to me unlocking my Windows session for the morning, although dark mode is turned off and most of my 'Theme' is switched to 'Light' upon me entering Windows, my dark mode wallpaper remains. It's not until I manually change the Theme, that the wallpaper changes.

could you also provide log files please?

**Comment by cableghost** [comment]
Per your request...
[AutoDarkMode.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8541286/AutoDarkMode.zip)
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8541289/service.log)

**Comment by Spiritreader** [comment]
@cableghost could you toggle this option and check back if this updates the theme correctly?

![image](https://user-images.githubusercontent.com/18438899/164760632-5427a046-3d2c-4b28-86e6-56f83023f006.png)

**Comment by cableghost** [comment]
Will do.

**Comment by cableghost** [comment]
Enabling that option worked... Wallpaper changed. No difference in log reading though.

**Comment by QuestYouCraft** [comment]
Moreover, this problem appeared and was repeated repeatedly only with the release of version 10.1.0. Personally, I have it only when changing from a light to a dark theme. When I work, there is a light theme, but as soon as the computer comes out of sleep mode in the evening, then after unlocking everything changes from the dark theme, except the wallpaper. Previously, this problem did not exist. Yes, you can check the box "Restore themes when changed externally", but this option probably (I haven't checked, so I assume) consumes more system resources. In short, I am also waiting for the elimination of this bug.

**Comment by Spiritreader** [comment]
> Moreover, this problem appeared and was repeated repeatedly only with the release of version 10.1.0. Personally, I have it only when changing from a light to a dark theme. When I work, there is a light theme, but as soon as the computer comes out of sleep mode in the evening, then after unlocking everything changes from the dark theme, except the wallpaper (they remain from the light one). Previously, this problem did not exist. Yes, you can check the box "Restoring themes with external changes", but this option probably (I haven't checked, so I assume) consumes more system resources. In short, I'm also waiting for this bug to be fixed.

I cannot reproduce this, I have the exact same scenario almost every day, and it switches properly with he same settings the others posted.

**Comment by QuestYouCraft** [comment]
> I need more data.

Ok. In Windows 11, I have the "Captured Motion" theme installed on a dark theme. On the light side - "Flow". Under these circumstances:

> When I work, there is a light theme, but as soon as the computer comes out of sleep mode in the evening, then after unlocking everything changes from the dark theme, except the wallpaper (they remain from the light one).

I get this in the system:

![Theme with the artifact](https://i2.paste.pics/cfe837a93499dc45360afe5af59b4e3a.png)

I think the important point is that after the manifestation of this bug, the file appears "Custom.theme" (in %LocalAppData%\Microsoft\Windows\Themes folder), which is the theme with the artifact. If you delete this file, then after the bug reappears, it will be created again.

**Comment by Spiritreader** [comment]
> > I need more data.
> 
> Ok. In Windows 11, I have the "Captured Motion" theme installed on a dark theme. On the light side - "Flow". Under these circumstances:
> 
> > When I work, there is a light theme, but as soon as the computer comes out of sleep mode in the evening, then after unlocking everything changes from the dark theme, except the wallpaper (they remain from the light one).
> 
> I get this in the system:
> 
> ![Theme with the artifact](https://camo.githubusercontent.com/facb404ad4eb399cbd6a8f6f515c5eb52aabe5cc8ae04ec224fb93e1cbde76d3/68747470733a2f2f69322e70617374652e706963732f63666538333761393334393964633435333630616665356166353962346533612e706e67)
> 
> I think the important point is that after the manifestation of this bug, the file appears "Custom.theme" (in %LocalAppData%\Microsoft\Windows\Themes folder), which is the theme with the artifact. If you delete this file, then after the bug reappears, it will be created again.

Perfect, this is exactly what I needed.
This appears to be a Windows issue where it doesn't correctly apply the theme.
Please report back whether the "restore themes when changed externally" setting works for you.

**Comment by StereogramStudios** [comment]
I am also having this issue. I do not use themes, just wallpaper switch. It will switch from dark to light mode just fine on its schedule. But light to dark, it switches everything except the wallpapers. I have to open up AutoDarkMode and click a time option for it to trigger the wallpaper.

**Comment by Spiritreader** [comment]
Could you try again with the latest beta? (>=10.2.0.2)

**Comment by Spiritreader** [comment]
Found the origin on Win11 to be theme switching no longer working during lockscreen.
Since 10.3.0.23 theme switching on Win11 can only occur **during** unlock, which allows for proper wallpaper synchronization and theme switching again.
