### ISSUE TITLE
Error occurs while applying settings

### ISSUE THREAD

**Issue by Armin2208** [AutoDarkMode/Windows-Auto-Night-Mode#44]
Some users run into issues while applying their settings. Only an error message is shown and the theme switch can not be enabled.

In Auto Dark Mode **Version 2.3** the error messages got much more detailed. Please post a screenshot of your error message under this issue. Don't forget to add some information about your setup, like Windows version. This helps me to resolve this problem in a future update.

Thank you.

## EDIT:
If you use Windows LTSC or LTSB, [please see this post.](https://github.com/Armin2208/Windows-Auto-Night-Mode/issues/44#issuecomment-517694119)

**Comment by rite2ace** [comment]
![2c063afbf0188c6533f5fbf8a001731c](https://user-images.githubusercontent.com/13923453/61598723-5f1a7f80-ac3f-11e9-8eb4-45768dc1afa7.png)

**Comment by rite2ace** [comment]
![Untitled](https://user-images.githubusercontent.com/13923453/61598923-3b583900-ac41-11e9-976b-1f00fcba3e1b.png)
i am using Win 10 LTSC 2019

**Comment by RaghuJayavardhan** [comment]
![Dark Mode Error](https://user-images.githubusercontent.com/52869095/61632310-28c61a00-acaa-11e9-8dde-3281535a3e78.png)

**Comment by Armin2208** [comment]
> ![Untitled](https://user-images.githubusercontent.com/13923453/61598923-3b583900-ac41-11e9-976b-1f00fcba3e1b.png)
> i am using Win 10 LTSC 2019

LTSC is based on 1809, but you need 1903 to enable system theme switch. Sorry!

**Comment by rite2ace** [comment]
Unlucko, i want to stick with LTSC 2019 for nobloat and how amazing it
feels.

**Comment by RaghuJayavardhan** [comment]
> > ![Untitled](https://user-images.githubusercontent.com/13923453/61598923-3b583900-ac41-11e9-976b-1f00fcba3e1b.png)
> > i am using Win 10 LTSC 2019
> 
> LTSC 2019 is based on 1809, but you need 1903 to enable system theme switch. Sorry!

Next feature update for LTSC is in 2021.

**Comment by Armin2208** [comment]
Hello,

I know why the error occurs on LTSC and I fixed it. But I don't know if I should push this fix to the release version. Because it doesn't make any sense to use Auto Dark Mode on LTSC. It has no advantages (because no Apps). And Explorer switch is buggy on LTSC, they will never fix it, because it's LTSC. 

I still put the installer with the fixed .exe on the attachments of this post. But don't expect a good working file explorer theme switch.
[AutoDarkMode_LTSC_FIX.zip](https://github.com/Armin2208/Windows-Auto-Night-Mode/files/3461349/AutoDarkMode_LTSC_FIX.zip)

**Comment by rite2ace** [comment]
> Hello,
> 
> I know why the error occurs on LTSC and I fixed it. But I don't know if I should push this fix to the release version. Because it doesn't make any sense to use Auto Dark Mode on LTSC. It has no advantages (because no Apps). And Explorer switch is buggy on LTSC, Microsoft will never fix it, because it's LTSC.
> 
> I still put the installer with the fixed .exe on the attachments of this post. But don't expect a good working file explorer theme switch.
> [AutoDarkMode_LTSC_FIX.zip](https://github.com/Armin2208/Windows-Auto-Night-Mode/files/3461349/AutoDarkMode_LTSC_FIX.zip)

Thanks!

**Comment by jsquared71** [comment]
![image](https://user-images.githubusercontent.com/4314939/68219812-a2151e80-ffb4-11e9-8b1d-b787d162cfca.png)
I get the above error when trying to save my settings on Windows 10 20H1 build 19013

**Comment by Armin2208** [comment]
works in 19018 for me

**Comment by Xyrak** [comment]
Have Windows 1909 installed.  The normal release version works with my original user account without problems.   Later added another account which was first as a Standard User, later changed to Admin.  On that 2nd account the release version fail to work with the error message discussed in this thread.  But the fixed version works fine.

**Comment by Armin2208** [comment]
The official version also contains the fix. But it contains different task scheduler name. Maybe it's not possible for 2 user accounts.

Will be fixed in 3.0 anyways.

**Comment by alealclag** [comment]
Hi! There seems to be an error like the ones commented above, but mine only occurs when I use the program in other user, unless I run the program as administrator, even though it already is an administrators accounts. BTW, I use Windows Home.
![Anotación 2020-03-20 201834](https://user-images.githubusercontent.com/43809119/77199178-b895bf80-6ae8-11ea-85ca-5e760704be2c.png)

**Comment by Armin2208** [comment]
> Hi! There seems to be an error like the ones commented above, but mine only occurs when I use the program in other user, unless I run the program as administrator, even though it already is an administrators accounts. BTW, I use Windows Home.

will be fixed in the next 2.4 release

**Comment by alealclag** [comment]
Okey thanks!

**Comment by Armin2208** [comment]
> Okey thanks!

please try the newest beta release

**Comment by alealclag** [comment]
> > Okey thanks!
> 
> please try the newest beta release

It works perfectly! If this were the play store I would give you 5 stars haha

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/85964185-e9ca3980-b9cd-11ea-8036-3be2127b6947.png)
![image](https://user-images.githubusercontent.com/23485114/85964192-f353a180-b9cd-11ea-861b-d179b2fff8a3.png)

**Comment by ToasterDEV** [comment]
![image](https://user-images.githubusercontent.com/5206262/108582798-0f100d00-72fb-11eb-90a1-d3e3fc1c449c.png)
![image](https://user-images.githubusercontent.com/5206262/108582808-1a633880-72fb-11eb-8918-17152465158d.png)

**Comment by Kazanopha** [comment]
I Downloaded the Latest Beta version (AutoDarkMode_v3_0_1)
and the same Error happens 

![Screenshot 2021-03-15 154205](https://user-images.githubusercontent.com/62829169/111155199-3332d700-85a5-11eb-9fba-86c95b6dd809.png)

**Comment by Armin2208** [comment]
> I Downloaded the Latest Beta version (AutoDarkMode_v3_0_1)
> and the same Error happens
> 
> ![Screenshot 2021-03-15 154205](https://user-images.githubusercontent.com/62829169/111155199-3332d700-85a5-11eb-9fba-86c95b6dd809.png)

did you deactivated multi user support in settings?

**Comment by Kazanopha** [comment]
> > I Downloaded the Latest Beta version (AutoDarkMode_v3_0_1)
> > and the same Error happens
> > ![Screenshot 2021-03-15 154205](https://user-images.githubusercontent.com/62829169/111155199-3332d700-85a5-11eb-9fba-86c95b6dd809.png)
> 
> did you deactivated multi user support in settings?

Unfortunately I Couldn't Even Click on it ☹
![Screenshot 2021-03-19 140308](https://user-images.githubusercontent.com/62829169/111770864-03911100-88bc-11eb-9898-421bf8758da2.png)

**Comment by Parth-Mawai** [comment]
![image](https://user-images.githubusercontent.com/76217236/112730698-fb3e7300-8f58-11eb-9280-ed3e5477e865.png)
![image](https://user-images.githubusercontent.com/76217236/112730704-ff6a9080-8f58-11eb-80eb-6e361134fb4c.png)

**Comment by Armin2208** [comment]
I see the problem

**Comment by kamsccssh** [comment]
![image](https://user-images.githubusercontent.com/65874813/117662415-883a3600-b16d-11eb-8fd4-6a58a09186f9.png)

**Comment by pc-v2** [comment]
![image](https://user-images.githubusercontent.com/58063311/125359837-1b256580-e395-11eb-8f26-ba4a53eb14e4.png)
I can't use it with AutoDarkModeXbeta4

**Comment by adamsophian** [comment]
![image](https://user-images.githubusercontent.com/89430072/130537533-11419d5f-e418-4d5b-991c-012985d220ba.png)

I'm on Windows 10 Version 21H1

**Comment by Armin2208** [comment]
> ![image](https://user-images.githubusercontent.com/89430072/130537533-11419d5f-e418-4d5b-991c-012985d220ba.png)
> 
> I'm on Windows 10 Version 21H1

at #112 someone had the same issue and fixed it with a registry tweak. would you try it?

"I went to regedit and i went to [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Schedule] and I changed the "Start" reg file to the value hexadecimal 2, instead of 4. And that solved it."
