### ISSUE TITLE
Postpone automatic theme change 

### ISSUE THREAD

**Issue by test1fy** [AutoDarkMode/Windows-Auto-Night-Mode#441]
Just a small QoL feature: I'd like an option to postpone the theme change by a certain amount of time. 

I've set ADM to switch to light mode at 09:00. When I open my laptop in the morning it's sometimes a bit past 9, so the theme immediately starts changing. This means that if I'm late and in a hurry to do something, like find/write notes, join a Zoom call etc, my computer will lag for about 10 seconds as Windows and all the apps start switching over. I'm not complaining about the lag itself, just that in the instances when I need to do something quickly, I kinda can't..

So in particular I would want to postpone the dark mode -> light mode switch by 5 minutes or so.  I guess the simplest option would postpone all automatic transitions by 5 (or X) minutes. If you want the DM switch to occur at 20:00 you could just adjust it to 19:55. But it could be implemented in many different ways, all of which I'd be happy with, I think.

My sleep schedule is a bit irregular and am not a creature of habit (I have ADHD, lol). On my phone I use tasker to recognize when I first unlock my phone in the morning which will make my smart lights slowly transition to fully lit, and will also switch the phone to light mode after 5 minutes, which is how I got this idea. So when I'm ready to use my computer, my "mental setting" is already "daytime", so I do want it to switch to light mode ASAP, not at say 10 AM. Or rather, I want it to switch after 5 minutes..

Thank you for reading, and for this great tool!

**Comment by tooomm** [comment]
Linking https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/204, where I suggested to have postpone capabilities in a notification that pops up right before the switch accours.

In your example it could be
- Start computer
- Selected schedule is (over)due
- (Instead forcing a switch right away) Notification/Warning/Hint appears that it's about to switch
- Click postpone e.g. 5/15min

**Comment by Spiritreader** [comment]
Also #418

Postponing defintely planned, but no ETA.

**Comment by Spiritreader** [comment]
merging issue with #439

However, the ability to show a notification while unlocking will not make it into ADM, as the unlock behavior is very different between Windows 10 and Windows 11.

**Comment by Spiritreader** [comment]
Good news, I found a way to get this to work after all. Should be available starting with beta 10.0.3.37
