### ISSUE TITLE
Shows theme at incorrect times

### ISSUE THREAD

**Issue by JDMorris81** [AutoDarkMode/Windows-Auto-Night-Mode#442]
I have it set to auto detect my location but it is still setting the dark theme during the day. Note: My system is dual booted and after the dual boot windows also displayed an incorrect time but I have fixed the issue by setting Linux to follow local time. This issue only happens with the newest version. Version 3.0.1 still works as it should.

**Comment by Spiritreader** [comment]
There was a change in ADM where it consistently checks with the system time (usually every few minutes)
If Windows has the wrong system time, ADM will do the right thing and set your preferred time.

There won't really be any changes for this, as there is no bug/issue with the software. It just performs as it is supposed to.

If you still feel like this is a bug, reopen the issue and follow the bug-report template.
Thank you.
