### ISSUE TITLE
Windows Settings'text has the opposite colour than it should have

### ISSUE THREAD

**Issue by DolanD2** [AutoDarkMode/Windows-Auto-Night-Mode#444]
**Description**

When the app changes system theme (from light to dark for example) when i open Windows Settings, the description of the settings has black text instead of white. (and when the app changes from dark to light, the text is white instead of black) 
It goes back to normal after closing and opening Windows Settings again. Yeah, i know this is a very little issue that nobody would care about but i personally do lol

**Expected behavior**

I expeacted the text to have normal colour.

**Log Data**

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8483923/service.log)
I can't attach the .yaml file for some reason

**Commit Hash and Version**

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

**Screenshots**

![image](https://user-images.githubusercontent.com/84463839/163250663-b326ed5f-e7aa-4142-8238-e377225604fa.png)
![image](https://user-images.githubusercontent.com/84463839/163250829-0e1038ab-d12a-4a73-85d7-b0c69ea999ab.png)

**Comment by Armin2208** [comment]
Windows bug, not fixable, was fixed in 11
