### ISSUE TITLE
Auto Dark Mode not being able to instantiate RequestHandler pipes

### ISSUE THREAD

**Issue by iamalexblue** [AutoDarkMode/Windows-Auto-Night-Mode#447]
**Description**

Details about the bug and how to reproduce it
I guess this problem should have appeared a few days ago. As soon as I turn on auto dark mode, the service.log file in "C:\Users\AlexBlue\AppData\Roaming\AutoDarkMode" keeps growing, it already takes up 115 GB of disk space when i found it, and it keeps getting bigger, so I have to kill the app to stop it from getting bigger. 

**Expected behavior**

no longer generates this big boy

**Log Data**

it too big and i can not upload to github. so i share this with googledrive（These files were regenerated when I wrote feedback after deleting the 115 gigabyte log file.）
https://drive.google.com/drive/folders/199w9X_kNzduVEL4aJTWMVtlwdzAyUetB?usp=sharing

**PS**: i set the Windows Task Scheduler for auto dark mode few days ago.

**Commit Hash and Version**

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

**Screenshots**

![image](https://user-images.githubusercontent.com/41639269/164010330-c89c9931-bcc8-48dc-9090-97349db75b75.png)

**Comment by Spiritreader** [comment]
Your system does not have permissions to create interprocess communication between backend and frontend.

If I may ask, what is your windows username?

**Comment by iamalexblue** [comment]
> If I may ask, what is your windows username?
my windows username is AlexBlue.


> Your system does not have permissions to create interprocess communication between backend and frontend.
> It's not really a logging issue per se, but rather the server trying to start indefinitely.

so what i should do?

**Comment by Spiritreader** [comment]
> my windows username is AlexBlue.
Okay, thanks, just wanting to rule out there is an issue with invalid characters.

Could you give me more context on what kind of system this is?
Is this a work/enterprise windows installation or your private one?

**Comment by Spiritreader** [comment]
Since the pipe server isn't working correctly, could you download the lastest beta from here
https://github.com/AutoDarkMode/AutoDarkModeVersion/releases/download/10.1.1.9/ADM.zip
and just overwrite all files in your existing installation?

I've rate limited the worker creation in this build.
Please delete the existing log files and re-upload the new log it generates. It should be a bit more readable what's going on.

Also, did you install ADM using the "for all users" or the "for current user" mode?

**Comment by iamalexblue** [comment]
> Also, did you install ADM using the "for all users" or the "for current user" mode?

Emmm, i forgot it, sorry. and i just uninstall the old version after this occured.



> Since the pipe server isn't working correctly, could you download the lastest beta from here
> https://github.com/AutoDarkMode/AutoDarkModeVersion/releases/download/10.1.1.9/ADM.zip
> and just overwrite all files in your existing installation?

I download the new version, it seems a portable version? i just unzip it and service.log file looks good.

**Comment by Spiritreader** [comment]
> > Also, did you install ADM using the "for all users" or the "for current user" mode?
> 
> Emmm, i forgot it, sorry. and i just uninstall the old version after this occured.
> 
> > Since the pipe server isn't working correctly, could you download the lastest beta from here
> > https://github.com/AutoDarkMode/AutoDarkModeVersion/releases/download/10.1.1.9/ADM.zip
> > and just overwrite all files in your existing installation?
> 
> I download the new version, it seems a portable version? i just unzip it and service.log file looks good.

yep, that one is portable.
Could you upload the log file?

**Comment by iamalexblue** [comment]
> Could you upload the log file?
> 
> The issue is very likely still there, it just no longer spams the log file.

okay, hope it can help and thank you for your patience.

https://drive.google.com/drive/folders/1-Ff7dS1jmN3YS5IF2ybV4Rbq8CfiLyXG?usp=sharing

**Comment by iamalexblue** [comment]
> Also, looking at your logfiles revealed that raw.github.com seems to be blocked in your country, as such you can always use this link to update to the lastest version if desired.

ahhhhh yess i live in china, GitHub is almost blocked  there, but i can update and download ADM by proxy. So it fine

i also appreciate your professionalism and fast response.

**Comment by Spiritreader** [comment]
Nothing came up regarding this issue, closing because stale. If anyone still has this problem, please feel free to re-open.
