### ISSUE TITLE
Fade between wallpapers

### ISSUE THREAD

**Issue by Dr747** [AutoDarkMode/Windows-Auto-Night-Mode#450]
Hi there, 
I would enjoy the change between wallpapers being smoother, using a 1 second fade for example. WinDynamicDesktop does so for example and it makes using day and night variants of the same wallpaper a bit more enjoyable.
Thanks!

**Comment by Spiritreader** [comment]
Sadly this requires using a different WindowsAPI that we currently have no plans on supporting.
Thank you for the suggestion tho!

**Comment by Dr747** [comment]
I had thought that might be the case, thanks for your response nonetheless
