### ISSUE TITLE
Auto night mode in  windows IME.

### ISSUE THREAD

**Issue by JamYiz** [AutoDarkMode/Windows-Auto-Night-Mode#451]
**Describe the enhancement or feature you'd like**

Win11 can change the input method theme, maybe automatically switch dark mode
**Describe alternatives you've considered**

**Additional context**

**Comment by JingBh** [comment]
**I might know how to solve this.**

I'm using Windows 11 version 22621.169, in the personalization settings, there are many themes for the IME, like the ones in the screenshot:
![image](https://user-images.githubusercontent.com/26338708/178218775-bb28dcc6-48a9-4eda-a224-440d418dcbaf.png)
*(sorry if the Chinese UI is confusing)*

The default behaviour is to automatically switch between light and dark upon theme change, but if we manually select one of them, then Windows will not change it anymore even if system color theme changes, and there is obviously no way to undo this on the UI.

So I dig a little deeper into this, and found that this setting is stored at `HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7` in the registry. To restore the default behavior, which is to switch IME theme automatically, you just need to delete this entry manually.

**Comment by JingBh** [comment]
Also a friendly Chinese version for the author @JamYiz :
我今天也遇到这个问题了，研究了一下发现应该是 Windows 的 bug，在注册表里删掉 `HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7` 就能自动切换啦~

**Comment by Spiritreader** [comment]
> **I might know how to solve this.**
> 
> I'm using Windows 11 version 22621.169, in the personalization settings, there are many themes for the IME, like the ones in the screenshot: ![image](https://user-images.githubusercontent.com/26338708/178218775-bb28dcc6-48a9-4eda-a224-440d418dcbaf.png) _(sorry if the Chinese UI is confusing)_
> 
> The default behaviour is to automatically switch between light and dark upon theme change, but if we manually select one of them, then Windows will not change it anymore even if system color theme changes, and there is obviously no way to undo this on the UI.
> 
> So I dig a little deeper into this, and found that this setting is stored at `HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7` in the registry. To restore the default behavior, which is to switch IME theme automatically, you just need to delete this entry manually.

So essentially the IME color can be changed by modifying a registry key?
Does the keyboard has to be re-opened or do the changes made to the regkey take effect immediately?

**Comment by JingBh** [comment]
@Spiritreader

> So essentially the IME color can be changed by modifying a registry key?

No it's not a single key, but a quite complex structure.
![image](https://user-images.githubusercontent.com/26338708/178272923-72092a79-d041-4baf-ac8a-b250c702d151.png)
Inside `SelectedThemeDark` and `SelectedThemeLight` is something like this:
![image](https://user-images.githubusercontent.com/26338708/178273126-c4325b1c-f0bd-485f-9d5f-bdda217893d6.png)

So I actually don't know which key effects what. All I managed to figure out is that deleting the whole folder restores the default behavior.

btw I'm also not sure if this is the only place where Windows places the IME theme settings.

> Does the keyboard has to be re-opened or do the changes made to the regkey take effect immediately?

From what I can tell:

1. Making changes in the settings app takes effect immediately. So I **guess** making changes directly to the registry also takes effect immediately.

2. If we delete the whole folder like mentioned above, the theme setting won't work anymore until the computer restarts, during which the IME theme will always be synced with the system theme no matter what you choose in the settings app.

**Comment by Spiritreader** [comment]
> Making changes in the settings app takes effect immediately. So I guess making changes directly to the registry also takes effect immediately.

There is sadly an asymmetry with this behavior starting with Windows 11.
Microsoft has introduced new unpublished APIs that are invoked in the control panel, but aren't availalbe to us, which caused (and causes) huge headaches in making even the theme switch work correctly in Win 11.


> If we delete the whole folder like mentioned above, the theme setting won't work anymore until the computer restarts, during which the IME theme will always be synced with the system theme no matter what you choose in the settings app.

If deleting the folder causes the IME themes to break until restart, I think it's a nonviable solution to integrate into dark mode.
At least it's not stored as binary like the night light settings...

Thanks for investigating this tho, we'll monitor it and hopefully at some point there's a way to integrate this seamlessly

**Comment by JingBh** [comment]
Anyway I don't think Auto Dark Mode needs this feature, as the default behavior of the IME is to sync with system theme, which is exactly how this is expected to be. For now, as long as you don't touch the setting, it's fine, and hopefully Microsoft comes up with a "Follow system theme" option.

**Comment by Armin2208** [comment]
Did Microsoft really just removed "follow system theme" for keyboard, emoji panel and IME?
It was there in Windows 11 relesae version...
![image](https://user-images.githubusercontent.com/32982430/179427060-3f88c7c7-bfd8-4c10-8870-8f154954acc1.png)

**Comment by Armin2208** [comment]
thanks for providing the registry keys. we can fix this.

**Comment by JingBh** [comment]
> Did Microsoft really just removed "follow system theme" for keyboard, emoji panel and IME?
It was there in Windows 11 relesase version...

I have been using version 22H2 for a while so I didn't notice that... Now this is absolutely Microsoft's fault.
