### ISSUE TITLE
Custom script took too long to complete and had to be stopped

### ISSUE THREAD

**Issue by Tizoner** [AutoDarkMode/Windows-Auto-Night-Mode#452]
### Question
Why `TimeoutMillis` from `scripts.yaml` is not being used in the [AutoDarkModeSvc/Handlers/ScriptHandler.cs](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/blob/52659d4bb5d0e9f08c7231cab69cbbda05c82b7c/AutoDarkModeSvc/Handlers/ScriptHandler.cs)?
![image](https://user-images.githubusercontent.com/40523001/166910110-6c749c9a-7264-4e31-85f5-19c08ad40996.png)
According to the `service.log`, custom script just does not have enough time to execute after reboot/sign out.

**Comment by Spiritreader** [comment]
Very good question. 
I've fixed the issue, and also changed the timout behavior.
Timeouts now need to be set on a per-script basis.
This allows us to adjust the base value as needed, and also gives users better individual control over script maximum runtimes.

**Comment by Tizoner** [comment]
It works, thank you!🎉
