### ISSUE TITLE
Auto dark mode must restart in Windows 11 Pro 22610.1 for normal

### ISSUE THREAD

**Issue by Backnumber-Liu** [AutoDarkMode/Windows-Auto-Night-Mode#453]
### Question

Since I updated in the beta channel,the taskbar can't switch modes automatically,the computer will have to reboot to get back to normal.I would like to ask if this is a Microsoft problem or a plugin（auto dark mode）problem？

**Comment by Armin2208** [comment]
a issue created by Microsoft. Please fill a Feedback Hub Issue on Windows that Auto Dark Mode doesn't switch the theme anymore. thanks
