### ISSUE TITLE
Wallpaper switches back when switching desktops

### ISSUE THREAD

**Issue by GeorgeSQiao** [AutoDarkMode/Windows-Auto-Night-Mode#454]
Basically every time when I try to switch desktops on my laptop in dark mode the wallpaper for the main desktop jumps back to the light version, but everything else remains the same. Updated to the Beta version and the problem still occurs. It has been bugging me for the last few months, hope that the wallpaper could stay the same after I switch desktops & not only the wallpaper for main desktop will have dark mode.

**Log Data**
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8637320/service.log)
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8637318/config.zip)

**Commit Hash and Version**

- Commit: `4bd2d25`
- Service: `10.1.1.12`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.1`

Currently using a Surface Pro 8 (i5-1135G7) and Windows 11 (22000.652)

**Comment by Spiritreader** [comment]
Could you specify what you mean with "switching desktops"

Are you referring to switching virtual desktops?

**Comment by GeorgeSQiao** [comment]
Yes, switching virtual desktops, sorry about the confusion. 


发件人: Sam
发送时间: 2022年5月7日 06:43
收件人: AutoDarkMode/Windows-Auto-Night-Mode
抄送: GeorgeSQiao; Author
主题: Re: [AutoDarkMode/Windows-Auto-Night-Mode] Wallpaper switches backwhen switching desktops (Issue #454)

Could you specify what you mean with "switching desktops"
Are you referring to switching virtual desktops?

**Comment by Spiritreader** [comment]
Hmm that's quite interesting. Do you often plug/unplug external monitors?

**Comment by castillohair** [comment]
This happens to me as well.

I use an external monitor but I was able to reproduce the issue even without one.

**Comment by Jaskejaske1** [comment]
This also happens to me. Although I am currently using an external monitor, the problem persists without it being connected.

**Comment by tp-duarte** [comment]
Yeah, I'm identifying the same problem here. I t would be awesome to solve this issue.

**Comment by Spiritreader** [comment]
We're aware of this issue on single-monitor systems that use VDesktops.

We're waiting for info to come out on the 22H2 API so we can use this very nice wrapperhttps://github.com/Grabacr07/VirtualDesktop that is available as a nuget package.

**Comment by GeorgeSQiao** [comment]
It’s not actual monitors, it is when you switch desktops under task view in Win 10/11.


发件人: Sam
发送时间: 2022年5月11日 19:46
收件人: AutoDarkMode/Windows-Auto-Night-Mode
抄送: GeorgeSQiao; Author
主题: Re: [AutoDarkMode/Windows-Auto-Night-Mode] Wallpaper switches backwhen switching desktops (Issue #454)

Hmm that's quite interesting. Do you often plug/unplug external monitors?

**Comment by Spiritreader** [comment]
merge with #469, is same issue
