### ISSUE TITLE
A word in chinese translate may cause an ambiguity

### ISSUE THREAD

**Issue by GVD20** [AutoDarkMode/Windows-Auto-Night-Mode#457]
![01](https://user-images.githubusercontent.com/75466651/168421284-1dd6ec8c-9741-48cb-9712-0f18677b8617.png)
![02](https://user-images.githubusercontent.com/75466651/168421285-cc54088e-0aaa-4cc1-83b3-72bedfd6b51d.png)
The option _”Adapt to System“_, translated into _”跟随系统“_，may make users consider the _”system“_ as the ”operating system (windows)“ instead of the true “Auto-Dark-Mode's timing system”.
this misunderstanding can cause seriously mistakes.
My suggestion is to change it into _"自动切换"_.

**Comment by Spiritreader** [comment]
Hmm good point.
That is even an ambiguity in English, because the same issue applies.

It might be a good idea to change the "Adapt to system" string to "Automatic"

**Comment by qNwNp** [comment]
> 

simplified

**Comment by Spiritreader** [comment]
done, thanks!
