### ISSUE TITLE
latest beta version the theme makes any changes, after minutes always automatically restore users settings preferences themes

### ISSUE THREAD

**Issue by chuck00000** [AutoDarkMode/Windows-Auto-Night-Mode#462]
![image](https://user-images.githubusercontent.com/98159699/169790862-2e561932-9576-4bce-8baf-d47f782d9256.png)
Even though "Restore themes when changed externally " Option is not selected, the program detected themes has any changes, after minutes always automatically restore users settings preferences themes,it's very annoying!

**Comment by Spiritreader** [comment]
There's generally no need to write things like "it's very annoying" in a free support inquiry, while simultaneously doing the same and not filling out the bug report template properly.

I'll look into it, but due to lack of information, we can't do anything.

**Comment by Spiritreader** [comment]
Should be fixed now!
There were still some leftovers from experimenting with theme synchronization that  turned the setting on permanently.

**Comment by Spiritreader** [comment]
Closing (no updates)
