### ISSUE TITLE
Number Count Dark

### ISSUE THREAD

**Issue by stevefxp1** [AutoDarkMode/Windows-Auto-Night-Mode#463]
### Description

Number count in Chrome is too dark to read.

### Expected Behavior

When in dark mode the number should default to a white background with dark numbers.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8783079/service.log)

### Operating System

Windows 11 21H2

### Commit Hash and Version

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

### Screenshots

![Screenshot 2022-05-26 203419](https://user-images.githubusercontent.com/70986226/170605985-7beff65f-77ff-481b-aa34-ed8d58359194.png)

**Comment by Armin2208** [comment]
this is something we can't fix, because it's a chrome issue I  guess. Or something is wrong with your chrome theme.
