### ISSUE TITLE
In Windows 11, the message at the lower right corner of the taskbar remains the same color

### ISSUE THREAD

**Issue by Emisaka123** [AutoDarkMode/Windows-Auto-Night-Mode#467]
### Description

In Windows 11, the message at the lower right corner of the taskbar remains the same color
![image](https://user-images.githubusercontent.com/74747045/173354685-56e786e3-c538-4937-9b33-d22b09a2dedb.png)
windows 11 ：22621.1 ni_release
![image](https://user-images.githubusercontent.com/74747045/173354883-17884666-0795-45dc-9e8a-9d58e3714029.png)
The bottom right corner is completely black

### Expected Behavior

In Windows 11, the message at the lower right corner of the taskbar remains the same color
![image](https://user-images.githubusercontent.com/74747045/173354685-56e786e3-c538-4937-9b33-d22b09a2dedb.png)
windows 11 ：22621.1 ni_release
![image](https://user-images.githubusercontent.com/74747045/173354883-17884666-0795-45dc-9e8a-9d58e3714029.png)
The bottom right corner is completely black

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8891063/service.log)
[config .txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8891076/config.txt)

### Operating System

window11

### Commit Hash and Version

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

### Screenshots

![image](https://user-images.githubusercontent.com/74747045/173354883-17884666-0795-45dc-9e8a-9d58e3714029.png)

**Comment by Emisaka123** [comment]
The dark mode looks less dark because I turned on transparent mode, but this is not the cause of the bug, even without transparent mode, the font color in the lower right corner is still the same as the theme color, so it is not recognizable

**Comment by Spiritreader** [comment]
Please update to latest beta

**Comment by Spiritreader** [comment]
I was able to find a workaround for this.
