### ISSUE TITLE
Auto Dark Mode stopped switching modes

### ISSUE THREAD

**Issue by kazerniel** [AutoDarkMode/Windows-Auto-Night-Mode#472]
### Description

As of today, Auto Dark Mode stopped being able to switch modes. First I noticed that it didn't automatically switch to Light mode when I started the PC during daytime, but the forced mode switches don't seem to work either. Tried restarting my PC, or switching Time modes in ADM, still nothing.

### Expected Behavior

To keep switching automatically, like it's been doing since I installed it 5 days ago.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8927427/service.log)
[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8927467/config.yaml.txt)
(GitHub doesn't let me upload a yaml file.)

### Operating System

Windows 10.0.17763 Build 17763

### Commit Hash and Version

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

**Comment by Spiritreader** [comment]
Hmm, I can't really see what's wrong.
ADM is not reporting any errors, so the theme switching directives get correctly passed on to Windows.

Have you tried updating to the latest Win10 build and using the ADM beta?

**Comment by kazerniel** [comment]
Ok, it seems like a Windows issue, my theme is indeed Light, but my taskbar is stuck in dark mode O.o
