### ISSUE TITLE
The right click options icons are not changing color

### ISSUE THREAD

**Issue by kevinjn0123** [AutoDarkMode/Windows-Auto-Night-Mode#475]
### Description

The right click options icons are not changing color

### Expected Behavior

The right click options icons should be in their respective color when the dark mode turns on/off

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8975681/service.log)
[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8975687/config.yaml.txt)

### Operating System

Version=22H2, OS build=22621.160

### Commit Hash and Version

- Commit: `3b0e556`
- Service: `10.2.0.9`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.1`

### Screenshots

![image](https://user-images.githubusercontent.com/82707769/175522654-d820e884-9415-4deb-b808-b5e7556d2ca0.png)

**Comment by Armin2208** [comment]
the only answer i can give you is: wtf is microsoft doing

**Comment by HRiver2** [comment]
same problem
may what we could do is waiting MS to fix his bugs.

**Comment by Spiritreader** [comment]
Yes, nothing we can do to fix/work around this.
Our latest fixes address inconsistent theme switching as best as possible, but we can't do more than that.
Hope that helps.
