### ISSUE TITLE
Beep noise when switching themes

### ISSUE THREAD

**Issue by leodoi3** [AutoDarkMode/Windows-Auto-Night-Mode#480]
I hear a beep sound when the themes switch.  Anyone know what it is?

**Comment by Spiritreader** [comment]
It looks like your computer is unable to handle the theme switch.
On some machines theme switching is more expensive than on others, which can cause the system to hang intermittently.
While the system is busy, inputs can get queued up, which can cause the beep you're describing and temporary unresponsiveness of your peripherals.

**Comment by leodoi3** [comment]
I have a recent modern system and I am using a wired keyboard and mouse, so I don't think it could be the issue. I didn't notice any lag with the mouse while theme switcher is running.

**Comment by Spiritreader** [comment]
How modern the system is seems to have no impact on this.
I also have a modern system and switching is a nightmare on it, whereas it's butter smooth on my laptop.

The mentioned beeping issue can occur with all hardware, but as I mentioned is just amplified on wireless devices.
In any case, it doesn't look like there's anything we can do really.

ADM only uses Windows APIs to change the theme, so it's most likely an issue with Windows and your specific HW combination.
