### ISSUE TITLE
Unable to switch wallpaper in the latest beta

### ISSUE THREAD

**Issue by willamettefour** [AutoDarkMode/Windows-Auto-Night-Mode#483]
### Description

After updating to the latest beta, wallpaper switch can't change the wallpaper from what was set either before the update or before it was enabled. This doesn't appear to be an issue in the stable version.

### Expected Behavior

Wallpaper changes to the one set when the theme is changed.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9051760/service.log)
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9051873/config.zip)

### Operating System

Windows 11 Build 22621.169

### Commit Hash and Version

- Commit: 68dd91a
- Service: `10.2.0.16`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.1`

### Screenshots

![behavior](https://user-images.githubusercontent.com/94886283/177475919-e5a9a14c-2024-46d8-bb9f-1107cf3b441b.gif)

**Comment by Spiritreader** [comment]
can reproduce this, it's most likely a synchronization issue, will take a look

**Comment by Spiritreader** [comment]
Please check out beta 10.2.0.17, should hopefully fix this.
Thanks for the detailed bug report, helped a lot in getting to the bottom of it quickly!

**Comment by Armin2208** [comment]
@willamettefour could you please answer to this issue, if your issue was released with latest beta release?

**Comment by willamettefour** [comment]
It's been fixed as far as I can tell

**Comment by Armin2208** [comment]
Hey @EvanOneCH, maybe you could also switch to Beta and try if your issue was solved?

**Comment by EvanOneCH** [comment]
Thanks @Armin2208, my problem has been worked out after updating to Beta.

**Comment by Armin2208** [comment]
@Spiritreader this is the proof beta works better than stable now 😂
