### ISSUE TITLE
Turn back to light more when back to plugged in?

### ISSUE THREAD

**Issue by jamie9090** [AutoDarkMode/Windows-Auto-Night-Mode#485]
Right now switching to dark mode works when unplugging laptop, but would love to go back to light mode (or normal timed settings) when plugging back in!

**Comment by Spiritreader** [comment]
The way you describe it is how it's supposed to work

**Comment by jamie9090** [comment]
Seems to be working now, will report back if that changes - but AWESOME.

**Comment by jamie9090** [comment]
Ok, issue has re-appeared. On reboot, it worked, but then it stopped correctly triggering shortly after.  It doesn't seem to correctly recognized whether the laptop is on battery, or plugged in. 

I imagine I can fix it after rebooting, but would prefer not do that each time.  I'm on a 2021 Asus Vivobook Pro. 

Anyone have any ideas?

**Comment by jamie9090** [comment]
Cheers!
