### ISSUE TITLE
Windows 11 system taskbar theme conversion meanwhile time etc do not convert colors

### ISSUE THREAD

**Issue by huiqiang233** [AutoDarkMode/Windows-Auto-Night-Mode#488]
### Description

Windows 11 system taskbar theme conversion meanwhile time etc do not convert colors.
However, after I restarted the explorer on the task manager, it returned to normal, but whenever the Auto Dark Mode converted the theme after the time was not displayed, I needed to manually restart the explorer every time.
This caused me a lot of trouble.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9146253/service.log)
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9146258/config.zip)

### Operating System

Windows 11 22621.232

### Commit Hash and Version

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

### Screenshots
![QQ截图20220720112126](https://user-images.githubusercontent.com/20625373/179890865-c05baed2-a045-4da6-9176-969fca56cbee.png)
![QQ截图20220720112344](https://user-images.githubusercontent.com/20625373/179890876-b5ee278b-5da3-4658-8b20-f97c57cd35dc.png)

**Comment by Spiritreader** [comment]
Known issue and duplicate, please check here for more info and workarounds https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/424
