### ISSUE TITLE
Themes option does not switch between wallpapers.

### ISSUE THREAD

**Issue by theDebonair** [AutoDarkMode/Windows-Auto-Night-Mode#491]
### Description

ADM's Theme option under the Personalization tab does not switch wallpaper according to the theme. This problem occurs most of the time. Also, the system freezes during the switch for some seconds. My PC's specs are Ryzen 5 2500U, 16 GB DDR4 RAM, 256 GB M.2 SSD + 1 TB HDD. I've installed ADM in my SSD. Please do some optimization.
Just found another bug while posting this issue. While copying version info via the copy button in ADM, the app gets crashed.
Thanks!

### Expected Behavior

ADM should switch wallpaper according to the theme.

### Log Data

[AutoDarkMode.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9229000/AutoDarkMode.zip)

### Operating System

Windows 11 Pro 21H2 22000.795

### Commit Hash and Version

Commit: 5e6ea8a
Service: 10.1.0.10
Updater: 2.4.2
App: 10.0.1.0
Shell: 1.3.1.0
.Net: 6.0.0

### Screenshots

![image](https://user-images.githubusercontent.com/51323434/182029939-23f5e6f8-4a20-4c59-bc19-d202fa0f0603.png)
Can't show the screenshot of the theme issue as I manually changed the wallpaper.

**Comment by Spiritreader** [comment]
can you try with the latest beta version?

**Comment by theDebonair** [comment]
I'll mention here if I tried the latest beta.

**Comment by carlosvsilva** [comment]
I have started to notice this major bug only after upgrade from Windows 11 21H2 to 22H2 latest Release Preview. Switching to Dark Theme is nearly instantaneous, but latest Windows Version 10.0.22621.382 forgets to change the wallpaper on all other virtual desktops, other than the current one in use.

I've reported the Windows bug (happens even when switching from Windows Settings) to Microsoft which breaks theming, and Auto Dark Mode, but the September 20th release date is fast approaching and the bug report remains unacknowledged (?).
The only way to workaround this, is by going to every individual virtual desktop, open Windows Settings and click Personalization. Only then Windows changes the wallpaper to match the current theme.

If you want to help upvote the bug report, it's here:

https://aka.ms/AAhmoj9

Thanks!

**Comment by aislend** [comment]
> I have started to notice this major bug only after upgrade from Windows 11 21H2 to 22H2 latest Release Preview. Switching to Dark Theme is nearly instantaneous, but latest Windows Version 10.0.22621.382 forgets to change the wallpaper on all other virtual desktops, other than the current one in use.
> 
> I've reported the Windows bug (happens even when switching from Windows Settings) to Microsoft which breaks theming, and Auto Dark Mode, but the September 20th release date is fast approaching and the bug report remains unacknowledged (?). The only way to workaround this, is by going to every individual virtual desktop, open Windows Settings and click Personalization. Only then Windows changes the wallpaper to match the current theme.
> 
> If you want to help upvote the bug report, it's here:
> 
> https://aka.ms/AAhmoj9
> 
> Thanks!

I have the same problem with the wallpaper not switching, it only happens after the PC wakes up from hibernation.
I tried restarting Windows File Explorer and it works fine. Switching themes manually from Windows Settings also works fine.

ADM has been updated to the latest beta version.
My OS: Windows 10 Home 21H2 19044.1889

Could this be a problem with ADM, or should I wait for Windows to fix it? Since I don't use virtual desktops, the bug you mentioned seems to be different from mine

**Comment by theDebonair** [comment]
> I have started to notice this major bug only after upgrade from Windows 11 21H2 to 22H2 latest Release Preview. Switching to Dark Theme is nearly instantaneous, but latest Windows Version 10.0.22621.382 forgets to change the wallpaper on all other virtual desktops, other than the current one in use.
> 
> I've reported the Windows bug (happens even when switching from Windows Settings) to Microsoft which breaks theming, and Auto Dark Mode, but the September 20th release date is fast approaching and the bug report remains unacknowledged (?).
> The only way to workaround this, is by going to every individual virtual desktop, open Windows Settings and click Personalization. Only then Windows changes the wallpaper to match the current theme.
> 
> If you want to help upvote the bug report, it's here:
> 
> https://aka.ms/AAhmoj9
> 
> Thanks!
> 
>  

Yea, I've to manually switch wallpaper everytime.

**Comment by Spiritreader** [comment]
Anything that changes in future windows builds is out of our hands.

If it doesn't end up working in the next stable w11 build we'll most likely have to retire ADM from those builds and mark it as unsupported.

Please everyone, be patient and wait for the final build, supporting insider is and way never really feasible.

**Comment by Spiritreader** [comment]
10.2 is out, please retry

**Comment by Ririshi** [comment]
Just booted my PC running W11 (Education) 21H2 22000.978 this morning with ADM version info below, and my wallpaper is not changing on inactive virtual desktops. Only started using virtual desktops recently after a long time, so I can't say if that was already an issue, or if it only just broke, but  I can confirm the newest (release) version of ADM doesn't seem to have fixed it.

- Commit: `f7a700b`
- Service: `10.2.0.18`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.7`

**Comment by Spiritreader** [comment]
10.3 should address most of the wallpaper/theme switching issues. Please see the list of known limitations: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Known-limitations

If none of these conditions apply. feel free to re-open and please provide some more instrucitons on how to reproduce.
