### ISSUE TITLE
Accent color on Titlebars and window borders toggle

### ISSUE THREAD

**Issue by LordEndor** [AutoDarkMode/Windows-Auto-Night-Mode#499]
**Describe the enhancement or feature you'd like**

Hey,
I like too have black Title bars in dark mode, would i be possible to add a toggle for that as you do for accent color on taskbar?

**Comment by Spiritreader** [comment]
Hi,
thanks for the suggestion!

Duplicate of https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/246

ATM we unfortunately have no plans of implementing this as there are multiple issues with refreshing explorer correctly to get this to work properly.
