### ISSUE TITLE
[Feature request] Switching between 2 modes with hotkey(s)

### ISSUE THREAD

**Issue by hohoaisan** [AutoDarkMode/Windows-Auto-Night-Mode#5]
I think this app need have user-manual hotkeys for switching "Windows" and "Apps" between 2 modes or both of it at the same time

**Comment by Armin2208** [comment]
I also had the nice idea. But the App would need a background task to do so.

**Comment by Armin2208** [comment]
Hello,

I released a new version of Auto-Night Mode. Version 2.0 introduces fast theme switching with the program Jump-List. So you can pin the program to your start screen or to the taskbar, and then right click on it to switch the theme. 

This solution is much easier & resource-saving than a global hotkey. I hope you like it!

[Click here to download the new version](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases)

**Comment by Armin2208** [comment]
Version 2.0 is now out of beta. It includes this feature and more enhancements. Thank you for your feedback.

**Comment by rquellet** [comment]
Another solution is to define a shortcut to the AutoDarkMode.exe with a command line argument of "/dark" or "/light". Then define a global keyboard shortcut to launch this shortcut.

Here's an example shortcut:
![image](https://user-images.githubusercontent.com/7592586/58397351-8af1fe00-801e-11e9-9a82-72b477619ae3.png)

It'd be nice if there was a "/toggle" command line argument so I can define only one shortcut instead of two. Here's the code to add to App.xaml.cs:
```
                    else if(value == "/toggle")
                    {
                        RegEditHandler regEditHandler = new RegEditHandler();
                        if (regEditHandler.SystemUsesLightTheme())
                            regEditHandler.ThemeToDark();
                        else
                            regEditHandler.ThemeToLight();
                    }
```

**Comment by aderchox** [comment]
> Hello,
> 
> I released a new version of Auto-Night Mode. Version 2.0 introduces fast theme switching with the program Jump-List. So you can pin the program to your start screen or to the taskbar, and then right click on it to switch the theme.
> 
> This solution is much easier & resource-saving than a global hotkey. I hope you like it!
> 
> [Click here to download the new version](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases)

This seems to be the best solution so far. I've pinned it to my Start menu and it works. But I still wish to have this keyboard shortcut as well, hopefully at some point. There ARE already [apps](https://www.wintools.info/index.php/easy-dark-mode) that can help with this but I don't want to install two different apps for achieving one goal.
Thank you ✨.

**Comment by Spiritreader** [comment]
> > Hello,
> > I released a new version of Auto-Night Mode. Version 2.0 introduces fast theme switching with the program Jump-List. So you can pin the program to your start screen or to the taskbar, and then right click on it to switch the theme.
> > This solution is much easier & resource-saving than a global hotkey. I hope you like it!
> > [Click here to download the new version](https://github.com/Armin2208/Windows-Auto-Night-Mode/releases)
> 
> This seems to be the best solution so far. I've pinned it to my Start menu and it works. But I still wish to have this keyboard shortcut as well, hopefully at some point. There ARE already [apps](https://www.wintools.info/index.php/easy-dark-mode) that can help with this but I don't want to install two different apps for achieving one goal. Thank you ✨.

Global hotkeys are very high on our priority list.
The next major feature release will not launch without it.

**Comment by Spiritreader** [comment]
![hotkeys](https://user-images.githubusercontent.com/18438899/140660225-86000722-02ba-4878-b778-29faf2c3721b.gif)

It's done.
