### ISSUE TITLE
Installation through winget

### ISSUE THREAD

**Issue by larsschellhas** [AutoDarkMode/Windows-Auto-Night-Mode#517]
### Could you add installation instructions?
These could include a link to the windows store as well as the command for winget :)

**Comment by Spiritreader** [comment]
We already have this in our readme
![image](https://user-images.githubusercontent.com/18438899/193255264-02afdff3-14f5-4196-9343-0bcf2c755892.png)

**Comment by larsschellhas** [comment]
Sorry, must have overlooked that.

**Comment by yllekz** [comment]
Hi folks, this appears to have been scrubbed from the docs + it's not in winget. Can this be reviewed again?

**Comment by Armin2208** [comment]
Check readme "Even more download options"
