### ISSUE TITLE
Change cursor theme when "windows theme" changes(automatically).

### ISSUE THREAD

**Issue by ghost** [AutoDarkMode/Windows-Auto-Night-Mode#522]
# What is this feature? 
Change cursor theme when "windows theme" changes(automatically).
# How the feature should work?
windows changes to dark mode(there is alot of application that does this). cursor changes it's theme from light to dark for example
# You have examples or an idea of how it can be implemented?

**Comment by Spiritreader** [comment]
This is planned eventually, we just need to find someone to create a UI for it.
you can already change the cursor by using Windows theme mode, individual control is not there yet tho.

**Comment by RobertChou** [comment]
> 

may I ask when did this feature will realease？

**Comment by Spiritreader** [comment]
> > 
> 
> may I ask when did this feature will realease？

When it's done.

**Comment by Spiritreader** [comment]
added in 10.3.0.50
