### ISSUE TITLE
Change user profile picture when "windows theme" changes(automatically).

### ISSUE THREAD

**Issue by direrFlood** [AutoDarkMode/Windows-Auto-Night-Mode#523]
# What is this feature? 
Change user profile picture when "windows theme" changes(automatically).
# How the feature should work?
windows changes to dark mode(there is alot of application that does this). profile picture changes from light to dark for example
# You have examples or an idea of how it can be implemented?

**Comment by Spiritreader** [comment]
Hi, currently there are no plans to implement changing the user picture from our side, but if someone wants to create a PR making a [component](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Adding-a-new-component) we'd happily take a look at integrating it

**Comment by Armin2208** [comment]
I don't like the idea and I don't think it adds value to Auto Dark Mode
