### ISSUE TITLE
Installation from Windows Store fails

### ISSUE THREAD

**Issue by l0drex** [AutoDarkMode/Windows-Auto-Night-Mode#526]
I tried to install this from the Windows Store, but the installation always fails with Code: 0x87AF0001. 

Windows Info:
```
Edition	Windows 11 Home
Version	22H2
Operating system build	22621.521
Performance	Windows Feature Experience Pack 1000.22634.1000.0
```

**Comment by Spiritreader** [comment]
This is an issue with the Microsoft Store, please try again later.
There's nothing we can do, we just provide the installer to MS and nothin ghas changed in that regard recently
