### ISSUE TITLE
AutoDarkMode causes flickering windows and scrolling issues in Windows Explorer

### ISSUE THREAD

**Issue by BallistiX09** [AutoDarkMode/Windows-Auto-Night-Mode#528]
### Description

For the past week or so roughly, I've been having issues where at some point during the day (I don't think it's related to day/night switching times) I'll have flickering and scrolling issues throughout the PC, most noticeably in Windows Explorer. A few examples I've noticed the issue in are:

- Notification area icons flickering
- Windows explorer window content flickering
- Windows explorer window constantly scrolling to the top of the folder
- Windows services screen heavily flickering

Quitting out of AutoDarkMode doesn't seem to fix the issue as far as I've experienced. The only way I've managed to get the issue to stop is by going into Task Manager and ending the AutoDarkModeSvc.exe process (which seems to stay open even after quitting the program).

### Expected Behavior

AutoDarkMode shouldn't cause any glitching in Windows Explorer or other programs.

### Log Data

Config.yaml had to be switched to config.txt because GitHub wouldn't allow a .yaml upload.

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9717652/service.log)
[config.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9717656/config.txt)

### Operating System

Windows 11 (22H2, 22622.440)

### Commit Hash and Version

- Commit: `038c1b7`
- Service: `10.3.0.10`
- Updater: `2.5.0`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.7`

**Comment by Spiritreader** [comment]
Is a bug with Windows theme switching, please file an issue with Microsoft's own feedback hub
