### ISSUE TITLE
Option to wait to change until idle

### ISSUE THREAD

**Issue by b-** [AutoDarkMode/Windows-Auto-Night-Mode#529]
One thing I thought was particularly interesting about the way iOS does automatic dark mode is that it waits for activity to become idle before switching, to prevent disrupting the user.

In other words, if my phone is going to switch to dark mode at 5:45, and I'm reading a website at 5:45, my phone will remain in light mode until locked, and then will be in dark mode upon unlock.

This by no means should be something on by default. Rather, it should be hidden behind a toggle or whatnot if it's added at all.

But upon seeing that this utility will optionally wait until you're done playing a full screen game, that got me thinking that this could be useful/nice. I do appreciate not having a transition in the middle of my work.

I'm not sure if it would help in and of itself, but Windows Task Scheduler supports triggers like "Unlock workstation," "idle," and "wake from sleep." Perhaps either Windows-Auto-Night-Mode can listen for the same alerts, or otherwise could defer to Task Scheduler?

**Comment by Spiritreader** [comment]
![image](https://user-images.githubusercontent.com/18438899/194135879-f918603b-da33-4ab0-9e7c-20f1d70e2b7f.png)
