### ISSUE TITLE
Auto switching mode not complete

### ISSUE THREAD

**Issue by nogeffedan** [AutoDarkMode/Windows-Auto-Night-Mode#536]
### Description

Allthough switching mode works in Windows 11, it seems not complete for apps.

For example when auto switching from light to dark mode did take place and I then open the Windows Settings app, the first half second the Settings window still appears light (with no content in it) and then switches to black (with content).
The same effect also happens the other way around after auto switching from dark to light. The first half second the app appears dark and then turns light.

If I manually switch between dark/light apps mode via Windows Settings, above described effect is gone.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9732230/service.log)
[config.yaml.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9732239/config.yaml.log)

### Operating System

Windows 11 22H2 22621.608

### Commit Hash and Version

- Commit: `f7a700b`
- Service: `10.2.0.18`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.7`

**Comment by Spiritreader** [comment]
Hi, thanks for the report.

Unfortunately, ADM is working properly in your case and this is a windows issue with the theme switching API.

Sadly this can't be fixed unless MS is doing something to counteract.
