### ISSUE TITLE
Always switching to dark mode at 4 pm / 16:00 CET

### ISSUE THREAD

**Issue by Jukeman9** [AutoDarkMode/Windows-Auto-Night-Mode#539]
Hello,
The app always switches to dark mode at 4 pm / 16:00 CET if it is set to geolocation (it should trigger around 18:20/6p.m. (app permiossion is granted) and also even if it's set to custom hours e.g. 21/9pm.

**Comment by Spiritreader** [comment]
no logs, no clue
