### ISSUE TITLE
Help button placement

### ISSUE THREAD

**Issue by tooomm** [AutoDarkMode/Windows-Auto-Night-Mode#549]
**Describe what issue or improvement you have with the usability design**
The help button is hidden currently and only accessible from within one menu.
It's usefulness is not limited to the `Time` menu. Users don't anticipate it there when looking for help.

**Describe how you would like to see it improved**
Place a `Get Help` item in the main menu for example.

**Additional context**
![help](https://user-images.githubusercontent.com/9874850/195447739-6c32f423-f489-401d-acdc-a0539f151354.png)

**Comment by Armin2208** [comment]
It was planned back then, but I removed that, because the navbar indicator got stuck at the link.

But you're right, it would be much better. Will try again soon. Thanks.

**Comment by tooomm** [comment]
> It was planned back then, but I removed that, because the navbar indicator got stuck at the link.

If placing a direct link there is causing issues...

You could also rename the `About` menu to `About / Help` and place a `Get Help` (or `Troubleshooting`) link there.

**Comment by PtrStruct** [comment]
I'm working on this, I'll push a commit today.

**Comment by Spiritreader** [comment]
Thanks @PtrStruct, works beautifully.
