### ISSUE TITLE
Does not work under Windows11 Pro x64 22H2

### ISSUE THREAD

**Issue by amitaba** [AutoDarkMode/Windows-Auto-Night-Mode#551]
### Description

AD has stopped working entirely after the new 22H2 update. It does not display Äpply button, will not activate on any setting (custom hours, sunset/sunrise), etc.

### Expected Behavior

ADM should just work as before

### Log Data

you don't support attaching the log or confrig files

### Operating System

Windows11 Pro x64 22H2

### Commit Hash and Version

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

**Comment by Armin2208** [comment]
Why didn't you updated Auto Dark Mode?
Didn't you get or see the Notification that an update is available?

**Comment by Spiritreader** [comment]
Also the bug report template asks for this:
![image](https://user-images.githubusercontent.com/18438899/195838057-ab9dfd22-1034-4c84-be3e-bfe6a7b6f541.png)

**Comment by amitaba** [comment]
I am not a coder but an end user. ADM, even though set for auto-update, did not update, either in stable nor beta channel. I finally figured out how, i think, to download the latest beta version. I will test.

**Comment by Spiritreader** [comment]
merge with #506
