### ISSUE TITLE
Show, app running status and delay info (with tooltip) on the tray icon.

### ISSUE THREAD

**Issue by cmhrky** [AutoDarkMode/Windows-Auto-Night-Mode#560]
**Describe the enhancement or feature you'd like**
It will allow you to quickly learn the relevant information without opening the application interface.

**Describe alternatives you've considered**
Gray ADM icon if app is disabled.
The app icon with the pause icon when paused.
App status and "Active delays" information in the tooltip.

**Additional context**
![image](https://user-images.githubusercontent.com/17867666/196036376-90a17edd-f927-42be-9119-410f70349460.png)
![image](https://user-images.githubusercontent.com/17867666/196036386-e9701d62-d723-4bd9-aaa7-464d6862c8c7.png)
![image](https://user-images.githubusercontent.com/17867666/196036599-889af8fe-d855-4441-872f-0b45c8959486.png)

**Comment by Spiritreader** [comment]
I don't know if we can implement this in time for the 10.3 release, but that's a super cool idea. 
I really like this.

**Comment by tooomm** [comment]
Ha, I had a very similar idea to improve the tray icon a few days ago @cmhrky! 😄

My thoughts were to mirror the mode that is currently used in the icon:
- Light Mode: Show only the sunny part of the icon in color, grey out the moon part.
- Dark Mode: Show only the moon part of the icon in color, grey out the sun part.

**Comment by cmhrky** [comment]
You are so fast. Thanks. Will there be tooltip information?

**Comment by Armin2208** [comment]
wow respect for this suggestion, awesome

**Comment by Spiritreader** [comment]
> You are so fast. Thanks. Will there be tooltip information?

I will play around with it, but no guarantees that it will make it into a final build

**Comment by cmhrky** [comment]
If AutoDarkModeSvc.exe is restarted while ADM is disabled, the tray icon appears to be enabled.

Also, if there is an active delay set manually, it will be canceled on the next start. I don't know the status of the Tray icon.

**Comment by Spiritreader** [comment]
>  the tray icon appears to be enabled.
Oh yes, it doesn't update this. will fix

> Also, if there is an active delay set manually, it will be canceled on the next restart. 
That is intentional.

**Comment by Spiritreader** [comment]
> You are so fast. Thanks. Will there be tooltip information?

There will be tooltip information in the next build!
