### ISSUE TITLE
Buggy after Windows 11 wakes up in the morning over night

### ISSUE THREAD

**Issue by miditw** [AutoDarkMode/Windows-Auto-Night-Mode#574]
### Description

Windows 11 22H2 Home Edition
nVidia GTX 1070 (latest driver)

My PC gone "auto-sleep" last night by setting.
This morning, when I wake up my PC, the Task Bar acts strangely.
It shows the black icons with dark color Task Bar.
Normaly, it will show black icons with light color Task Bar, or white icons with dark color Task Bar.
Seems to me like a bug. Would you check out for that problem and fix it? Thanks!

### Expected Behavior

ADM wronly display black icons with dark color Task Bar after PC wake up in the morning.
ADM should display black icons with light color Task Bar, or white icons with dark color Task Bar.
Even after PC wake up in the morning after gone sleep mode over night.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9843148/service.log)

### Commit Hash, Version and Windows Build

版本	Windows 11 家用版
版本	22H2
安裝於	‎2022/‎10/‎6
OS 組建	22621.674
體驗	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by Spiritreader** [comment]
You're using an old version that is no longer maintained. Please update to the latest beta. Everything is fixed there and more.
