### ISSUE TITLE
Choosing the traditional Chinese, but the UI language is still simplified Chinese.

### ISSUE THREAD

**Issue by Tamaya-Jin** [AutoDarkMode/Windows-Auto-Night-Mode#578]
### Description

1. I downloaded it from Github. 
2. Updating it to the latest version with the Beta channel.
3. Chose the traditional Chinese.
4. But the language is still simplified Chinese.

### Expected Behavior

The language of UI should be traditional Chinese. 

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9850879/service.log)
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9850887/config.zip)

Sorry, I can't upload the .yaml file so I compressed it into .zip. 

### Commit Hash, Version and Windows Build

- Commit: `ed4c2b1`
- Service/App: `10.3.0.81`
- Updater: `2.5.1`
- Shell: `1.3.1.0`
- .Net: `6.0.10`
- Windows: `22623`

**Comment by Spiritreader** [comment]
does switch for me, I wonder if it has to do with the locale string that is saved in the app cache.
I'll look into it

**Comment by Spiritreader** [comment]
It appears as if Microsoft has changed the language definitions again!! Wohooo!
I've updated the language files to something that works again.
I am pretty certain that this will happen again in the future, feel free to reopen the issue then

**Comment by Tamaya-Jin** [comment]
Thank you so much! 
Looking forward to the next update~

**Comment by Spiritreader** [comment]
> Thank you so much! Looking forward to the next update~

I've pushed a new beta 10.3.0.82 that has the updated language files. Should be available soon!
You may have to switch to english, restart the app and then switch back to chinese traditional and restart once more for the app language definitions to update!

**Comment by chungchungdev** [comment]
I also have the same problem.
Updated to beta 10.3.0.84.
Tried switching to English and back to Traditional Chinese.
Tried rolling back to old versions. Version 10.0.0.26 shows Traditional Chinese correctly with some untranslated English words. All later versions only show Simplified Chinese.

My OS is Windows 10 22H2 19045.2130.

**Comment by Spiritreader** [comment]
Hmm yea it reverted for me as well.

I don't think i can fix this. This appears to be a bug in dotnet.
I've changed the language definitions twice now and it keeps happening.

**Comment by Spiritreader** [comment]
Okay, apparently .NET isn't able to discern language definitions if they share the same root and automatically picks the shorter one. It also doesn't always compile the zh-cht file for some reason. I've renamed the files once again and hopefully it works now.

10.3.0.85 should be available soon.

**Comment by Tamaya-Jin** [comment]
It's okay now!
❤️
![image](https://user-images.githubusercontent.com/115028995/198838496-55ff6dda-49f3-4390-8c67-24698b2ba7d0.png)
