### ISSUE TITLE
Unable to apply settings

### ISSUE THREAD

**Issue by asdfhdasfhasd** [AutoDarkMode/Windows-Auto-Night-Mode#579]
### Description

unable to apply settings, and I tried to use the methods on the waring, but don't work.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9852744/service.log)
github doesn't suit .yaml; I change it to .txt

[config.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9852757/config.txt)

### Commit Hash, Version and Windows Build

- Commit: `b8a079d`
- Service/App: `10.3.0.82`
- Updater: `2.5.1`
- Shell: `1.3.1.0`
- .Net: `6.0.10`
- Windows: `22621`

### Screenshots / Videos

<img width="415" alt="屏幕截图 2022-10-24 230311" src="https://user-images.githubusercontent.com/61657224/197560864-70dd13d3-e236-49af-99fa-0c0b16e06fb8.png">

**Comment by Spiritreader** [comment]
Are you using an ARM based device?

**Comment by UMOAQ** [comment]
> Are you using an ARM based device?
> 
> Also this is not really an error related to settings. I should probably update that text.
No，I use a x64 device, this is my pc info.

Device name
Processor 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz
40.0 GB RAM (39.7 GB available)
System type 64-bit operating system, x64-based processor

Version Windows 11 Pro
Version 22H2
Installation date 2022/10/24
OS version 22621.674
Experience Windows Feature Experience Pack 1000.22634.1000.0

**Comment by Spiritreader** [comment]
Thanks!

Are you able to provide a translation for the error message in the screenshot?

**Comment by UMOAQ** [comment]
> 谢谢！
> 
> 您是否能够为屏幕截图中的错误消息提供翻译？

I specially choose English in software to reproduce the error, and the screenshot is English. Do you mean the only Chinese:"找不到”？The meaning of it is "can't find"

**Comment by Spiritreader** [comment]
> Do you mean the only Chinese:"找不到”？The meaning of it is "can't find"

Yes, exactly, I meant that! Thanks. That reassures my assumption I outlined above

**Comment by UMOAQ** [comment]
> 谢谢！
> 
> 您是否能够为屏幕截图中的错误消息提供翻译？
> 
> 它似乎好像自动黑暗模式找不到自动启动条目。
> 
> ```
> 2022-10-24 23:05:17 | Error | RegistryHandler.IsAutostartApproved: could not retrieve autostart startup approved entry: NullReferenceException > Object reference not set to an instance of an object. > Boolean IsAutostartApproved()
> ```
> 
> 您能否通过注册表编辑器导航到并确保注册表项存在，以及“自动黑暗模式”条目？`SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run`
> 
> 应该看起来像这样 ![图像](https://user-images.githubusercontent.com/18438899/197571008-c51da4f7-ce36-4de8-b5d3-8e2a6405c85b.png)

I searched the regedit. There is no \StartupApproved under \explorer

**Comment by UMOAQ** [comment]
> > 谢谢！
> > 您是否能够为屏幕截图中的错误消息提供翻译？
> 
> I specially choose English in software to reproduce the error, and the screenshot is English. Do you mean the only Chinese:"找不到”？The meaning of it is "can't find"



> Thanks!
> 
> Are you able to provide a translation for the error message in the screenshot?
> 
> It appears as if Auto Dark Mode is unable to find the autostart entry.
> 
> ```
> 2022-10-24 23:05:17 | Error | RegistryHandler.IsAutostartApproved: could not retrieve autostart startup approved entry: NullReferenceException > Object reference not set to an instance of an object. > Boolean IsAutostartApproved()
> ```
> 
> Could you navigate to `SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run` via regedit and ensure that the registry key is there, as well as the "AutoDarkMode" entry?
> 
> Should look like this ![image](https://user-images.githubusercontent.com/18438899/197571008-c51da4f7-ce36-4de8-b5d3-8e2a6405c85b.png)

I use ctrl F and find it under this `计算机\HKEY_USERS\S-1-5-21-1998402688-2482168250-2247747961-1001\Software\Microsoft\Windows\CurrentVersion\Run`
<img width="858" alt="屏幕截图 2022-10-25 000442" src="https://user-images.githubusercontent.com/61657224/197573087-aae004b5-1008-48d6-9664-b1a9a372f3d3.png">

**Comment by Spiritreader** [comment]
> I use ctrl F and find it under this 计算机\HKEY_USERS\S-1-5-21-1998402688-2482168250-2247747961-1001\Software\Microsoft\Windows\CurrentVersion\Run
That's a different entry that controls whether the auto start entry shows up.

The one I'm referring to under StartupApproved is responsible for setting this disabled and enabled flag in Task Manager. For some reason, on your system there's just nothing configured that way yet or the regkey was never created on your system.

I have good news, there's no issue with ADM. You've just caught an erroneous message showing up when it shouldn't. 
You can continue using ADM as is, everything is working as intended. 

I will push a fix that removes the error. For now you can just click on "No" or close the window when opening the settings page.
