### ISSUE TITLE
Portable by Network Storage

### ISSUE THREAD

**Issue by Hao0920** [AutoDarkMode/Windows-Auto-Night-Mode#591]
**Describe what issue or improvement you have with the usability design**
Since the file is released in zip format, it can be used as a portable version on network storage (such as OneDrive). Then the configuration file should be put together with the program.
**Describe how you would like to see it improved**
Put the configuration folder in the program root directory instead of "C:\Users\USERNAME\AppData\Roaming\AutoDarkMode"
**Additional context**
none

**Comment by Spiritreader** [comment]
There are no plans to move the configuration file or folder location.
Portability in ADM is meant in a sense that no explicit installation is required, but storing config data for now is mandatory in %appdata% and will probably not change unless we switch from x86 unpackaged installation to packaged msix, which at the moment is not an option yet as we rely on more than just .net to deliver ADM.
