### ISSUE TITLE
Dark Mode Switch does not work

### ISSUE THREAD

**Issue by vonmaster** [AutoDarkMode/Windows-Auto-Night-Mode#620]
### Description

ADM was working just fine on Windows 10 until the recent updates: ADM is unable to switch to dark mode (even when trying to force dark mode).
I updated to the Beta Channel and reinstalled ADM several times, but it still does not work.

### Expected Behavior

Automatic theme switch should work.
Forcing Dark Mode through ADM should work.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9989338/service.log)
[config.yaml](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9989355/config.log)

### Commit Hash, Version and Windows Build

- Commit: `212dbb4`
- Service/App: `10.3.0.90`
- Updater: `2.5.2`
- Shell: `1.3.1.0`
- .Net: `6.0.10`
- Windows: `19045.2251`

### Screenshots / Videos

![test](https://user-images.githubusercontent.com/43321841/201321180-f5ba334f-8563-421a-8b79-4daf6025f6da.gif)

**Comment by Spiritreader** [comment]
Unfortunately I can't reproduce that on my 19045.2251 machine.
The logs don't indicate that ADM is doing anything wrong, so the issue must lie with windows failing to apply the theme.

Can you apply themes via the windows control panel?

**Comment by vonmaster** [comment]
Hi, 
Thanks for the quick reply.
It worked! I was going crazy...
Maybe it would be great to add this fix here: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Troubleshooting
Thanks,

**Comment by Spiritreader** [comment]
> Hi, Thanks for the quick reply. It worked! I was going crazy... Maybe it would be great to add this fix here: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Troubleshooting Thanks,

I've instead added some more sanitization to auto dark mode so it automatically catches these cases and attempts to auto-repair the theme file.

**Comment by swoy45** [comment]
> Delete Custom.theme, ADMTheme.theme and then create another theme via the windows control panel.

Had same issue, this helped me too. I think the issue itself appears when you trying to use another app which modifies your themes. In my case ADM stopped working right after installing UltraUX Theme Patcher.

**Comment by Spiritreader** [comment]
> > Delete Custom.theme, ADMTheme.theme and then create another theme via the windows control panel.
> 
> Had same issue, this helped me too. I think the issue itself appears when you trying to use another app which modifies your themes. In my case ADM stopped working right after installing UltraUX Theme Patcher.

Not necessarily. The other app would have to modify the ini file incorrectly.
Windows also can't fully apply these themes anymore so you essentially break theme field windows wide if the ini file structure gets corrupted.
