### ISSUE TITLE
Toggling back to light theme gives weird colors in File Explorer (Windows 11, build- stable 22621.819)

### ISSUE THREAD

**Issue by d3EyedRaven** [AutoDarkMode/Windows-Auto-Night-Mode#621]
![image](https://user-images.githubusercontent.com/71594081/201370725-df2efa96-198f-4872-ada1-02b644c1dc2b.png)

**Comment by Spiritreader** [comment]
listed as known issue / windows bug
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Known-limitations
