### ISSUE TITLE
Suggestion: Restart Windows Explorer Option

### ISSUE THREAD

**Issue by muhlisgursoy** [AutoDarkMode/Windows-Auto-Night-Mode#625]
Hi,

Been using this program for a while. Occasionally the theme doesn't update correctly (clocks etc), but restarting the Windows Explorer on the Task Manager corrects the problem. Is there any chance a "Restart Windows Explorer automatically when switching theme" feature is being added to the program? That would be helpful.

Thanks!

**Comment by Spiritreader** [comment]
This won't be implemented as we consider this intrusive behavior by ADM.

You can achieve this by using custom scripts
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/discussions/597
