### ISSUE TITLE
Set themes or wallpapers for different desktops

### ISSUE THREAD

**Issue by zhzhmao** [AutoDarkMode/Windows-Auto-Night-Mode#628]
In Windows, I will add multiple desktops. I hope that the wallpaper or theme of each desktop is different. I want to know if it is possible to set the theme or wallpaper on different desktops (same display) respectively.

**Comment by Spiritreader** [comment]
related to #469, we're currently waiting for a stable API (preferrable an npm package) that allows us to do that.
