### ISSUE TITLE
Where is the command-line tool?

### ISSUE THREAD

**Issue by fenhl** [AutoDarkMode/Windows-Auto-Night-Mode#629]
### Question

I am trying to test the command-line tool as documented at <https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Command-line-arguments-|-parameters> but PowerShell can't find it:

```
$ AutoDarkModeShell.exe --dark
AutoDarkModeShell.exe: The term 'AutoDarkModeShell.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Where can I find this CLI?

**Comment by Armin2208** [comment]
The CLI is located at the installation path of Auto Dark Mode.
Default path: %localappdata%\Programs\AutoDarkMode
If you need to use the AutoDarkModeShell.exe on regular base, you can at it to the Windows Path.

**Comment by fenhl** [comment]
Update for anyone finding this now: The CLI seems to have moved into the `adm-app` subdirectory, i.e. `%localappdata%\Programs\AutoDarkMode\adm-app\AutoDarkModeShell.exe` by default.
