### ISSUE TITLE
AutoDarkModeApp.exe closes unexpectedly when you specify "Time the notification waits for user input in minutes" greater then Int32.MaxValue

### ISSUE THREAD

**Issue by saha80** [AutoDarkMode/Windows-Auto-Night-Mode#633]
In "Switch Modes" and with checked "Notify before automatically switch themes" you're able to specify "Time the notification waits for user input in minutes". When you specify this time greater then Int32.MaxValue AutoDarkModeApp.exe closes without showing any error message. But AutoDarkModeSvc.exe keep running in background.
![image](https://user-images.githubusercontent.com/48954743/203402306-fa2fd15d-d5a4-4e2d-a5a8-a0995a7158f8.png)

Maybe it's caused by [Convert.ToInt32](https://learn.microsoft.com/en-us/dotnet/api/system.convert.toint32?view=net-7.0), which throws [OverflowException](https://learn.microsoft.com/en-us/dotnet/api/system.overflowexception?view=net-7.0)

https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/blob/1817a320cad3bfcf43be82932241486b372aaf7f/AutoDarkModeApp/Pages/PageSwitchModes.xaml.cs#L256

- Commit: `212dbb4`
- Service/App: `10.3.0.90`
- Updater: `2.5.2`
- Shell: `1.3.1.0`
- .Net: `6.0.10`
- Windows: `19045.2311`

**Comment by Spiritreader** [comment]
oops

Honestly didn't really think anyone would ever want this. if you set this to intmax, why have it enabled in the first place.
You're absolutely right, this is due to the conversion.

Will fix, thanks!

**Comment by Spiritreader** [comment]
I've added the conversion method to the already in-place exception handilng for the save process.
It now shows an error MessageBox informing users of why it happened when setting a value that is too large instead of crashing the app,
