### ISSUE TITLE
希望能让虚拟键盘也一同更换成深色（I hope the touch keyboard can also be replaced with dark color）

### ISSUE THREAD

**Issue by CaseYwY** [AutoDarkMode/Windows-Auto-Night-Mode#639]
Every time I open the touch keyboard late at night, the white skin always blinks my eyes like a flashbang 
<img width="861" alt="175088281-ba0f354f-74e7-4ea1-b5d0-d2bcf9d3d5cb" src="https://user-images.githubusercontent.com/93791824/204366680-ad760144-984f-41cf-923b-354f812dac8a.png">
<img width="770" alt="175091490-166265dc-7849-42ce-b245-e36a8d2e4f84" src="https://user-images.githubusercontent.com/93791824/204366676-ad7f4e6e-6bda-4011-b9d1-e60eea09f8ac.png">

**Comment by Spiritreader** [comment]
Hi,

At the moment we don't plan to offer any automatic switching for the integrated keyboard.

However there is a discussion about possibly integrating IME over here.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/451

I'll link this issue and close it to avoid duplicates.

Thanks for the suggestion!
