### ISSUE TITLE
Tray icon does not correctly display data

### ISSUE THREAD

**Issue by emanuel-c4** [AutoDarkMode/Windows-Auto-Night-Mode#661]
**Describe what issue or improvement you have with the usability design**

I have found a problem in the info and options of the tray icon. The data can be displayed in some Cyrillic language, when it should be displayed in English.

**Describe how you would like to see it improved**

It should display the data in the default language of the programme (English) or display it in the selected language of the user's choice, if no translation is available at the time, use the default language.

**Additional context**
| Light Mode | Dark Mode |
| :---: | :---: |
| ![image](https://user-images.githubusercontent.com/36056518/210267693-211f5afd-fde9-4059-b4dd-d09935f20734.png) | ![image](https://user-images.githubusercontent.com/36056518/210269517-bc0b2c73-c4fc-4645-a1b7-0acdd2240d63.png) |
| ![image](https://user-images.githubusercontent.com/36056518/210267718-fa3da35c-5020-4a43-baa2-089f2cead8dc.png) | ![image](https://user-images.githubusercontent.com/36056518/210269298-354380d1-453b-4a65-a2ea-53eb85525811.png) |
| ![image](https://user-images.githubusercontent.com/36056518/210267736-e2c46c6a-55f1-4c9f-b981-6ce5cb676b19.png) | ![image](https://user-images.githubusercontent.com/36056518/210269791-255630bf-e4a0-42cb-86c4-939166392b19.png) |

Program info:
- Commit: `212dbb4`
- Service/App: `10.3.0.90`
- Updater: `2.5.2`
- Shell: `1.3.1.0`
- .Net: `6.0.10`
- Windows: `19044.2364`

**Comment by Spiritreader** [comment]
Hmm I can't really say why this is happening.
Especially the close button is generated in the exact same place where all the other menu options are defined as well, so this doesn't really make sense.

**Comment by emanuel-c4** [comment]
I have found the reason why the tray icon appears in Russian to me, before making any modifications I looked at the program's configuration files and found this: `UICulture: ru` in the file `%AppData%/AutoDarkMode/config.yaml`. When changing from the program I had in Spanish to another language, the bug was corrected and `UICulture` was changed to the selected language. Now it is in Spanish, it shows the entire program and the tray icon correctly.

I also found out that if I modified the `UICulture` language property from the file, then closed the program and reopened, it would only change the language of the tray icon data. Although the entire program interface continued to display in the previously selected language from `Settings`.

**Comment by Spiritreader** [comment]
> I have found the reason why the tray icon appears in Russian to me, before making any modifications I looked at the program's configuration files and found this: `UICulture: ru` in the file `%AppData%/AutoDarkMode/config.yaml`. When changing from the program I had in Spanish to another language, the bug was corrected and `UICulture` was changed to the selected language. Now it is in Spanish, it shows the entire program and the tray icon correctly.
> 
> I also found out that if I modified the `UICulture` language property from the file, then closed the program and reopened, it would only change the language of the tray icon data. Although the entire program interface continued to display in the previously selected language from `Settings`.

Language changes currently only work when changing the language on the settings page and then pressing the restart button. That's necessary as the service doesn't support on-the-fly language changes.
