### ISSUE TITLE
Hope to add a toggle for the cursor

### ISSUE THREAD

**Issue by GhostBone** [AutoDarkMode/Windows-Auto-Night-Mode#662]
**There are two sets of color cursors (Light and Dark) in my system. I hope that the cursor of the selected corresponding color can be automatically set when the mode is automatically switched.**

![image](https://user-images.githubusercontent.com/40034700/211148721-c50995cf-8951-4c96-ab29-a7142f2f5383.png)

**Comment by Susko3** [comment]
You should be able to use theme switching for this:

![image](https://user-images.githubusercontent.com/16479013/211166330-62838d1c-013c-4a0f-9ef9-f9293a1a8d28.png)

**Comment by GhostBone** [comment]
Thank you, it worked!

Maybe I didn't see it. My bad. sorry!

😶‍🌫️😶‍🌫️😶‍🌫️
