### ISSUE TITLE
Issue with Windows start menu and auto dark mode theme switch

### ISSUE THREAD

**Issue by PeopleInside** [AutoDarkMode/Windows-Auto-Night-Mode#674]
### Description

When at night the theme set is dark and I turn off the PC, the next morning when I turn the PC On Auto Dark Mode switch the theme to the light one but the start menu is not updated.

Even using the keybord button ... in my case altgr + D for dark and altgr + L for light never update the Windows start menu.
No issues if I switch the theme from Windows preference interface so the issue seems to be Auto Dark Mode.

### Expected Behavior

I expect to see the start menu updated as well with the relative theme

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/10465523/service.log)
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/10465526/config.zip)

### Commit Hash, Version and Windows Build

![immagine](https://user-images.githubusercontent.com/5006150/213675426-f2bb6f26-fdde-4c44-92c7-47bb78a306d3.png)
The button to copy the information above is broken as an error is showed.
![immagine](https://user-images.githubusercontent.com/5006150/213675561-ef66216c-965c-4a5b-8bd9-3018b781381d.png)

**Comment by Spiritreader** [comment]
If it's *only* the start menu then it's probably an issue with the API we use, which we don't have influence over.
Doesn't seem like it's anything we can fix.

Does repeatedly opening the start menu resolve the issue?

**Comment by PeopleInside** [comment]
@Spiritreader clicking start manually each time resolve.
The issue is only in the Beta, in the stable not.

**Comment by Spiritreader** [comment]
> @Spiritreader clicking start manually each time resolve. The issue is only in the Beta, in the stable not.

that's strange, there were no code changes when calling the api regarding beta vs stable.

**Comment by PeopleInside** [comment]
Understood. I'm sorry you seems have no idea why this happen.
Never mind, what I can do i do, I open a bug report after discovering switching from beta to stable resolve the issue.
After testing changing the theme from Windows cause no issues, only when Auto Dark mode are at work.

I thought also to open a Windows BUG but how can I report a Windows Feedback if switching from theme works well on Windows? :)

**Comment by Spiritreader** [comment]
The thing is, theme switching in windows doesn't work well either, it's just more difficult to break as they seem to do some stuff we aren't aware of when using the API.

Best thing is to probably just use what works best for you for now.

**Comment by fkamp** [comment]
I understand there is probably nothing that can be done here; I thought I still give some feedback regardless.
I have the exact same problem. Running this version:

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

On...
Edition	Windows 11 Pro
Version	22H2
Installed on	‎09.‎06.‎2022
OS build	22621.1344
Experience	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by Spiritreader** [comment]
> I understand there is probably nothing that can be done here; I thought I still give some feedback regardless. I have the exact same problem. Running this version:
> 
>     * Commit: `5e6ea8a`
> 
>     * Service: `10.1.0.10`
> 
>     * Updater: `2.4.2`
> 
>     * App: `10.0.1.0`
> 
>     * Shell: `1.3.1.0`
> 
>     * .Net: `6.0.0`
> 
> 
> On... Edition Windows 11 Pro Version 22H2 Installed on ‎09.‎06.‎2022 OS build 22621.1344 Experience Windows Feature Experience Pack 1000.22639.1000.0

Thanks!
We are always monitoring new developments in terms of how much of the Windows theming API is available and what workarounds improve the experience.
Every new Windows build since 22H2 has significantly changed (sadly mostly for the worse) the behavior of IThemeManager1&2 and from what I understand (as I'm not the one reverse engineering the APIs) new information can only be achieved by doing kernel debugging.

We should probably make a spreadsheet at some point for what works and what doesn't on the different Windows versions. Just for the sake of keeping an overview and for users to report or inform themselves on behavior specific to certain builds,

**Comment by futursolo** [comment]
I found a workaround for this issue that if you use theme switch (Personalize -> Pick a Theme) and pick a dark and a light theme then the taskbar can be switched alongside the theme.
If you turn off "Enable Windows theme switch", the taskbar will not be switched.

**Comment by fkamp** [comment]
> I understand there is probably nothing that can be done here; I thought I still give some feedback regardless. I have the exact same problem. Running this version:
> 
> * Commit: `5e6ea8a`
> * Service: `10.1.0.10`
> * Updater: `2.4.2`
> * App: `10.0.1.0`
> * Shell: `1.3.1.0`
> * .Net: `6.0.0`
> 
> On... Edition Windows 11 Pro Version 22H2 Installed on ‎09.‎06.‎2022 OS build 22621.1344 Experience Windows Feature Experience Pack 1000.22639.1000.0

Just fyi, the latest version of AutoDarkMode did it for me. Thanks!!
```
- Commit: `212dbb4`
- Service/App: `10.3.0.90`
- Updater: `2.5.2`
- Shell: `1.3.1.0`
- .Net: `6.0.10`
- Windows: `22621.1413`
```
