### ISSUE TITLE
 taskbar sometimes does not hide

### ISSUE THREAD

**Issue by brunocardosoeng91** [AutoDarkMode/Windows-Auto-Night-Mode#679]
### Description

Hello, since I installed the app there are times when my taskbar does not hide. However, it is only on the main monitor, because on the auxiliary monitor it hides normally. this started to appear since I installed it.

I would like to congratulate you for the application, a long time ago I had this criticism in windows of not being able to change to dark mode automatically.

There is another thing, when I set it to change with the sun, the time of sunrise is correct, but when the sun sets it is wrong, I think it is a small problem.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/10499298/service.log)

### Commit Hash, Version and Windows Build

![image](https://user-images.githubusercontent.com/93286991/214565645-48e6ffdc-a2ed-4959-b552-5365ddc52f3d.png)

**Comment by Spiritreader** [comment]
Hmm the taskbar is not something we have control over sadly. I would assume this happens due to the theme change but that again is also controlled by windows.

As far as sunrise/sunset times are concerned, what option did you select?
Do you use the automatic geolocation or did you enter coordinates manually?

**Comment by brunocardosoeng91** [comment]
what caught my attention is that on one monitor it hides normally, on the other it is always active, some software I use have buttons at the bottom, so I need to keep changing it. But I'll see if it's a defect in windows itself.

on the issue of sunrise/sunset I found out what it was, there was an advance on the offset.


I would like to take advantage, where can I help translate the app? there are some words wrong and others that were not translated

**Comment by Spiritreader** [comment]
> what caught my attention is that on one monitor it hides normally, on the other it is always active, some software I use have buttons at the bottom, so I need to keep changing it. But I'll see if it's a defect in windows itself.
> 
> on the issue of sunrise/sunset I found out what it was, there was an advance on the offset.
> 
> I would like to take advantage, where can I help translate the app? there are some words wrong and others that were not translated

It might work fine during normal use. The api we call to switch themes is undocumented and reverse engineered so I wouldn't be surprised if some things aren't working properly. It's the trade-off when using automatic theme switching. 

You can help translate ADM here:
https://hosted.weblate.org/projects/auto-dark-mode/app/

**Comment by brunocardosoeng91** [comment]
about the taskbar, i think i solved. i open the task mananger e restart the windows ecplorer, after that, the taskbar hide

**Comment by Spiritreader** [comment]
awesome, glad you got your issue resolved!
