### ISSUE TITLE
ADM is resetting my theme back to default in MS Edge

### ISSUE THREAD

**Issue by ghost** [AutoDarkMode/Windows-Auto-Night-Mode#694]
### Description

https://user-images.githubusercontent.com/71337477/224516367-a6b6fef9-72cd-4f37-9b3c-cc66f97bbe8a.mp4

See the video for more details about this problem.

### Expected Behavior

ADM should NOT change my wallpaper back to defaults in MS Edge.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/10949695/service.log)
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/10949696/config.zip)

### Commit Hash, Version and Windows Build

![image](https://user-images.githubusercontent.com/71337477/224516456-ac14066d-d838-498a-b048-561cf371c8ba.png)

### Screenshots / Videos

https://user-images.githubusercontent.com/71337477/224516460-0de55889-3da4-41d1-b4d3-4562b58e72ae.mp4

**Comment by Spiritreader** [comment]
ADM is doing nothing to MSEdge, so probably an edge bug related to changing themes.
Have you tried disabling dynamic theme in Edge?

**Comment by Spiritreader** [comment]
![image](https://user-images.githubusercontent.com/18438899/225089646-2c9c168f-19f2-4e5f-b7e2-d0c05301d067.png)

Maybe this one, set it to light or dark and see if the theme is still being changed.
I could also be that you have to set your background for each theme that gets selected.

I can't reproduce this behavior on Edge, Edge Dev and Edge Canary so I can'tprovide more insight unfortunately.
