### ISSUE TITLE
big log output

### ISSUE THREAD

**Issue by uykuda** [AutoDarkMode/Windows-Auto-Night-Mode#695]
### Description

i have 2,73GB log file.

### Log Data

![image](https://user-images.githubusercontent.com/81591768/224678264-74bf90d2-4783-4533-9929-0bcd8fe98a7d.png)
![image](https://user-images.githubusercontent.com/81591768/224678310-f6677ddf-c359-4ccb-8461-b48918da46bc.png)

### Commit Hash, Version and Windows Build

![image](https://user-images.githubusercontent.com/81591768/224678529-8ca372a6-fe82-487e-a04c-338264405fa1.png)

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/81591768/224678619-ae6d159c-f57d-4739-aee0-d54148ece816.png)

**Comment by uykuda** [comment]
2023-03-12 22:30:45 | Warn | AsyncPipeServer.HandleRequest: request pipe was closed prematurely 

i found the error, opened service.log with chrome.

full spammed this warn

![image](https://user-images.githubusercontent.com/81591768/224679266-6a1e75ca-81c9-47af-aa7f-5ebdb707097b.png)

**Comment by Spiritreader** [comment]
This is usually due to a permission issue, either temporary or because of system config. However it shouldn't spam the log that way. I've addressed this by setting a timeout before the request handler is allowed to retry.
