### ISSUE TITLE
Make the Svc exe a service

### ISSUE THREAD

**Issue by aaronliu0130** [AutoDarkMode/Windows-Auto-Night-Mode#700]
**Describe the enhancement or feature you'd like**
I'm not that familiar with how Windows works, but I've heard that services autorun faster. A quick glance at Task Manager and Autoruns reveals that AutoDarkModeSvc.exe is considered as a process/app but not a service. Currently I run into the issue of AutoDarkMode sometimes autorunning like 30s~1min after login (I don't have a very good concept of time but I felt it was quite a long time, this is a rough estimate), which is mildly inifuriating when the theme needs to switch

**Describe alternatives you've considered**
Delay every other autorun process by ~30s but that's even more infuriating

**Comment by Spiritreader** [comment]
Not planned because we don't want to mess with registering and unregistering services when and we want to keep ADM portable.

If you want quicker startup time you can use a logon task
![image](https://user-images.githubusercontent.com/18438899/228949117-0299014e-7767-41c7-a784-9c2854f2ca63.png)

**Comment by aaronliu0130** [comment]
Thanks for the speedy response!
