### ISSUE TITLE
Setting on full screen game doesn't work

### ISSUE THREAD

**Issue by 1111Al** [AutoDarkMode/Windows-Auto-Night-Mode#705]
### Description

Although it is set to not change theme while playing, it changes and make problems for the game.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11208230/service.log)

[AutoThemeSwitchingEnabled true.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11208262/AutoThemeSwitchingEnabled.true.txt)

### Commit Hash, Version and Windows Build

10  22h2  22621.1105

**Comment by Spiritreader** [comment]
A lot of stuff can be the reason for that.

Could you please turn on debug logs in the settings?
That way we will get more information what exactly is going on. 

The out of the box configuration of the gpu monitor module might be too conservative if you have a high end GPU and/or depending on the game you play

You might also want to increase the samples to "2"

Please try that. 

If that doesn't work upload the logs again and we'll try to see if there's something wrong with windows performance counter querying

**Comment by 1111Al** [comment]
> 

Even today it changed theme while playing Skyrim LE, causing a crash of the game. I don't have an high level gpu, for now I set  the samples to 2. In th case I'll activate debug mode.

**Comment by 1111Al** [comment]
It is not just a problem with one game, the program always changes at the scheduled time, whether there are full screen windows or not. Here it does that with any program in full screen. I have now selected debug mode for the next log.

**Comment by Spiritreader** [comment]
> It is not just a problem with one game, the program always changes at the scheduled time, whether there are full screen windows or not. Here it does that with any program in full screen. I have now selected debug mode for the next log.

Thanks for the update, I assume that there will probably be some issue with GPU usage detection, but the logs will reveal more once we have them.

Could you tell us a bit more about the exact hardware you're using?
Specifically whether it is a laptop or a desktop, and which GPU you are using, which driver, and what graphics API the games you play are using (DX11, DX12, Vulkan, OpenGL etc)

Some newer games that use D3D12 may have specific counters that we don't yet check for

**Comment by 1111Al** [comment]
Pending for the next switch, I can say that it happens not only with games, but with any program/window in full screen mode, browser or photo eding or other software it is. Basically that option doesn't work here. Mine is an old AIO PC with a low-power nVidia gt280 graphics card, last drivers of 2017. Dxdiag = DirectX 12.

**Comment by Spiritreader** [comment]
Full screen Mode is not supposed to stop theme switches.

It only measures GPU usage and determines whether a theme switch should be postponed.
