### ISSUE TITLE
App Color Issue

### ISSUE THREAD

**Issue by griggril000** [AutoDarkMode/Windows-Auto-Night-Mode#709]
**Describe what issue or improvement you have with the usability design**
I clicked on one setting in the app and almost everything turned white.
<img width="634" alt="image" src="https://user-images.githubusercontent.com/8701691/232363612-2f37c258-68f6-45ad-b0e7-f7868735ac74.png">

**Describe how you would like to see it improved**

**Additional context**

**Comment by Spiritreader** [comment]
please check if that is fixed on the beta branch

**Comment by DRKSLV** [comment]
yes!
i had the same issue when using "force .. theme"
apps had trouble refreshing after the theme changes, including autodark mode itself

in beta this is thenkfully fixed, and actually works!!
