### ISSUE TITLE
Update notifications are in German when the app is set to English

### ISSUE THREAD

**Issue by tomc128** [AutoDarkMode/Windows-Auto-Night-Mode#711]
### Description

Notifications that Auto Dark Mode has an update are sent in German, when the language in the app settings menu is set to English. This is persistent, i.e. every time I start my system I get the notification, and it is always in German.

### Expected Behavior

The notification should follow the language set in settings.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11313614/service.log)
[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11313616/config.yaml.txt)

### Commit Hash, Version and Windows Build

- Commit: `ac5f815`
- Service/App: `10.3.1.34`
- Updater: `2.5.2`
- Shell: `1.3.2.0`
- .Net: `7.0.1`
- Windows: `22624.1616`

### Screenshots / Videos

![Notification](https://user-images.githubusercontent.com/43298139/234087082-9f946266-3589-4045-bae3-895fd47d607b.png)
![Settings](https://user-images.githubusercontent.com/43298139/234087110-c77117ac-9f2b-4b4b-929d-0745ea4b19f7.png)

**Comment by Spiritreader** [comment]
That is Dutch.

The UI culture in the service is set to NL.
This happens when the language is changed but the service is never restarted.

Set the language to any other language than English, and click restart
Then set the language back to English and click restart again.
