### ISSUE TITLE
ADM doesnt switch theme

### ISSUE THREAD

**Issue by Rediupside** [AutoDarkMode/Windows-Auto-Night-Mode#717]
### Description

ADM worked fine for me a pretty long time but recently it stopped working out of nowhere. Reinstalling it also didnt help.

### Expected Behavior

ADM should change my theme when i click "toggle theme" and it should also do it to the time ive set it up to.
ADM doesnt switch themes at all, not time based and neither manually.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11359710/service.log)

Uploading the config didnt work

### Commit Hash, Version and Windows Build

Edition	Windows 11 Pro
Version	22H2
Installed on	‎10/‎12/‎2022
OS build	22623.741
Experience	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by Spiritreader** [comment]
On the 5th of April you have disabled automatic theme switching.

2023-04-05 21:41:17 | Info | ModuleTimer.DeregisterModule: deregistered TimeSwitchModule from timer main 

Please rename the config file to config.txt and upload it

**Comment by Rediupside** [comment]
Hello, thanks for the fast response!

making a copy of ADMTheme.theme so that they were recreated by ADM helped, its working now.
So it seemes that the theme got corrupted somehow.

Thanks for the help!

**Comment by Spiritreader** [comment]
> Hello, thanks for the fast response!
> 
> making a copy of ADMTheme.theme so that they were recreated by ADM helped, its working now. So it seemes that the theme got corrupted somehow.
> 
> Thanks for the help!

Hey, thanks for the update.
Would you be able to upload that theme file so we can take a look at it?
10.3 actually has a mechanism that should restore corrupted theme files, so if it's a previously unknown case then we might be able to use it to improve that behavior.

**Comment by Rediupside** [comment]
Yea sure! 
[Corrupted_ADMTheme.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11359949/Corrupted_ADMTheme.txt)

**Comment by Spiritreader** [comment]
Yep, the theme file is indeed corrupted as you suspected.

an ini file section definition was missing
![image](https://user-images.githubusercontent.com/18438899/235321300-173e8664-9e59-4073-b780-49db12e23304.png)

I've seen this happen when ADM is reading a theme file during the exact time that it is written to.
I might be able to use that to prevent it.
Thanks!

**Comment by Rediupside** [comment]
Alright, very interesting. 
I'm glad that I might helped a bit ! 

And thank you very much for your help! I wouldnt even have thought of recreating the theme! So thank you!

**Comment by Spiritreader** [comment]
> And thank you very much for your help! I wouldnt even have thought of recreating the theme! So thank you!

It's a really tough case because Windows just doesn't report anything wrong if a corrupted theme file is applied.
That's why in those cases where everything looks alright I always recommend recreating the theme files and documenting the entire process to see where in the chain an issue appears!

Glad that this resolved your issue though!

**Comment by Rediupside** [comment]
Well im not really in the position to make any decisions, but if this happends more frequently, maybe a "recreate theme" button or something like that would be helpful. But if it actually doesnt happen frequently I guess it's alright to do it that way.

**Comment by Spiritreader** [comment]
> Well im not really in the position to make any decisions, but if this happends more frequently, maybe a "recreate theme" button or something like that would be helpful. But if it actually doesnt happen frequently I guess it's alright to do it that way.

Something like that probably won't make it into ADM. But not because it is a bad idea. Rather, Auto Dark Mode should do that automatically with no input required from the user. 
I think with better ini file validation we can minimize the issue or resolve it altogether.

**Comment by Rediupside** [comment]
I wish you luck with finding a good working solution then!
And thanks again for helping this fast!
Just wanna let you know that I really love ADM!

I wish you nice day! :D

**Comment by Spiritreader** [comment]
Thanks!
Glad to be of help!

Since your issue is resolved, I shall close this issue as completed!
