### ISSUE TITLE
Customizable events on theme switch

### ISSUE THREAD

**Issue by cah42** [AutoDarkMode/Windows-Auto-Night-Mode#724]
I am a happy user of AutoDarkMode,  using hotkeys to switch between light and dark.

However, some of my core applications, eg. WezTerm, does not follow the system theme, but has its own configuration file. I then run a dark.bat with a content like:
 ```bash
sed -i "/color_scheme = 'VSCodeLight+ (Gogh)',/ccolor_scheme = 'VSCodeDark+ (Gogh)'," c:\users\myself\.wezterm.lua`
```
to replace the theme configuration in the config file from light the dark.

Instead of this manuel process, it would be grand, if we had the possibility to fill out two custom events, SwitchToLightEvent and SwitchToDarkEvent. Each maybe just a edit we could fill out with a custom command or path to a bat with the commands needed to complete the theme switch fully.

**Comment by Spiritreader** [comment]
I'm sorry, but I don't fully understand what you mean with custom events. Could you explain a bit more?

It seems like what you're doing should be possible with our script engine though:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts

**Comment by cah42** [comment]
Sorry for the late response! I totally missed your reply.

Custom scripts is exactly what I was looking for.  Thanks for pointing me in that direction.
