### ISSUE TITLE
this string is hardcoded? (Personalization -> Color Accent)

### ISSUE THREAD

**Issue by pc-v2** [AutoDarkMode/Windows-Auto-Night-Mode#729]
### Question
as the image say

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/58063311/c945b22c-5b91-4de9-b64c-e200ed5c3794)

**Comment by Spiritreader** [comment]
That's correct.

**Comment by Spiritreader** [comment]
should be available now.
