### ISSUE TITLE
Night mode does not need to be turned on

### ISSUE THREAD

**Issue by acolasialiuliu** [AutoDarkMode/Windows-Auto-Night-Mode#730]
In Win11, it has been said that a distinction has been made between light and dark colors, and at the same time, when the tool switches to dark colors, it will turn on the night mode together, causing the screen to yellow. Night mode is not needed, or it can be controlled individually whether it is needed

**Comment by Spiritreader** [comment]
I'm not really sure what you're trying to say, but Auto Dark Mode does not enable Night mode. It can't, it is only able to read the night light state, not set it.

**Comment by acolasialiuliu** [comment]
已经修复了，感谢
