### ISSUE TITLE
System Explorer Can`t follow Application settings

### ISSUE THREAD

**Issue by AkarinLiu** [AutoDarkMode/Windows-Auto-Night-Mode#731]
### Description

I using the is Application, but Taskbar and Windows Explorer not Follow the Application setting.

### Log Data

AutoThemeSwitchingEnabled: true
Autostart:
  Validate: true
WindowsThemeMode:
  Enabled: false
  DarkThemePath: 
  LightThemePath: 
  MonitorActiveTheme: false
AppsSwitch:
  Enabled: true
  Component:
    Mode: Switch
SystemSwitch:
  Enabled: true
  Component:
    Mode: Switch
    TaskbarSwitchDelay: 1200
    TaskbarColorOnAdaptive: false
    TaskbarColorWhenNonAdaptive: Light
ColorFilterSwitch:
  Enabled: false
  Component: {}
OfficeSwitch:
  Enabled: true
  Component:
    Mode: Switch
    LightTheme: 5
    DarkTheme: 4
Sunrise: 2023-05-29T18:00:00.0000000
Sunset: 2023-05-29T06:00:00.0000000
Location:
  PollingCooldownTimeSpan: 1.00:00:00
  Enabled: true
  UseGeolocatorService: true
  SunsetOffsetMin: 0
  SunriseOffsetMin: 0
  CustomLat: 0
  CustomLon: 0
Tunable:
  BatterySliderDefaultValue: 25
  DisableEnergySaverOnThemeSwitch: false
  UseLogonTask: false
  Debug: false
  DebugTimerMessage: false
  ShowTrayIcon: true
  UICulture: zh
GPUMonitoring:
  Enabled: false
  Threshold: 30
  MonitorTimeSpanMin: 1
  Samples: 1
Events:
  DarkThemeOnBattery: false
  SystemResumeTrigger: true
Hotkeys:
  Enabled: false
  ForceLightHotkey: 
  ForceDarkHotkey: 
  NoForceHotkey: 
WallpaperSwitch:
  Enabled: false
  Component:
    TypeLight: Individual
    TypeDark: Individual
    Position: Fill
    GlobalWallpaper:
      Light: 
      Dark: 
    SolidColors:
      Light: '#FFFFFF'
      Dark: '#000000'
    Monitors: []
Updater:
  AutoInstall: false
  Enabled: true
  Silent: false
  DaysBetweenUpdateCheck: 7
  CheckOnStart: false
  VersionQueryUrl: 
  DownloadBaseUrl: 
  ZipCustomUrl: 
  HashCustomUrl: 

### Commit Hash, Version and Windows Build

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

**Comment by Spiritreader** [comment]
Hello, are you using Windows 10?

**Comment by Armin2208** [comment]
Please Update Auto Dark Mode to Version 10.3 - thanks!
