### ISSUE TITLE
Add option to disable theme switching while some process is running.

### ISSUE THREAD

**Issue by pohuing** [AutoDarkMode/Windows-Auto-Night-Mode#733]
**Describe the enhancement or feature you'd like**
Option to disable switching if certain programs are running.

**Describe alternatives you've considered**
The idle switch and the low GPU usage switches. 

**Additional context**
The low GPU usage threshold does not work on my AMD GPU, because it's either too beefy, or the sampling is just broken(AMD reports null for sensors occasionally, so this isn't an issue with this application itself).
Furthermore, the GPU load threshold is inadequate for some scenarios:
I don't mind if my system switches while watching videos, or doing a render, or streaming per se. In those situations the frame drops are irrelevant, yet would be prevented by GPU usage. 
On the other side, plenty of timing specific games use very little resources, such as League of Legends, Counter Strike, any roguelike really, similar for a lot of fighting games like Rivals of Aether.

**Comment by Armin2208** [comment]
Idea: don't switch while Game Mode is activated as an additional option for the "Don't switch while playing video games" setting.

**Comment by pohuing** [comment]
I don't know anyone who uses Game Mode to be honest. Having a list of processes to block the switching sounds the most straight forward to me.
Also, I'm not aware of an API to actually check if it's active. The docs are pretty lackluster and the only somewhat related API I can find has been deprecated for years now.

**Comment by pohuing** [comment]
I'll take a shot at implementing this myself. I'm not very familiar with WPF and C# anymore though.

**Comment by Armin2208** [comment]
Every gamer uses Windows Game Mode, because it's enabled by default for every game. People need to opt out of Game Mode to have it disabled.

But you are right, listening if game mode is activate is not good documented. PowerToys uses a method in Always on Top.
![grafik](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/32982430/6eee864c-0986-4e51-84ea-fcfe0860b660)

Btw thanks for your pull request!

**Comment by Spiritreader** [comment]
Your implementation is now available in the latest beta.

**Comment by pohuing** [comment]
Was fun working on this, thanks for the quick help!
