### ISSUE TITLE
Request --- Notion in README about JasonWei512 Visual-Studio-Auto-Theme-Switcher-for-Win10-Dark-Mode and if possible collaboration

### ISSUE THREAD

**Issue by claudiusraphael** [AutoDarkMode/Windows-Auto-Night-Mode#739]
**Describe the enhancement or feature you'd like**
Visual Studio does not allow for automatic theme switching before the 2022 release and even in the 2022 release while offering "system" as the target for auto-theme-switching it defaults to the classic blue-theme at daytime and this can not be changed via options.

After several attempts and one finally successful kind of brute-force attempt by using different search engines in different browsers on different operating-systems after 40 minutes i found a StackOverflow-question which in the sole answer given referred to [Visual-Studio-Auto-Theme-Switcher-for-Win10-Dark-Mode](https://github.com/JasonWei512/Visual-Studio-Auto-Theme-Switcher-for-Win10-Dark-Mode).

This helper is the perfect companion to [Windows-Auto-Night-Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) - please consider a notion of it in your README.

If you find it to your liking and you think a collaboration would be possible let me encourage you to do so hereby.

I tested the extension in VS 2017 / 2019 / 2022 and it works flawlessly under Windows 10 Home/Pro/LTSC as well as Windows 11 Home/Pro, same as Windows-Auto-Night-Mode does.

**Describe alternatives you've considered**
I simply wasn't able to find any alternatives to this specific request/enhancement.

**Additional context**
I opened an issue [Do not be shy about this awesome helper --- Ask for notion in AutoDarkMode Windows-Auto-Night-Mode](https://github.com/JasonWei512/Visual-Studio-Auto-Theme-Switcher-for-Win10-Dark-Mode/issues/4) - to offer a simple meeting space/common ground for a contact between the authors of both projects and let both know about my "desire". 

Thanks for sharing your awesome helper, it is tremendously helpful and i am sure offering the Visual Studio Theme Switch i mentioned via your theme-switcher for Windows 10/11 would enrich the experience and make much more users life much easier.

**Comment by Spiritreader** [comment]
Sure we can add a reference.

It probably would make the most sense in our wiki, similar to how we've recommended DarkReader
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki

**Comment by Armin2208** [comment]
And in our Wiki there is already a extension for Visual Studio linked 

[](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Apps-with-Auto-Dark-Mode-support)

**Comment by Spiritreader** [comment]
Oh yea didn't see that we already have the exact same one in. Guess this issue is resolved,

**Comment by claudiusraphael** [comment]
Okay just checked again the Wiki. The thing is that the search does not ping a result for "Visual Studio", so i was going through the Wiki-Pages and this time did not ignore the "Apps with Auto Dark Mode support" and found indeed the Plugin.

Maybe it is because english is not my native language, but i interpreted "Apps with Auto Dark Mode support" as apps that support explicitly your own helper, namely "Windows-Auto-Nightmode" as it comes up as "Auto Dark Mode" and "AutoDarkMode" respectively in search engines, hence the confusion.

Maybe you can have a look into it again and pinpoint why "Visual Studio" does not return a result in the Wiki-search - i assume it refers only to titles - if so, expanding the wiki-entry into a list with separate points and titles for each app might be worthwhile, or add "Plugins" into the title alongside Apps, that might do the trick.

I'd still love to see you consider an integration although - as in: "an option for automatic installation of the Visual Studio plugin" in the installer for "Windows-Auto-Night-Mode" or as an option to install from the settings of "Windows-Auto-Night-Mode" or alternatively the reference-list you (as i know now) have in this Github-repo in the wiki under "Apps with Auto Dark Mode support" embedded into the "Windows-Auto-Night-Mode"-settings.

Reference for users stumbling over this issue looking for the link to the plugin: It is mentioned in the wiki under "[Apps with Auto Dark Mode support](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Apps-with-Auto-Dark-Mode-support)"

**Comment by Spiritreader** [comment]
Anything that has a "use system setting" option has Auto Dark Mode support, because respecting the system theme in a globally accessible api by windows is the best way to deal with it.

> an option for automatic installation of the Visual Studio plugin" in the installer for "Windows-Auto-Night-Mode" or as an option to install from the settings of "Windows-Auto-Night-Mode" 

Shipping binaries is a no from a software licensing perspective. 

The reason why we tend to not include links in the software (with the exception of dark reader) is that they need to be vetted and if one goes down you have a dead link. 
At best we could include link to our wiki like we have with dark reader. 

The wiki doesn't allow searching that way because it is not indexed. To fix that you would need to self-host one, like Wiki.js or sth that suppose elasticsearch, which is out of scope for this project. 

I don't really have time to work on sth outward-facing right now as I'm really busy. My main focus is to ensure ADM functions at all in the current windows ecosystem in the spare time I can dedicate towards the project. 

Maybe @Armin2208 can help you out.

**Comment by claudiusraphael** [comment]
Thanks @Spiritreader for getting back on this with your clarifications. I fully understand the reasoning, just wanted to have it mentioned due to the fact that in reality there simply is only this one reliable trinity of AutoDarkMode/Windows-Auto-Night-Mode + Dark Reader + Visual Studio auto Theme Switcher that actually works (mostly: looking at you Bing, you absolute radiance ...).

Appreciate the details!
