### ISSUE TITLE
Disable program updates

### ISSUE THREAD

**Issue by Detsle** [AutoDarkMode/Windows-Auto-Night-Mode#741]
### Description

Good afternoon, I really liked the first version of your program, but that's just the trouble, it asks for updates every time. Could you please help and disable this request for me?

### Log Data

-

### Commit Hash, Version and Windows Build

1.0.0.0

### Screenshots / Videos

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/22348086/13756940-68ef-4d00-923b-2058b8e85924)

**Comment by Pipixel** [comment]
https://learn.microsoft.com/en-us/windows/security/operating-system-security/network-security/windows-firewall/create-an-outbound-program-or-service-rule this link will probably help you

**Comment by Spiritreader** [comment]
Hey!

The first version of ADM is unmaintained and we will no longer make any changes to it.

You're probably better off removing the update check yourself by cloning the release-3.0 branch and building yourself, or block outgoing internet connections as @Pipixel suggested.

Closing this as issues are only meant for supported versions only.
