### ISSUE TITLE
Not correctly change theme Windows 11 

### ISSUE THREAD

**Issue by TheFlash200406** [AutoDarkMode/Windows-Auto-Night-Mode#752]
### Description

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/81970364/f1ca9aad-02f7-4cb8-b8a5-9bfa4b883d88)

### Expected Behavior

Your app is so great but I think you should fix this, is a bit annoying

### Log Data

When theme changes, the start settings app is not corrrect with them, hope you fix it please 

### Commit Hash, Version and Windows Build

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/81970364/edaddf1f-bbdc-4c4c-9d4f-be95cfac55d4)

### Screenshots / Videos

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/81970364/fd38205b-c47d-4938-adb6-e7957a30b244)

**Comment by Armin2208** [comment]
no added version details, no detailed information. We will not look into this.

**Comment by Spiritreader** [comment]
Hey! 
To provide a bit more insight.

This is a known Windows issue and is related to the API.
It is also listed in our known issues and limitations section:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Known-limitations#general

```
The loading splash-screen color of UWP/native Windows Apps is not updating correctly.
```

Nothing we can do about that unfortunately, except for waiting until Microsoft's theming API becomes more stable and/or public.
