### ISSUE TITLE
Location / time data update broken for the last 2-3 months.  

### ISSUE THREAD

**Issue by flobo09** [AutoDarkMode/Windows-Auto-Night-Mode#754]
### Description

For the last few months, location data had stopped updating, meaning it ALWAYS stays on the location and light and dark time of the moment was application was originally installed. 

It never updates after installation. I originally thought it was a minor bug on my device but since i can reproduce it on any device i install the app to, i do believe it has to be a bug. 

### Expected Behavior

Should update daily. 

Never updates. 

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/12246932/service.log)
[config.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/12246937/config.log)

### Commit Hash, Version and Windows Build

- Commit: `06db52b`
- Service/App: `10.4.0.26`
- Updater: `3.1.4`
- Shell: `1.3.2.0`
- .Net: `7.0.5`
- Windows: `23516.1000`

But it's happening on 3 devices (production / dev / canary), and all versions of the app.

### Screenshots / Videos

Desktop device: app reinstalled on 15/7, always stays on that : 
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/41547109/6282b5d7-9ce1-417d-8ae6-d45a33d4a343)
Surface Pro 5 : app installed on 11/6, always stays on that: 
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/41547109/f5cb6223-a870-406b-959b-a464e45998a7)
Brand new Ultrabook bought last week, always stay on 31/07 :  
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/41547109/ea71c38d-f202-41f6-b406-d793e4e34827)

**Comment by flobo09** [comment]
I have an hunch that somehow, something is messed up with timezone management and the "next update" time is created in the past at installation. 

Could be fully wrong though.

**Comment by Spiritreader** [comment]
> I have an hunch that somehow, something is messed up with timezone management and the "next update" time is created in the past at installation.
> 
> Could be fully wrong though.

I don't think that's the case, otherwise it would only happen on dev. There is no timezone management in 10.3

**Comment by Spiritreader** [comment]
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/commit/9aa1ef6211c3974a5722b4cb6b6a83b3a00cab8e

I have accidentally removed the Geopositioning update module from the warden.
However that happened in the latest beta 2 months ago and not on the stable 10.3 release.

In any case good catch, thanks for the report!
Fix and new beta build is coming shortly

**Comment by flobo09** [comment]
My bad, i thought i had one on stable but i guess not ! :)

**Comment by Spiritreader** [comment]
> My bad, i thought i had one on stable a few weeks back but i guess not ! :)

No worries!
New beta build is up, please let me know if you still run into issues!

**Comment by zhenjie1999** [comment]
10.3.0.90 look like have this same problem. Not sure is because of the latest windows update.

**Comment by Spiritreader** [comment]
> 10.3.0.90 look like have this same problem. Not sure is because of the latest windows update.

The cause is most likely a different one.
you can update to 10.4 and see if it disappears, but on 10.3 the only point of failure would be the windows geolocation api.
