### ISSUE TITLE
Delay gets added to custom time

### ISSUE THREAD

**Issue by mangoepic** [AutoDarkMode/Windows-Auto-Night-Mode#755]
### Description

Time delay from sunset got added to the custom time

### Expected Behavior

it doesn't get added

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/12324715/service.log)

### Commit Hash, Version and Windows Build

Windows 10 Home 22H2

### Screenshots / Videos

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/71931749/467e216b-4a7c-4bac-be2b-76a0ca9cae6e)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/71931749/c8fb1a21-0184-4663-a4b3-c63a5d7a7136)

**Comment by Spiritreader** [comment]
Hey, thanks for the report.

We know about this, and it's fixed already on the beta branch!
We can't push to stable yet because we're awaiting a signing certificate from Microsoft.

I recommend updating to beta, it's basically the finished 10.4 release.
