### ISSUE TITLE
there was an issue with the UI

### ISSUE THREAD

**Issue by xc1984759471** [AutoDarkMode/Windows-Auto-Night-Mode#756]
### Description

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/53083866/2be61775-de9a-48f4-aee9-89ccd81398e0)

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/12327442/service.log)
[Uploading config.yaml…]()

### Commit Hash, Version and Windows Build

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/53083866/59f12b49-8513-4398-badd-5be022ac0768)

**Comment by Spiritreader** [comment]
Hey!

If the Management Event Watcher can't be initialized, usually restarting the computer will fix it.

However please note that you're currently on a Windows build that is unsupported.
