### ISSUE TITLE
"Underline access keys" is enabled when opening Auto Dark Mode

### ISSUE THREAD

**Issue by Zlypkorp** [AutoDarkMode/Windows-Auto-Night-Mode#757]
### Description

When opening Auto Dark Mode the "Underline access keys" feature is enabled showing a dark/white border on context menus or other menus. It gets enabled even when in Windows settings the switch is disabled, if I enable and then disable "Underline access keys" the border dissapears.

### Expected Behavior

Opening the app should not enable this feature.

### Log Data

[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/12327976/config.yaml.txt)
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/12327977/service.log)

### Commit Hash, Version and Windows Build

- Commit: `b89e0c2`
- Service/App: `10.4.0.27`
- Updater: `3.1.4`
- Shell: `1.3.2.0`
- .Net: `7.0.5`
- Windows: `22621.2134`

### Screenshots / Videos

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/5231929/ac951bbf-c55d-4ed0-99ac-f33272963feb)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/5231929/bbf6d393-e300-41f2-b3fa-941fed76af97)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/5231929/e2d4796d-45f6-45c8-903a-4401a48d9bd7)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/5231929/9c60a3eb-d73f-4452-ae0f-751e0015fb51)

**Comment by Spiritreader** [comment]
Hmm, I can't really reproduce that behavior.
I get those borders regardless of whether the setting is enabled or not.

The only thing the underline access keys is doing is, changing whether you get a small underline on letters that are used as access keys.

However, it's correct that ADM shouldn't enforce that setting on users without alternative, so I will remove the auto-set.
