### ISSUE TITLE
The command line

### ISSUE THREAD

**Issue by H5820121** [AutoDarkMode/Windows-Auto-Night-Mode#758]
>Syntax: AutoDarkModeShell.exe [--<command>] [(optional) timeout-value]

Can you please give an example of the use of ` timeout`?
(I mean how should I write it exactly).

Thanks!

**Comment by Spiritreader** [comment]
Example with 2 second timeout:

```AutoDarkModeShell.exe --alive 2```

You just specify the timeout value after your command.
If you want to start Auto Dark Mode with a timeout different from the default 5s, just specify the command as well

```AutoDarkModeShell.exe --alive --and-launch-service 2```

**Comment by H5820121** [comment]
Could you please add an explanation of what exactly this parameter does?

**Comment by Spiritreader** [comment]
The timeout?
It's how long the shell waits for a response from the service.
