### ISSUE TITLE
ADM's bug on the SurfaceBook: cannot save settings

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [AutoDarkMode/Windows-Auto-Night-Mode#760]
### Description

After opening ADM, configure the time on the homepage, and then switch to any other tab, a prompt will pop up: Sorry, we can't save your settings
**But one interesting thing is that although ADM says that it cannot be saved, what I set up before still works fine after closing the pop-up**

### Expected Behavior

ADM should save my settings
**But it didn't do this :(((**

### Log Data

config: https://paste.ubuntu.com/p/28FbhNDbw7/
logs: https://paste.ubuntu.com/p/Xt7XDWWRTY/

### Commit Hash, Version and Windows Build

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/71379165/113d210e-acf6-44e8-a9fd-7cfaad5be25c)

### Screenshots / Videos

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/71379165/5a0e1d6e-3c46-4d6c-b9bc-a531815b76a1)

**Comment by Spiritreader** [comment]
Hello, you're using an outdated version of Auto Dark Mode.
Please update to the latest beta.

**Comment by xiaoyueyoqwq** [comment]
> 

Got it, thanks for helping ;)
