### ISSUE TITLE
Mouse pointer is reset to the default one when the theme is changed.

### ISSUE THREAD

**Issue by ArKeid0s** [AutoDarkMode/Windows-Auto-Night-Mode#762]
### Description

Mouse pointer is reset to the default one when the theme is changed.

### Expected Behavior

ADM should not reset the mouse pointer on theme switching

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/12504563/service.log)
Config: `AutoThemeSwitchingEnabled: true
Autostart:
  Validate: true
WindowsThemeMode:
  Enabled: true
  DarkThemePath: C:\Windows\Resources\Themes\dark.theme
  LightThemePath: C:\Windows\Resources\Themes\aero.theme
  MonitorActiveTheme: false
AppsSwitch:
  Enabled: true
  Component:
    Mode: Switch
SystemSwitch:
  Enabled: true
  Component:
    Mode: Switch
    TaskbarSwitchDelay: 1200
    TaskbarColorOnAdaptive: false
    TaskbarColorWhenNonAdaptive: Light
ColorFilterSwitch:
  Enabled: false
  Component: {}
OfficeSwitch:
  Enabled: false
  Component:
    Mode: Switch
    LightTheme: 0
    DarkTheme: 4
Sunrise: 2023-08-20T07:00:00.0000000
Sunset: 2023-08-20T20:00:00.0000000
Location:
  PollingCooldownTimeSpan: 1.00:00:00
  Enabled: true
  UseGeolocatorService: true
  SunsetOffsetMin: 0
  SunriseOffsetMin: 0
  CustomLat: 0
  CustomLon: 0
Tunable:
  BatterySliderDefaultValue: 25
  DisableEnergySaverOnThemeSwitch: false
  UseLogonTask: false
  Debug: false
  DebugTimerMessage: false
  ShowTrayIcon: true
  UICulture: en
GPUMonitoring:
  Enabled: false
  Threshold: 30
  MonitorTimeSpanMin: 1
  Samples: 1
Events:
  DarkThemeOnBattery: false
  SystemResumeTrigger: true
Hotkeys:
  Enabled: false
  ForceLightHotkey: 
  ForceDarkHotkey: 
  NoForceHotkey: 
WallpaperSwitch:
  Enabled: false
  Component:
    TypeLight: Individual
    TypeDark: Individual
    Position: Fill
    GlobalWallpaper:
      Light: 
      Dark: 
    SolidColors:
      Light: '#FFFFFF'
      Dark: '#000000'
    Monitors: []
Updater:
  AutoInstall: true
  Enabled: true
  Silent: true
  DaysBetweenUpdateCheck: 7
  CheckOnStart: false
  VersionQueryUrl: 
  DownloadBaseUrl: 
  ZipCustomUrl: 
  HashCustomUrl: 
`

### Commit Hash, Version and Windows Build

Commit: 5e6ea8a
Version: 10.1.0.10
Windows: 11 22H2 22621.2134

**Comment by Armin2208** [comment]
You are using an old version of Auto Dark Mode. Please update.
