### ISSUE TITLE
What is "Always refresh DWM on theme switch"?

### ISSUE THREAD

**Issue by kazerniel** [AutoDarkMode/Windows-Auto-Night-Mode#769]
### Question
I see this new option appeared in v10.4. What is the effect of this setting? Benefits/drawbacks?

(Google says DWM is Desktop Window Manager, but nothing about why I would enable or disable that option.)

**Comment by Spiritreader** [comment]
If you select it, it will provide an explanation for you.

**Comment by kazerniel** [comment]
Thanks!
