### ISSUE TITLE
10.4.0 is unavailable for download via winget?

### ISSUE THREAD

**Issue by shal0l** [AutoDarkMode/Windows-Auto-Night-Mode#770]
### Description

> With 10.4, we've improved the update system and made it more future proof. Because this introduced incompatibilities with the old system, you can't use the automatic updater if you are on version 10.3. In this case, just download the installer below and re-install Auto Dark Mode.

Is winget is no longer available? Or it just takes time to get updated?

**Comment by Spiritreader** [comment]
The winget package is/was maintained by the community and not by us.
It has not been updated to 10.4 yet.
