### ISSUE TITLE
Inconsistent version display causes winget to detect updates

### ISSUE THREAD

**Issue by lvzhenbo** [AutoDarkMode/Windows-Auto-Night-Mode#771]
### Description

I updated the software by downloading the package, but when I use winget to detect the software update, I found that there is an update, and then the local display version number is 10.4.0.0, while the remote version number is 10.4.0.35, the local display version is not the same as the version of the software
![屏幕截图 2023-09-13 171527](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/32427677/882eaa00-177a-4bf2-986f-5305e88bf683)
![屏幕截图 2023-09-13 171912](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/32427677/c2674461-1022-4205-bc3b-79325cac89d0)

### Expected Behavior

winget should not be able to detect the update, the version number should be the version number of the software itself

### Log Data

unnecessary

### Commit Hash, Version and Windows Build

- Commit: `57ef363`
- Service/App: `10.4.0.35`
- Updater: `3.1.4`
- Shell: `1.3.3.0`
- .Net: `7.0.5`
- Windows: `22621.2283`

**Comment by Spiritreader** [comment]
Innosetup does not support build numbers, hence the installer will report 10.4.0.0.

Could you explain what exactly is happening?
If our windows store version is 10.4.0.0, and you have used our updater to update to 10.4.0.35, how is winget telling you to update, if you local version is newer than upstream?

Or am I misunderstanding anything here?

**Comment by lvzhenbo** [comment]
是这样子的，winget是根据软件在windows里注册的版本号检测的，注册的版本号是10.4.0.0，但是winget的软件版本库维护者是根据真实版本号写的，而真实的版本号是10.4.0.35，根据winget的算法是大于注册的版本号，导致软件本身是版本一致，但是winget能够检测到版本更新，就是无论通过winget安装更新多少次都是会一直被检测到更新

**Comment by lvzhenbo** [comment]
10.4.0.35 > 10.4.0.0  update

**Comment by Armin2208** [comment]
Yes, the Auto Dark Mode Setup doesn't set the build number on the version number for the app list. This is why Winget thinks an update for Auto Dark Mode is available, although it isn't.

The integrated Updater of Auto Dark Mode sets the build number for the app list. So after updating via Auto Dark Mode itself, Winget shouldn't detect any updates. And yes, the upgrade from 10.3 to 10.4 required a setup installation. But only once, in the future the Auto Dark Mode Updater will done the job and will not confuse Winget.

**What can you do?**
You can pin Auto Dark Mode on Winget. The pin feature of Winget skips updates for pinned package.
Try using: `winget pin add "Auto Dark Mode"`.
After pinning Auto Dark Mode, it should be on the list `winget pin list`.
You can now safely use winget upgrade without updating Auto Dark Mode.

**What can we do?**
@Spiritreader it seems like InnoSetup has the ability to put the build number in.
[See the InnoSetup documentation, it allows putting four numbers into the versioninfo](https://jrsoftware.org/ishelp/index.php?topic=setup_versioninfoversion).
Maybe you can retry to enable build numbers in future setups?

**Comment by Spiritreader** [comment]
> Yes, the Auto Dark Mode Setup doesn't set the build number on the version number for the app list. This is why Winget thinks an update for Auto Dark Mode is available, although it isn't.
> 
> The integrated Updater of Auto Dark Mode sets the build number for the app list. So after updating via Auto Dark Mode itself, Winget shouldn't detect any updates. And yes, the upgrade from 10.3 to 10.4 required a setup installation. But only once, in the future the Auto Dark Mode Updater will done the job and will not confuse Winget.
> 
> **What can you do?** You can pin Auto Dark Mode on Winget. The pin feature of Winget skips updates for pinned package. Try using: `winget pin add "Auto Dark Mode"`. After pinning Auto Dark Mode, it should be on the list `winget pin list`. You can now safely use winget upgrade without updating Auto Dark Mode.
> 
> **What can we do?** @Spiritreader it seems like InnoSetup has the support for build numbers, at least in the config file. [See the InnoSetup documentation, it allows putting four numbers into VersionInfoVersion](https://jrsoftware.org/ishelp/index.php?topic=setup_versioninfoversion). But it's hard to automate, because it would need a constant change of the version number in the InnoSetup config file? Maybe there are some easier ways of automatization?

Hm aight. Last time I tried it it didn't work, and it just ignored that value, but I can check and try again.

**Comment by aaronliu0130** [comment]
@lvzhenbo the winget thing would be fixed by https://github.com/microsoft/winget-pkgs/pull/120000 .

**Comment by aaronliu0130** [comment]
I don’t think this should be closed, not displaying the build number is still a problem.

**Comment by Spiritreader** [comment]
> I don’t think this should be closed, not displaying the build number is still a problem.

This issue is about winget though.
New stable releases will always have their minor version changed, and on the next release the installer will include the version number again (assuming this works now with inno setup)

**Comment by aaronliu0130** [comment]
It’s a two parter, the WinGet was just a consequence of the version display. If the next release still don’t give the right version number then this should be reopened.
