### ISSUE TITLE
Didn't fully change the app theme from light to dark

### ISSUE THREAD

**Issue by avi12** [AutoDarkMode/Windows-Auto-Night-Mode#772]
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/6422804/6a08121a-465b-4d71-8f30-698f8d3a3527)

**Comment by Spiritreader** [comment]
oh wow that looks like a windows 10 exclusive issue, we have to look into that.

**Comment by GasimGasimzada** [comment]
I have the same issue with Windows 11.

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/807231/a3c962a5-2007-4025-a035-47357d928f22)

**Comment by Spiritreader** [comment]
> I have the same issue with Windows 11 (this is in Dark mode).
> 
> ![image](https://user-images.githubusercontent.com/807231/280416182-a3c962a5-2007-4025-a035-47357d928f22.png)

that's a windows bug though.

**Comment by GasimGasimzada** [comment]
Yeah, I thought this ticket was about the colors when auto switching from light to dark, not about the app's own bug. Sorry about that.

**Comment by HarshdeepSinghChauhan** [comment]
> > I have the same issue with Windows 11 (this is in Dark mode).
> > ![image](https://user-images.githubusercontent.com/807231/280416182-a3c962a5-2007-4025-a035-47357d928f22.png)
> 
> that's a windows bug though.

No, if this was a Windows issue, then why, manually changing between light and dark themes this wrong colour change is absent?
I created a new issue (I did not check this issue) which contains the relevant recording and snapshots.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/845

**Comment by Spiritreader** [comment]
> > > I have the same issue with Windows 11 (this is in Dark mode).
> > > ![image](https://user-images.githubusercontent.com/807231/280416182-a3c962a5-2007-4025-a035-47357d928f22.png)
> > 
> > 
> > that's a windows bug though.
> 
> No, if this was a Windows issue, then why, manually changing between light and dark themes this wrong colour change is absent? I created a new issue (I did not check this issue) which contains the relevant recording and snapshots. #845

Because, once again, we are calling a windows api to perform the theme switch.

If you call a windows api to apply a windows theme and it doesn't work, then Windows is the issue.

We know about it, it's in the list of common problems, there's nothing that can be done for the people that experience it except this:

If you have issues, check always refresh dwm in the settings.

If you want to fix it yourself, feel free to go ahead. But creating the 101st issue on it won't bring any meaningful improvement.

**Comment by avi12** [comment]
Yes, it got resolved

**Comment by Spiritreader** [comment]
Sweet, closing then :)

Let us know if the issue resurfaces, we've been trying to get to the bottom of this for a while for the Win10 build.
There's some components that aren't always hooked to the theme switching event within our UI framework we use for Win10.

**Comment by HarshdeepSinghChauhan** [comment]
> > > > I have the same issue with Windows 11 (this is in Dark mode).
> > > > ![image](https://user-images.githubusercontent.com/807231/280416182-a3c962a5-2007-4025-a035-47357d928f22.png)
> > > 
> > > 
> > > that's a windows bug though.
> > 
> > 
> > No, if this was a Windows issue, then why, manually changing between light and dark themes this wrong colour change is absent? I created a new issue (I did not check this issue) which contains the relevant recording and snapshots. #845
> 
> Because, once again, we are calling a windows api to perform the theme switch.
> 
> If you call a windows api to apply a windows theme and it doesn't work, then Windows is the issue.
> 
> We know about it, it's in the list of common problems, there's nothing that can be done for the people that experience it except this:
> 
> If you have issues, check always refresh dwm in the settings.
> 
> If you want to fix it yourself, feel free to go ahead. But creating the 101st issue on it won't bring any meaningful improvement.
> 
> There was no meaningful difference found when using the cpl compared to invoking methods via CThemeManager.
> 
> Don't forget that ADM is an unofficial, unsupported hack that is actively disapproved by Microsoft.

Understood. Thanks, but I did not know about the lack of official support given that it is a highly-rated app with a big disclaimer about winning the 2022 MS Store App Awards.
