### ISSUE TITLE
Windows 11 compat not complete

### ISSUE THREAD

**Issue by aaronliu0130** [AutoDarkMode/Windows-Auto-Night-Mode#773]
**Describe what issue or improvement you have with the usability design**
1. Hover shade changes immediately instead of fading slightly
2. Every UI element except sections, headers and Mica is wrong (All screenshots are ADM first, official second)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/4b6d9dda-aa00-44f4-ace4-cfe09cb48d32)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/170a08e2-f779-4200-95f7-8ead80e5677c)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/60d9b4be-11e9-4716-a170-909ffb2da5dc)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/4fea60b8-3d22-4440-b373-a0fa8d04557a)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/f77d2d41-4e62-4750-8feb-d96fe488f56f)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/a36687b3-678e-4f4e-bb56-f3c330fe80f9)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/8c99b492-22ae-4dce-913f-021d67710d1a)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/e16b7062-c532-484d-a054-fccace8b62d9)
(I couldn't get a screenshot but hover effects for buttons are also wrong)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/dc77026c-38f3-4c1b-bee2-ee7de78d9da0)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/b13bc7c9-c1cd-43c6-8f66-52e6d345189d)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/5f928485-4f39-46bd-a9b1-f50332e59c42)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/80e80b49-a88d-46c3-9841-572b16723e06)
I couldn't find a reference for the text fields but I'm pretty sure these are also wrong
Sidebars (don't need to have fluent icons but) are... wrong
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/b5159d41-6d4e-4b6d-9deb-839c6a548862)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/11874211/b4be4511-3386-45ca-a5cb-db54cf449240)

3. If possible add a back arrow or favicon to the top left
**Describe how you would like to see it improved**
Make it more like Mica before declaring Windows 11 support to be done

**Additional context**
This is just a minor gripe, this app's UI and UX is still wonderful!

**Comment by Spiritreader** [comment]
Win 11 compat is not supposed to be complete.
Please refer to https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/297
I'll close this as duplicate and link it in the original issue, as we already have an issue for better consistency.

Thanks for your suggestion!
