### ISSUE TITLE
Windows ARM64

### ISSUE THREAD

**Issue by dancewithyourghost** [AutoDarkMode/Windows-Auto-Night-Mode#780]
**Describe the enhancement or feature you'd like**
I need ARM64 version Windows-Auto-Dark-Mode.

**Describe alternatives you've considered**
I'm using x64 version windows-auto-dark-mode. It is very slow and shorten my battery life.

**Additional context**
I'm using a Windows tablet with Qualcomm 8cx gen2 processer, which is ARM64 structure. It is very slow when I using x64 version Windows-Auto-Night-Mode.

**Comment by xgdgsc** [comment]
dup of https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/690
