### ISSUE TITLE
How to Get Sunset/Sunrise Times from Auto Dark Mode using Auto Dark Mode Shell?

### ISSUE THREAD

**Issue by bigplayer-ai** [AutoDarkMode/Windows-Auto-Night-Mode#784]
# How to Get Sunset/Sunrise Times from Auto Dark Mode using Auto Dark Mode Shell?

Hello,

I am using [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode), a tool that automatically switches between dark and light themes on Windows 10. I have configured Auto Dark Mode to follow Windows Night Light, which is a feature that adjusts the color temperature of the screen according to the time of day.

I would like to know how to get the sunset and sunrise times from Auto Dark Mode using [Auto Dark Mode Shell](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Command-line-arguments-%7C-parameters), which is a command-line interface for Auto Dark Mode. I want to use these times for some other tasks that depend on the daylight cycle.

Is this possible? If so, how can I do it? What commands or parameters do I need to use?

I appreciate any help or guidance on this topic. Thank you.

[Auto Dark Mode GitHub](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) | [Auto Dark Mode Shell Documentation](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Command-line-arguments-%7C-parameters)

**Comment by Spiritreader** [comment]
You can't do that with the shell, however in `%AppData%\AutoDarkMode\location_data.yaml` you can find all data related to location and suntime tracking. In the `%AppData%\AutoDarkMode\config.yaml` there are offsets and manual sun times (if set / used).

**Comment by Armin2208** [comment]
You can also listen to the registry key `AppsUseLightTheme` located at`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`
