### ISSUE TITLE
Glitched switching the color of the font on the clock ald the icons (TaskBar)

### ISSUE THREAD

**Issue by popos123** [AutoDarkMode/Windows-Auto-Night-Mode#792]
### Description

Hi, i have problem from about three years.
Always on couple computers, windows 10 and 11 is the same problem - glitched font color, thats don't change witch other UI .
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/43697578/b03164fe-dff3-4aac-969a-307bb222228a)
How to fix that?

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/13268214/service.log)

### Commit Hash, Version and Windows Build

- Commit: `212dbb4`
- Service/App: `10.3.0.90`
- Updater: `2.5.2`
- Shell: `1.3.1.0`
- .Net: `6.0.10`
- Windows: `22631.2506`

**Comment by Armin2208** [comment]
Have you Windows notifications disabled or why you don't know that an update for Auto Dark Mode is available

**Comment by popos123** [comment]
I see, sorry for this, I was updated to 10.4.1 version
