### ISSUE TITLE
AutoDarkMode not refreshing some taskbar icons.

### ISSUE THREAD

**Issue by ZhMster** [AutoDarkMode/Windows-Auto-Night-Mode#793]
### Description

I've noticed that when you switch to light > dark or dark to light, sometimes the icons in taskbar remain their old state. It doesn't happen on Windows Theme changing via settings.

So, i've found a quick fix for it, which is restarting explorer or reloading icon cache (via WinToys, however i don't really think it's necessary).

Can you add a option to allow restarting explorer everytime that changes the theme, with the options: [Never, Ask before, Always]

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/13298466/service.log)
[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/13298471/config.yaml.txt)

### Commit Hash, Version and Windows Build

Windows 10, 22H2 (19045.3636 - Latest Update ATM)

**Comment by Armin2208** [comment]
1) This is an issue of Windows, not Auto Dark Mode. We can't fix this.

2) We will not integrate Explorer restarts into Auto Dark Mode. But you can use this as custom script:  #597
