### ISSUE TITLE
Boot self-start autodarkmode not working

### ISSUE THREAD

**Issue by Qing90bing** [AutoDarkMode/Windows-Auto-Night-Mode#796]
### Description

![动画](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/69203427/07847724-ae7a-4590-820c-6a3ae75509af)

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/13324360/service.log)
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/13324362/config.zip)

### Commit Hash, Version and Windows Build

版本	Windows 11 专业版
版本	23H2
安装日期	‎2023-‎09-‎08
操作系统版本	22635.2700
体验	Windows Feature Experience Pack 1000.22678.1000.0

**Comment by Spiritreader** [comment]
Auto Dark Mode is not allowed to modify registry keys on your system

```
2023-11-11 11:31:46 | Error | RegistryHandler.AddAutoStart: could not add service to autostart UnauthorizedAccessException > Attempted to perform an unauthorized operation. > Void Win32Error(Int32, System.String)
```

Do you have any restrictions in place that would prevent you from performing such an operation?

**Comment by Qing90bing** [comment]
I'm not sure, I tried to add a registry startup item but it didn't work

**Comment by Spiritreader** [comment]
> I'm not sure, I tried to add a registry startup item but it didn't work

Could you try switching over to the task based start mode?
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/18438899/adc569d1-401c-438e-a2bc-7b52c0d31bcb)

**Comment by Spiritreader** [comment]
Great to hear!

There's still an issue with the selection being grayed out and not selectable from the user interface if the normal startup method is not available.

I sadly can't say why there's a permission issue on your system. I've attempted to fix it by checking if the registry key actually exists, maybe that was the issue.

**Comment by Qing90bing** [comment]
It's okay, the problem has been solved. This can be considered a solution, right。

**Comment by Spiritreader** [comment]
Alright, thanks for letting me know! closing this, feel free to reopen if you experience issues again.
