### ISSUE TITLE
The "Taskbar" theme does not change automatically

### ISSUE THREAD

**Issue by jekeam** [AutoDarkMode/Windows-Auto-Night-Mode#797]
### Description

Does not switch the "taskbar", to solve the problem, you have to resize it - only then it changes the theme.

### Expected Behavior

The "Taskbar" theme changes automatically

### Log Data

[log.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/13335616/log.zip)

### Commit Hash, Version and Windows Build

- Commit: `cf7a0fe`
- Service/App: `10.4.1.1`
- Updater: `3.1.4`
- Shell: `1.3.3.0`
- .Net: `7.0.5`
- Windows: `19045.3636`

### Screenshots / Videos

https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/19660852/973ba5fc-c68c-4a2a-a185-d7e5e9ef83d4

**Comment by robertow83** [comment]
Same issue. Resolved as OP advised. GPU in overdrive while taskbar is 'light' in 'dark' mode — fans spin down when the taskbar is resized and 'fixed'.

**Comment by Armin2208** [comment]
Please update Auto Dark Mode to 10.4 and try again.

**Comment by Armin2208** [comment]
> Same issue. Resolved as OP advised. GPU in overdrive while taskbar is 'light' in 'dark' mode — fans spin down when the taskbar is resized and 'fixed'.

what do you mean with gpu overdrive?

**Comment by robertow83** [comment]
> > Same issue. Resolved as OP advised. GPU in overdrive while taskbar is 'light' in 'dark' mode — fans spin down when the taskbar is resized and 'fixed'.
> 
> what do you mean with gpu overdrive?

Currently on:
_Commit: `cf7a0fe`
Service/App: `10.4.1.1`
Updater: `3.1.4`
Shell: `1.3.3.0`
.Net: `7.0.5`
Windows: `19045.3693`_

The fans ramp up and are consistently at a high RPM when the switchover happens - just an observation, might not be related; but happens when going light > dark (and remains high rpm until taskbar in dark mode)

**Comment by Armin2208** [comment]
> The fans ramp up and are consistently at a high RPM when the switchover happens - just an observation, might not be related; but happens when going light > dark (and remains high rpm until taskbar in dark mode)

How long does the transition take?

**Comment by robertow83** [comment]
> > The fans ramp up and are consistently at a high RPM when the switchover happens - just an observation, might not be related; but happens when going light > dark (and remains high rpm until taskbar in dark mode)
> 
> How long does the transition take?

Windows/Apps - within seconds; taskbar text changes as expected, but colour doesn't change until (l > d) unless bar resized. Would a log help in addition to OPs log?

**Comment by Armin2208** [comment]
> Windows/Apps - within seconds; taskbar text changes as expected, but colour doesn't change until (l > d) unless bar resized. Would a log help in addition to OPs log?

Sure, your log would be also nice.

**Comment by jekeam** [comment]
> Please update Auto Dark Mode to 10.4 and try again.

Already have version latest [10.4.1.1](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.4.1.1), are you suggesting I do a downgrade to == [10.4.0.35](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.4.0.35)?

**Comment by Armin2208** [comment]
> > Please update Auto Dark Mode to 10.4 and try again.
> 
> I already have version latest [10.4.1.1](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.4.1.1), are you suggesting I do a downgrade to == [10.4.0.35](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.4.0.35)?

no i am NOT suggesting a downgrade, sorry

**Comment by jekeam** [comment]
> no i am NOT suggesting a downgrade, sorry
The problem occurred in an earlier version, which resulted in me upgrading to the latest version. But by the way, I haven't noticed it for the last few days, it seems to have self-corrected.

**Comment by jekeam** [comment]
The problem disappeared, what exactly it was was not clear.
