### ISSUE TITLE
Dark mode does not apply to dialog windows

### ISSUE THREAD

**Issue by JanHeimsoth** [AutoDarkMode/Windows-Auto-Night-Mode#801]
### Description

I use Wallpaper Engine to manage my desktop look and feel and now I wanted to use ADM to also automatically change the theme. Since windows does not apply the theme to dialogue windows and I read, that ADM could to this I hoped it would. However, for me the dialogue windows stay in light mode no matter what.
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/101802956/1904b562-7351-4306-b09f-488170f559e4)

### Expected Behavior

ADM should change dialogue windows to dark mode as well.
ADM does not do this.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/13493294/service.log)

config file will not upload, so here is the text from it:

AutoThemeSwitchingEnabled: true
Governor: Default
Autostart:
  Validate: true
WindowsThemeMode:
  Enabled: false
  DarkThemePath: C:\Users\Jan\AppData\Local\Microsoft\Windows\Themes\Windows11 Dark.theme
  LightThemePath: C:\Users\Jan\AppData\Local\Microsoft\Windows\Themes\Windows11 Dark.theme
  MonitorActiveTheme: true
  ApplyFlags: []
AppsSwitch:
  Enabled: true
  Component:
    Mode: Switch
SystemSwitch:
  Enabled: true
  Component:
    Mode: Switch
    TaskbarSwitchDelay: 1200
    TaskbarColorOnAdaptive: false
    TaskbarColorWhenNonAdaptive: Light
    DWMPrevalenceSwitch: false
    DWMPrevalenceEnableTheme: Dark
TouchKeyboardSwitch:
  Enabled: true
  Component: {}
ColorizationSwitch:
  Enabled: false
  Component:
    LightHex: '#FF0C3372'
    DarkHex: '#FF0C3372'
    LightAutoColorization: false
    DarkAutoColorization: false
ColorFilterSwitch:
  Enabled: false
  Component: {}
OfficeSwitch:
  Enabled: false
  Component:
    Mode: Switch
    LightTheme: 0
    DarkTheme: 4
CursorSwitch:
  Enabled: false
  Component:
    CursorsLight: 
    CursorsDark: 
Sunrise: 2023-11-28T21:17:00.0000000
Sunset: 2023-11-28T21:46:00.0000000
Location:
  PollingCooldownTimeSpan: 1.00:00:00
  Enabled: false
  UseGeolocatorService: true
  SunsetOffsetMin: 0
  SunriseOffsetMin: 0
  CustomLat: 0
  CustomLon: 0
Tunable:
  BatterySliderDefaultValue: 25
  DisableEnergySaverOnThemeSwitch: false
  UseLogonTask: false
  Debug: false
  Trace: false
  DebugTimerMessage: false
  ShowTrayIcon: true
  AlwaysFullDwmRefresh: true
  UICulture: en
GPUMonitoring:
  Enabled: false
  Threshold: 30
  Samples: 1
ProcessBlockList:
  ProcessNames: []
  Enabled: false
Events:
  DarkThemeOnBattery: false
  Win10AllowLockscreenSwitch: false
Notifications:
  OnAutoThemeSwitching: true
  OnSkipNextSwitch: true
AutoSwitchNotify:
  Enabled: false
  GracePeriodMinutes: 5
Hotkeys:
  Enabled: false
  ForceLight: 
  ForceDark: 
  NoForce: 
  ToggleTheme: 
  TogglePostpone: 
  ToggleAutoThemeSwitch: 
IdleChecker:
  Enabled: false
  Threshold: 5
WallpaperSwitch:
  Enabled: false
  Component:
    TypeLight: Individual
    TypeDark: SolidColor
    Position: Fill
    GlobalWallpaper:
      Light: 
      Dark: 
    SolidColors:
      Light: '#FFFFFF'
      Dark: '#000000'
    Monitors:
    - Id: '\\?\DISPLAY#GSM5B41#5&bffe4cc&0&UID24839#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}'
      LightThemeWallpaper: ''
      DarkThemeWallpaper: ''
Updater:
  AutoInstall: true
  Enabled: true
  Silent: false
  DaysBetweenUpdateCheck: 7
  CheckOnStart: true
  VersionQueryUrl: 
  DownloadBaseUrl: 
  ZipCustomUrl: 
  HashCustomUrl: 

### Commit Hash, Version and Windows Build

- Commit: `cf7a0fe`
- Service/App: `10.4.1.1`
- Updater: `3.1.4`
- Shell: `1.3.3.0`
- .Net: `7.0.5`
- Windows: `22631.2715`

### Screenshots / Videos

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/101802956/031b4ffa-5583-4ca3-91d4-ec1297a81db4)

**Comment by Spiritreader** [comment]
That is normal, and is unrelated to Auto Dark Mode. 
It's just a Windows thing.

You can ask Microsoft on the Windows feedback hub to fix that.
