### ISSUE TITLE
UI error (ARM64 build)

### ISSUE THREAD

**Issue by awarson2233** [AutoDarkMode/Windows-Auto-Night-Mode#802]
### Description

UI error when clip setting button.

I try to build the arm64 version, it works well excepted this bug, please fix it, and release the official version for arm devices. 😊😊😊

### Log Data

 NightLightGovernor.EnableHook: could not start night light regkey monitor: TypeInitializationException > The type initializer for 'System.Management.ManagementPath' threw an exception. > System.Management.ManagementPath get_DefaultPath()

### Commit Hash, Version and Windows Build

- Commit: `57f35ac9`
- Service/App: `10.4.2.1`
- Updater: `not found`
- Shell: `1.3.3.0`
- .Net: `7.0.14`
- Windows: `22631.2792`

### Screenshots / Videos

![屏幕截图 2023-12-11 172552](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/101026605/1db689d7-06c3-4137-905e-129a01cc766c)

**Comment by Spiritreader** [comment]
Please refer to the collection issue for ARM build issues:

Short summary I don't have an ARM device, I can't test or fix anything. Therefore: No arm64 unless help from the community.

dup of #690
