### ISSUE TITLE
MS Store compatibility check

### ISSUE THREAD

**Issue by SaltfishAmi** [AutoDarkMode/Windows-Auto-Night-Mode#803]
### Description

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/14184974/6b15b95e-fc5e-40ed-9f26-9c8554c05c79)

Microsoft Store seemingly doesn't make x86_64 processors automatically support x86 apps. Is this something that can be fixed at your side?

### Log Data

irrevelant

### Commit Hash, Version and Windows Build

Windows 10 22H2, OS Build 19045.3803
Microsoft Store 22311.1401.2.0

**Comment by Armin2208** [comment]
Do you have a ARM based computer? Look at Windows Settings > System > About > System type
![grafik](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/32982430/93d6be50-a6b2-49cb-ad30-d7634d29cb96)

**Comment by SaltfishAmi** [comment]
@Armin2208 

Absolutely no.

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/14184974/5bc96164-541a-475b-a3f9-531b42b7680a)

**Comment by Armin2208** [comment]
Hmm I don't understand, why this incompatibility message appears. Seems like a bug by the Microsoft Store itself.  

What about other x86 win32 apps on the store, like [Apache OpenOffice](https://apps.microsoft.com/store/detail/XP89J5462CMGJD?ocid=pdpshare)?

**Comment by SaltfishAmi** [comment]
That's weird. Now it doesn't display the error.

Yes, it really looks like a bug at Microsoft side.
