### ISSUE TITLE
Wallpaper Switch Prioritizes Solid Color Wallpaper Before Picture, even when Picture is Selected.

### ISSUE THREAD

**Issue by 19stefanecg** [AutoDarkMode/Windows-Auto-Night-Mode#805]
### Description

When switching themes automatically, my wallpaper changes for a second to what I set it to be when it dark mode, but then quickly changes to what is set for the "solid color" wallpaper, even when it is not selected. I have tried, going to beta, uninstalling and reinstalling, repeating then deleting all data in "AppData" to no avail. The earliest I can remember this happening was about a week or 2 ago when I changed some RAM in my system. 

### Expected Behavior

When the theme changes, my wallpaper should also switch according to what it is set to and stay there until another theme switch occurs.

When the theme changes, my wallpaper switches for a second, then switches to the "solid color" wallpaper instead, even though it is not currently selected.

### Log Data

[Files.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/13744527/Files.zip)

### Commit Hash, Version and Windows Build

- Commit: `cf7a0fe`
- Service/App: `10.4.1.1`
- Updater: `3.1.4`
- Shell: `1.3.3.0`
- .Net: `7.0.5`
- Windows: `22621.2861`

### Screenshots / Videos

[Uploading Auto Dark Mode Troubleshooting Video.zip…]()

**Comment by Spiritreader** [comment]
Should be fixed in the latest beta build 10.4.2.4

Please test!

**Comment by EliasOS** [comment]
> Should be fixed in the latest beta build 10.4.2.4
> 
> Please test!

Yeahm, fixed ❤️
