### ISSUE TITLE
Add bule light 'filter' and brightness controls/sliders.

### ISSUE THREAD

**Issue by brunoosti** [AutoDarkMode/Windows-Auto-Night-Mode#806]
Would be nice to add a yellowish tint and lower the monitor brightness when switching to the dark theme (at scheduled night hours). Thank you! : )

**Comment by FlorentMasson** [comment]
There's a settings in Windows already, but it would be useful to have that linked to the same switch conditions (for instance "Don't switch while playing video games")
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/9975455/3268fcb2-b9a4-48f4-b0f8-ce3f746b1f0e)
