### ISSUE TITLE
Manual toggling

### ISSUE THREAD

**Issue by avi12** [AutoDarkMode/Windows-Auto-Night-Mode#807]
**Describe the enhancement or feature you'd like**
Suppose the theme should auto-turn to the light at 7 am, and auto-turn to dark at 4 pm
However, by toggling the theme at 3 pm (as I know that I'll be back late), it will set to dark mode and then I'll get a notification:
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/6422804/198c0b91-0507-4dfa-b58e-777125d6fc2c)

Instead, my desired solution is that once I toggle to dark mode, it will only auto-toggle it back to light mode at 7 am

**Comment by Spiritreader** [comment]
```
Instead, my desired solution is that once I toggle to dark mode, it will only auto-toggle it back to light mode at 7 am
```

That is precisely what happens.

Your sunset is at 15:50, and automatic theme switching will resume at that time. However, since it is already dark then, no switch will be performed.
