### ISSUE TITLE
Light mode not activated back

### ISSUE THREAD

**Issue by enricodarodda** [AutoDarkMode/Windows-Auto-Night-Mode#813]
### Description

I set the dark mode activation according to geographical coordinates, but it doesn't switch back to the light theme if i switch on the computer after sunrise time. Is it the correct behaviour?

### Expected Behavior

Light theme mode should be enabled back as soon as I turn on the computer, even though sunrise time already passed. Clearly this should not happen if sunset time passed too, it should remain the dark theme in that case.

### Log Data

not present...if required will be provided

### Commit Hash, Version and Windows Build

- Commit: `cf7a0fe`
- Service/App: `10.4.1.1`
- Updater: `3.1.4`
- Shell: `1.3.3.0`
- .Net: `7.0.5`
- Windows: `19045.3930`

**Comment by Armin2208** [comment]
Log Data is required to help you

**Comment by enricodarodda** [comment]
Maybe I understood the problem: when i activate the flag "enable dark mode on battery" it always stays black. I thought it was something related to issues regarding the inability to trigger dark/light mode on laptops, but it appears that it always stays black and that's it. If this is the intended behaviour it is possible to close the issue.

**Comment by Spiritreader** [comment]
> Maybe I understood the problem: when i activate the flag "enable dark mode on battery" it always stays black. I thought it was something related to issues regarding the inability to trigger dark/light mode on laptops, but it appears that it always stays black and that's it. If this is the intended behaviour it is possible to close the issue.

Yes, this is the intended behavior!

If you enable dark theme mode on battery and you don't have a charger plugged in, it is supposed to stay in dark mode, no matter what the current theme by-time would be.

**Comment by enricodarodda** [comment]
Sorry for the misunderstanding then, as i said, i thought it was a feature developed to overcome some problems related to laptops that when on battery they couldn't switch theme, and that would have forced somehow the trigger.
