### ISSUE TITLE
Spotlight background setting in theme file not persisted

### ISSUE THREAD

**Issue by hlqviet** [AutoDarkMode/Windows-Auto-Night-Mode#814]
### Description

When I chose Windows spotlight for the background option, the ADM theme file was generated correctly with `WindowsSpotlight=1`. But when the theme is toggled either automatically or manually, the newly generated theme file had `WindowsSpotlight=0`. This makes the background stay forever as a single picture.

### Expected Behavior

ADM should creates the theme file with `WindowsSpotlight=1` when Windows Spotlight is selected for background.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/14070771/service.log)
[config.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/14070772/config.txt)

### Commit Hash, Version and Windows Build

- Commit: `c8ee8c4`
- Service/App: `10.4.2.5`
- Updater: `not found`
- Shell: `1.3.3.0`
- .Net: `8.0.0`
- Windows: `22631.3085`

### Screenshots / Videos

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/5486625/e36c69df-829d-4f73-affc-1a85d3374f16)

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/5486625/d94fdb34-1cd8-47ff-ad55-3ed491e4dc65)

**Comment by Spiritreader** [comment]
Unfortunately, the logs look all okay.

I cannot reproduce your issue. If I disable the wallpaper switcher and toggle the theme, my `WindowsSpotlight=1` stays enabled.
If I enable the wallpaper switcher and set both of them to Spotlight, `WindowsSpotlight=1` also stays enabled in my testing.

Can you provide more detailed reproduction instructions or a video that leads you to get the incorrect behavior you're descriibing?
Thanks!

**Comment by hlqviet** [comment]
I tried starting fresh by removing %AppData%\AutoDarkMode

https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/5486625/95aa6f55-ff0c-4af3-aec6-de6646f7bcd6
