### ISSUE TITLE
Suggestion for Next Updates

### ISSUE THREAD

**Issue by ual1n** [AutoDarkMode/Windows-Auto-Night-Mode#822]
Currently the change of themes is very sudden, simply one wallpaper changes to another when the time is reached, so I suggest that the change is smooth, and have a transition between the images, to soften and make the change more cool.
It would also be interesting for the lock screen wallpaper to change along with the desktop wallpapers.

**Comment by Armin2208** [comment]
A smooth transition is not easy to implement and the amount of work isn't worth it.
