### ISSUE TITLE
ADM (presumably) generated a file 'overrides.json' on Desktop

### ISSUE THREAD

**Issue by oxjihun** [AutoDarkMode/Windows-Auto-Night-Mode#829]
### Description

2024-03-14 21:53, I noticed a file `%userprofile%\Desktop\overrides.json` which I wasn't aware of its origin. [overrides.json](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/14614077/overrides.json)

Due to the similarity of content between the file and `%userprofile%\scoop\apps\auto-dark-mode-np\current\adm-app\overrides.json`, I concluded that ADM could be the reason of such unexpected file generation. 

Couldn't reproduce the issue. 

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/14614112/service.log)
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/14614114/config.zip)

### Commit Hash, Version and Windows Build

- Commit: `cf7a0fe`
- Service/App: `10.4.1.1`
- Updater: `3.1.4`
- Shell: `1.3.3.0`
- .Net: `7.0.5`
- Windows: `22621.3296`

**Comment by Armin2208** [comment]
This is an automatically generated file by Windows when using location service in an non packaged app. I don't know why it's located at your Desktop, usually it will take place in AppData.

**Comment by Spiritreader** [comment]
ADM's execution directory remains in AppData. However, we are not maintaining the scoop installation method and it might be possible that it's launched with the wrong working directory.

Could you kindly check with a tool like processexplorer what the working directory of ADM is?

**Comment by oxjihun** [comment]
@Spiritreader Sorry for the late reply. 

Since it's my first time using the tool, I'm not sure if this is the right information but I would still like to proceed providing it. 

The screenshot below says that the 'Current directory' is `C:\Windows\System32`. 

![2024-06-28_23-24](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/91365109/6d16b2f8-4c16-47b6-b49a-4f3705799762)

**Comment by oxjihun** [comment]
@Armin2208 Should I be concerned of the fact that I have publicly uploaded a file related to my location? If yes, I'll try contacting GitHub Support to remove it.

**Comment by Armin2208** [comment]
> @Armin2208 Should I be concerned of the fact that I have publicly uploaded a file related to my location? If yes, I'll try contacting GitHub Support to remove it.

I don't see any personal information in the shared files. People just see your region is KO. I don't think this is a problem?
