### ISSUE TITLE
bug  menu

### ISSUE THREAD

**Issue by Aeakaw** [AutoDarkMode/Windows-Auto-Night-Mode#831]
左侧菜单过宽，且固定，可以做成自动之类吗？
另外，能否像任务管理器那样 展开/收缩？
The left menu is too wide and fixed. Can it be made automatic or something like that?
Also, can it be expanded/collapsed like the task manager?

**Comment by Armin2208** [comment]
Not planned. Why is it needed? Where is the problem?

**Comment by Aeakaw** [comment]
> Not planned. Why is it needed? What's the problem?

Too ugly, not refined enough
