### ISSUE TITLE
Glitchy switching. Glitch not going away even on uninstallation.

### ISSUE THREAD

**Issue by Koladweep** [AutoDarkMode/Windows-Auto-Night-Mode#842]
### Description

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/8be7525e-3e44-4154-b5c8-27b8159f02c9)

### Expected Behavior

theme switch should be complete not partial. but I see that the theme in apps is permanently stuck in dark mode and fonts are of very low contrast. This doesn't go away even on uninstalling the application.

### Log Data

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/d0bb9ceb-
[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/15090336/config.yaml.txt)
543f-4e1b-94bd-4a4fde3eaeb0)
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/15090342/service.log)

Update, switching to high contrast White is a temporary relief and makes the screen readable, but the problem with the other modes persists.
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/1f7d3d49-966c-4c6d-964e-de0b3c10d90b)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/06f5bbf9-e9ac-4b41-a5c9-e757b96e6afa)

### Commit Hash, Version and Windows Build

Windows 10 22H2 OS Build 19045.4291

### Screenshots / Videos

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/2788b43a-ffca-4dd6-ac64-8d306f0be316)

**Comment by Spiritreader** [comment]
Please provide all of the requested information necessary for a bug report


```
Log Data

Attach the service.log file
Attach the config.yaml file
They can be found in %AppData%\AutoDarkMode
```

Please also note that by default, Windows' task manager does not support dark mode.

I cannot reproduce this issue on my 19045.4291 test machine with the latest Auto Dark Mode Beta

**Comment by Koladweep** [comment]
Thanks for responding.
I did attach the files earlier but it seems that this forum doesn't support yaml attachments. I tried renaming it to txt but I see that my earlier upload isn't available. I have zipped them here:
config.yaml and service.log
I understand that task manager doesn't support dark mode by default, but it does support high contrast. It seems that there has been some permanent alteration to it's template due to conflict in the AutoDarkMode app and high contrast theme.
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/d418164a-b230-4d02-9274-96302007fd6e)
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/067e36f5-c0a8-49e8-872f-f6bc2f08f383)

[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/15104805/config.zip)

**Comment by Koladweep** [comment]
update. I see other things have changed too. See the text in menus in the editor window? Same happens when using web browser. I have noticed this issue in past before using AutoDarkMode but it used to go away with a restart of explorer.exe but now it seems to have become permanent.
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/401b2e31-ec1f-4dc9-b03a-c7d5ee793ef4)

**Comment by Koladweep** [comment]
>  custom themes (as applied via secureuxtheme for example) don't work.

I'm using stock theme. This is some kind of corruption of theme or configuration that happened it seems.
The good news is that only my account is affected. A clean account will save me the botheration of a fresh Windows install. (Will have to migrate data, softwares and packages- can be done with Winget)
Here it is. clean as fresh: 
![Screenshot 2024-04-27 113312](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/0d6afb7f-9256-4034-86c1-c34c5b505b31)

I'm sorry I don't have a code fix to offer. Just a suggestion for someone with similar issue.

**Comment by Koladweep** [comment]
> Please provide all of the requested information necessary for a bug report
> 
> ```
> Log Data
> 
> Attach the service.log file
> Attach the config.yaml file
> They can be found in %AppData%\AutoDarkMode
> ```
> 
> Please also note that by default, Windows' task manager does not support dark mode.
> 
> I cannot reproduce this issue on my 19045.4291 test machine that with the latest Auto Dark Mode Beta. ADM only supports stock, unpatched themes at this time, custom themes (as applied via secureuxtheme for example) don't work.

**Comment by Koladweep** [comment]
I don't know what fixed it, but after a few restarts, the issue seems to have fixed itself 😅
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/102764937/c8ed553f-f78a-4ef5-9a2d-91cd7e61ff2b)
I was considering moving stuff to a new account, but it seems things fixed themselves after I had to force a restart when the machine froze. 
So, I guess this was some cache issue post uninstallation.

**Comment by Spiritreader** [comment]
Thanks for the investigation!
I have to reiterate that the only thing that Auto Dark Mode does is calling a Windows API to instruct Windows to switch to another Windows theme.

W10 is sort of kind of on the back burner since it's support ends in 2025, but it could be that some value in the theme file that ADM writes causes this 

However, if there is a bug with this theme switching API itself, that causes corruption for multiple users, we cannot do anything to fix it other than stop supporting W10 altogether because it's within Windows and we depend on it to work. 

Since I've never seen this happen on any test machine and you are the first one to report such an issue, I'm reluctant to do so because it will probably annoy a lot of people.

Maybe W10 somehow respects the old win2k color values.
When the task manager starts glitching, does manually applying a standard theme via the windows control panel fix the issue?

**Comment by Koladweep** [comment]
As I mentioned earlier, this font having low contrast with its backdrop happens often in Windows-10 and is generally fixed with a restart of Windows Explorer or a full system restart. 
But when this happened in conjunction with AutoDarkMode being used and the regular fix didn't work I suspected a bug in the app. I still don't know what fixed the issue. All I did was restart a few times. (I rarely do that and only did when system froze twice yesterday)

**Comment by Koladweep** [comment]
Thanks for explaining the workings of the application. I am not familiar with C#
I'm grateful it was resolved.
> When the task manager starts glitching, does manually applying a standard theme via the windows control panel fix the issue?
I haven't tried custom themes. I did try switching dark and light modes and high contrast themes. That didn't fix it.
However, as I mentioned earlier what I observed:
1) Restart (thrice yesterday. I rarely restart the machine🙂) however this wasn't fixing things earlier.
2) I created a fresh User account to see if it would inherit the same issue- It didn't. I was planning to move my stuff there when I found that the issue was resolved.

**Comment by Spiritreader** [comment]
> 2\. I created a fresh User account to see if it would inherit the same issue- It didn't. I was planning to move my stuff there when I found that the issue was resolved.

That's why i think applying a default windows theme like this
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/18438899/13c72578-03a5-41bd-9b8d-8bc52aa4c12d)

has a potential of fixing it.

I'm not really sure what causes this in the first place, but if we can find the trigger then we can at least warn the user / prevent them from entering this state.
