### ISSUE TITLE
Enable Light Mode on Battery

### ISSUE THREAD

**Issue by CyberBonk** [AutoDarkMode/Windows-Auto-Night-Mode#851]
**Describe the enhancement or feature you'd like**
i actually want to make the app to enable Light Mode when unplugged, the opposite to enable Dark mode on battery option,

reason is simple, i have a 2k IPS Panel, and there is no efficiency gains in dark mode except having to increase brightness to see better
**Describe alternatives you've considered**

**Additional context**

**Comment by Armin2208** [comment]
![grafik](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/32982430/a6ae6764-1847-4fc0-b866-1ac37c7b4669)

**Comment by Xriuk** [comment]
The highlighted option doesn't seem to address the request. An opposite switch would be needed

**Comment by Armin2208** [comment]
Whats the use case?

**Comment by Xriuk** [comment]
My current use case would be to switch to light mode on battery because I'm probably outside with my laptop and need brighter windows outdoors. I use dark mode by default when I'm indoors.

**Comment by Armin2208** [comment]
> My current use case would be to switch to light mode on battery because I'm probably outside with my laptop and need brighter windows outdoors. I use dark mode by default when I'm indoors.

Thanks for clarification. Does your Laptop has an Ambient Light Sensor? Currently we are working on a feature to switch the theme based on the brightness of your environment. Maybe this could serve the same use case.

**Comment by Xriuk** [comment]
I don't think it has a light sensor, how can I check it?

**Comment by Armin2208** [comment]
I think the easiest thing would be to join the Auto Dark Mode Beta (Settings > Update Channel) and look if you can enable the Ambient Light Sensor switch

<img width="1182" height="928" alt="Image" src="https://github.com/user-attachments/assets/2ddf7e50-b278-4177-9705-09ac62aff54f" />

**Comment by Xriuk** [comment]
Just checked, no ambient light sensor for me. So the battery trigger could be useful

**Comment by Armin2208** [comment]
Normally I don't like too much customization, but maybe this could make sense

**Comment by Xriuk** [comment]
Yeah, I mean the option is already there. Just left to add a dropdown to select dark or light mode instead of dark only.
