### ISSUE TITLE
why so huge a package?

### ISSUE THREAD

**Issue by Streamlet** [AutoDarkMode/Windows-Auto-Night-Mode#862]
A.T.T.

**Comment by Armin2208** [comment]
Because we include the whole .net runtime with the Auto Dark Mode Installer. As long as Microsoft doesn't include this into Windows, we will continue doing that.

**Comment by Streamlet** [comment]
would you make a pure release and point our which version of .Net Framework is required?

**Comment by Armin2208** [comment]
why should we?

**Comment by Streamlet** [comment]
(please feel free, it's just a suggestion. if you don't agree, treat it as nothing.)

**Comment by Streamlet** [comment]
for me, a traditional depveloper, if my logical sized 10M, my dependency sized 100K (my code size is far far larger than my dependency), i may include this dependency.

but for the opposite situation, i will feel hard to do it such way.
