### ISSUE TITLE
Add Extend setting for wallpaper

### ISSUE THREAD

**Issue by nicola02nb** [AutoDarkMode/Windows-Auto-Night-Mode#864]
**Describe the enhancement or feature you'd like**
When selecting a wallpaper there should ba also a setting to extend a wallpaper in multiple screens

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/61830443/59e0a03d-6f86-4185-95d8-71bb6a79d367)
Those are default settings for wallpapers in windwos

**Comment by Spiritreader** [comment]
This is (sadly) by design. There is an issue with extend mode if set via the API path we're using. If you want to span wallpapers across multiple screens, we recommend you split it into two wallpapers and set it individually for each monitor with the wallpaper (multi monitor) mode

**Comment by nicola02nb** [comment]
I found a workaround by creating a theme with wallpaper set with extend mode.
Then i setted up the app to switch theme
