### ISSUE TITLE
[Suggestion] Add Win X menu items

### ISSUE THREAD

**Issue by khuongduybui** [AutoDarkMode/Windows-Auto-Night-Mode#87]
Maybe a submenu of 3 options: 

switch to light (and pause auto switch), 

switch to dark (and pause auto switch),

resume auto switch

**Comment by Armin2208** [comment]
Hey,

thanks for the idea. But I will not implement this, sorry! You can easily switch the theme in version 2.X with the jump list and in 3.0 (coming later this year) with the tray icon or with a keyboard shortcut.

Thanks for your suggestion!

**Comment by khuongduybui** [comment]
but it's really easy though, haven't you checked?

All we need to do is put a few shortcuts into a folder and put that folder under `%USERPROFILE%\AppData\Local\Microsoft\Windows\WinX`

Maybe I can do a quick PR if you like?

**Comment by JesFEREM** [comment]
That does sound pretty nice and easy solution

**Comment by Armin2208** [comment]
canceled feature, because we don't want to edit th a system menu. 
Our new tray icon is already a great and wasy way to force dark or light theme (coming 5th october)
