### ISSUE TITLE
Feature Request: Make the cursor change with dark mode

### ISSUE THREAD

**Issue by RTR-RDD** [AutoDarkMode/Windows-Auto-Night-Mode#873]
Can you make a new function which can change the cursor color when the dark mode on.

**Comment by Randomaker** [comment]
You can already select a different cursor for light/dark mode. Just go to personalization - pick mouse cursors.

**Comment by RTR-RDD** [comment]
干啥？

**Comment by Randomaker** [comment]
Just select a light-colored cursor for light mode, and a dark-colored cursor for dark mode. Pretty self-explanatory.

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Armin2208** [comment]
Hopefully if he comes bock from his vacation, he will see that this feature is already supported.
