### ISSUE TITLE
How do I set the theme color to switch every 30 minutes?

### ISSUE THREAD

**Issue by billowssun** [AutoDarkMode/Windows-Auto-Night-Mode#875]
### Question
I need to switch between dark and light colors every 30 minutes and I don't know how I should set it up

**Comment by yogeshwar-b** [comment]
You can write another script that does this and just run it in the background.

```
@echo off
:loop
echo 'Theme Switch initiated' %date% %time%
<path to AutoDarkModeShell.exe> --swap
timeout /t <seconds to wait> > NUL /nobreak
goto loop
```

**Comment by billowssun** [comment]
> You can write another script to do this, just run it in the background.
>
> The following is an example of a Windows batch file.
>
> You need to update the path and wait seconds for AutoDarkModeShell.exe, save it in a Something.bat file and run it in the console.
>
> ```
> @echo off
> :loop
> echo 'Theme switch initiated' %date% %time%
> <path to AutoDarkModeShell.exe> --swap
> timeout /t <seconds to wait> > NUL /nobreak
> goto loop
> ```

Can't I just use the software's custom scripts to achieve this?

**Comment by Spiritreader** [comment]
> > You can write another script to do this, just run it in the background.
> > The following is an example of a Windows batch file.
> > You need to update the path and wait seconds for AutoDarkModeShell.exe, save it in a Something.bat file and run it in the console.
> > ```
> > @echo off
> > :loop
> > echo 'Theme switch initiated' %date% %time%
> > <path to AutoDarkModeShell.exe> --swap
> > timeout /t <seconds to wait> > NUL /nobreak
> > goto loop
> > ```
> 
> Can't I just use the software's custom scripts to achieve this?

The custom scripts are hooks when the theme changes, basically a callback. You can't configure the scripts to call a switch yourself, otherwise you would run into recursion problems.
