### ISSUE TITLE
Suggestion to add some description

### ISSUE THREAD

**Issue by RyanLeigh39** [AutoDarkMode/Windows-Auto-Night-Mode#89]
Hey,there
I found this program can't perform correctly without microsoft visual c++,so i think u should add some description

**Comment by Armin2208** [comment]
sorry, but I am using fresh windows installs to test Auto Dark Mode. And even with everything uninstalled and every feature disabled I still don't need visual c++

**Comment by Spiritreader** [comment]
> Hey,there
> I found this program can't perform correctly without microsoft visual c++,so i think u should add some description

"Doesn't perform correctly" is very unspecific.
Please provide some more detail on what **exactly** isn't working without C++ runtimes.
