### ISSUE TITLE
Feature Request: Is it possible to enable dark theme for third party apps automatically

### ISSUE THREAD

**Issue by floppypoppy** [AutoDarkMode/Windows-Auto-Night-Mode#90]
Microsoft Office apps like word, excel etc supports dark theme but need to enable manually. Foxit, Adobe pdf readers, and some more popular apps for windows 10 now support dark theme but need to manually enable the dark theme. Is there any possible way to force these app to automatically switch to dark theme based on windows default theme.

**Comment by zheolls** [comment]
You should advise those developers add the following Windows10 theme feature.
The Auto Dark Mode just change the theme actually.

**Comment by NicTanghe** [comment]
i made a powershell script to autochange vscode theme to a dark theme i diden't make a propper readme tho and i fergot wich global variables you need to add. you can have a look at it and try and fix it if it doesn't work.

**Comment by NicTanghe** [comment]
I'd recomend adding a run script on switch to day/ night this way the automation whould be eazyer.
